import DeepWiki.SymbolicIntegration.Core.Polynomial.Groebner.DivideOutCommonFactor
import DeepWiki.SymbolicIntegration.Core.Polynomial.Groebner.CommonFactor

/-! # Divided Groebner basis

The quotient ideal generated by the divided basis, its Groebner-basis structure,
and the final unconditional Lazard factorization theorem.
-/

open MvPolynomial MonomialOrder

namespace DeepWiki.SymbolicIntegration

/-- **Membership in the divided ideal** (cancel the common factor `H`, domain). For a finite family
`q : ι → MvPolynomial σ K` and `H ≠ 0`, a polynomial `g` lies in `span (range q)` iff `H·g` lies in
`span (range (H · q))`: forward multiplies a representation by `H`; backward cancels `H`
(`mul_left_cancel₀`). -/
theorem mem_span_divided_iff {σ K : Type*} [Field K] {ι : Type*} [Fintype ι]
    (q : ι → MvPolynomial σ K) {H : MvPolynomial σ K} (hH : H ≠ 0) (g : MvPolynomial σ K) :
    g ∈ Ideal.span (Set.range q) ↔
      H * g ∈ Ideal.span (Set.range (fun i => H * q i)) := by
  classical
  constructor
  · intro hg
    rw [Ideal.mem_span_range_iff_exists_fun] at hg ⊢
    obtain ⟨c, hc⟩ := hg
    refine ⟨c, ?_⟩
    rw [← hc, Finset.mul_sum]
    exact Finset.sum_congr rfl (fun i _ => by ring)
  · intro hHg
    rw [Ideal.mem_span_range_iff_exists_fun] at hHg ⊢
    obtain ⟨c, hc⟩ := hHg
    refine ⟨c, ?_⟩
    apply mul_left_cancel₀ hH
    rw [← hc, Finset.mul_sum]
    exact Finset.sum_congr rfl (fun i _ => by ring)

/-- **The common `y`-factor `gbYGcd` is nonzero**: the gcd of the nonzero basis views is nonzero. -/
theorem gbYGcd_ne_zero {K : Type*} [Field K] {I : Ideal (MvPolynomial (Fin 2) K)}
    {B : Finset (MvPolynomial (Fin 2) K)}
    (hB : IsReducedGroebnerBasis MonomialOrder.lex I (↑B : Set (MvPolynomial (Fin 2) K)))
    (hne : (Finset.univ : Finset (Fin B.card)).Nonempty) : gbYGcd hB ≠ 0 := by
  letI := gcdMonoidLazardRing K
  rw [gbYGcd, Ne, Finset.gcd_eq_zero_iff]
  push Not
  obtain ⟨i, hi⟩ := hne
  exact ⟨i, hi, lazardView_eq_zero_iff.not.mpr (hB.ne_zero (sortedByYDegree_mem hB i))⟩

/-- **The bivariate common factor `H = gbCommonYFactor hB` is nonzero**. -/
theorem gbCommonYFactor_ne_zero {K : Type*} [Field K] {I : Ideal (MvPolynomial (Fin 2) K)}
    {B : Finset (MvPolynomial (Fin 2) K)}
    (hB : IsReducedGroebnerBasis MonomialOrder.lex I (↑B : Set (MvPolynomial (Fin 2) K)))
    (hne : (Finset.univ : Finset (Fin B.card)).Nonempty) : gbCommonYFactor hB ≠ 0 := by
  intro h0
  apply gbYGcd_ne_zero hB hne
  rw [← lazardView_gbCommonYFactor hB, h0, lazardView, map_zero]

/-- The divided basis cofactor, pulled back to `K[x,y]`. -/
noncomputable def dividedBasis {K : Type*} [Field K] {I : Ideal (MvPolynomial (Fin 2) K)}
    {B : Finset (MvPolynomial (Fin 2) K)}
    (hB : IsReducedGroebnerBasis MonomialOrder.lex I (↑B : Set (MvPolynomial (Fin 2) K)))
    (hne : (Finset.univ : Finset (Fin B.card)).Nonempty) (i : Fin B.card) :
    MvPolynomial (Fin 2) K :=
  (finSuccEquiv K 1).symm (gbYGcdCofactor hB hne i)

/-- `lazardView (dividedBasis hB hne i) = gbYGcdCofactor hB hne i`. -/
@[simp] theorem lazardView_dividedBasis {K : Type*} [Field K] {I : Ideal (MvPolynomial (Fin 2) K)}
    {B : Finset (MvPolynomial (Fin 2) K)}
    (hB : IsReducedGroebnerBasis MonomialOrder.lex I (↑B : Set (MvPolynomial (Fin 2) K)))
    (hne : (Finset.univ : Finset (Fin B.card)).Nonempty) (i : Fin B.card) :
    lazardView (dividedBasis hB hne i) = gbYGcdCofactor hB hne i := by
  rw [dividedBasis, lazardView, AlgEquiv.apply_symm_apply]

/-- **The divided-basis factorization, bivariate form**: `H · qᵢ = fᵢ`. -/
theorem gbCommonYFactor_mul_dividedBasis {K : Type*} [Field K]
    {I : Ideal (MvPolynomial (Fin 2) K)} {B : Finset (MvPolynomial (Fin 2) K)}
    (hB : IsReducedGroebnerBasis MonomialOrder.lex I (↑B : Set (MvPolynomial (Fin 2) K)))
    (hne : (Finset.univ : Finset (Fin B.card)).Nonempty) (i : Fin B.card) :
    gbCommonYFactor hB * dividedBasis hB hne i = sortedByYDegree hB i := by
  apply lazardView_injective
  rw [lazardView, map_mul, ← lazardView, ← lazardView, lazardView_gbCommonYFactor,
    lazardView_dividedBasis]
  exact (gbYGcd_mul_cofactor hB hne i).symm

/-- **The divided basis is nonzero**. -/
theorem dividedBasis_ne_zero {K : Type*} [Field K] {I : Ideal (MvPolynomial (Fin 2) K)}
    {B : Finset (MvPolynomial (Fin 2) K)}
    (hB : IsReducedGroebnerBasis MonomialOrder.lex I (↑B : Set (MvPolynomial (Fin 2) K)))
    (hne : (Finset.univ : Finset (Fin B.card)).Nonempty) (i : Fin B.card) :
    dividedBasis hB hne i ≠ 0 := by
  intro h0
  exact hB.ne_zero (sortedByYDegree_mem hB i)
    (by rw [← gbCommonYFactor_mul_dividedBasis hB hne i, h0, mul_zero])

/-- **`lazardView` of a `K`-scalar multiple**. -/
theorem lazardView_C_scalar_mul {K : Type*} [Field K] (c : K) (f : MvPolynomial (Fin 2) K) :
    lazardView (MvPolynomial.C c * f) = Polynomial.C (MvPolynomial.C c) * lazardView f := by
  rw [lazardView, map_mul, lazardView]
  congr 1
  have h2 := RingHom.congr_fun (finSuccEquiv_comp_C_eq_C (R := K) 1) c
  simp only [RingHom.comp_apply] at h2
  exact ((finSuccEquiv K 1).symm_apply_eq.mp h2).symm

/-- The divided basis rescaled to lex-leading-coefficient `1`. -/
noncomputable def monicDividedBasis {K : Type*} [Field K] {I : Ideal (MvPolynomial (Fin 2) K)}
    {B : Finset (MvPolynomial (Fin 2) K)}
    (hB : IsReducedGroebnerBasis MonomialOrder.lex I (↑B : Set (MvPolynomial (Fin 2) K)))
    (hne : (Finset.univ : Finset (Fin B.card)).Nonempty) (i : Fin B.card) :
    MvPolynomial (Fin 2) K :=
  MvPolynomial.C (MonomialOrder.lex.leadingCoeff (dividedBasis hB hne i))⁻¹ * dividedBasis hB hne i

/-- The lex leading coefficient of `dividedBasis hB hne i` is nonzero. -/
theorem leadingCoeff_dividedBasis_ne_zero {K : Type*} [Field K] {I : Ideal (MvPolynomial (Fin 2) K)}
    {B : Finset (MvPolynomial (Fin 2) K)}
    (hB : IsReducedGroebnerBasis MonomialOrder.lex I (↑B : Set (MvPolynomial (Fin 2) K)))
    (hne : (Finset.univ : Finset (Fin B.card)).Nonempty) (i : Fin B.card) :
    MonomialOrder.lex.leadingCoeff (dividedBasis hB hne i) ≠ 0 :=
  MonomialOrder.lex.leadingCoeff_ne_zero_iff.mpr (dividedBasis_ne_zero hB hne i)

/-- `monicDividedBasis hB hne i ≠ 0`. -/
theorem monicDividedBasis_ne_zero {K : Type*} [Field K] {I : Ideal (MvPolynomial (Fin 2) K)}
    {B : Finset (MvPolynomial (Fin 2) K)}
    (hB : IsReducedGroebnerBasis MonomialOrder.lex I (↑B : Set (MvPolynomial (Fin 2) K)))
    (hne : (Finset.univ : Finset (Fin B.card)).Nonempty) (i : Fin B.card) :
    monicDividedBasis hB hne i ≠ 0 := by
  rw [monicDividedBasis, ← smul_eq_C_mul, smul_ne_zero_iff]
  exact ⟨inv_ne_zero (leadingCoeff_dividedBasis_ne_zero hB hne i), dividedBasis_ne_zero hB hne i⟩

/-- `lex.degree (monicDividedBasis hB hne i) = lex.degree (dividedBasis hB hne i)`. -/
theorem degree_monicDividedBasis {K : Type*} [Field K] {I : Ideal (MvPolynomial (Fin 2) K)}
    {B : Finset (MvPolynomial (Fin 2) K)}
    (hB : IsReducedGroebnerBasis MonomialOrder.lex I (↑B : Set (MvPolynomial (Fin 2) K)))
    (hne : (Finset.univ : Finset (Fin B.card)).Nonempty) (i : Fin B.card) :
    MonomialOrder.lex.degree (monicDividedBasis hB hne i)
      = MonomialOrder.lex.degree (dividedBasis hB hne i) :=
  degree_C_mul MonomialOrder.lex (inv_ne_zero (leadingCoeff_dividedBasis_ne_zero hB hne i)) _

/-- `lex.leadingCoeff (monicDividedBasis hB hne i) = 1`. -/
theorem leadingCoeff_monicDividedBasis {K : Type*} [Field K] {I : Ideal (MvPolynomial (Fin 2) K)}
    {B : Finset (MvPolynomial (Fin 2) K)}
    (hB : IsReducedGroebnerBasis MonomialOrder.lex I (↑B : Set (MvPolynomial (Fin 2) K)))
    (hne : (Finset.univ : Finset (Fin B.card)).Nonempty) (i : Fin B.card) :
    MonomialOrder.lex.leadingCoeff (monicDividedBasis hB hne i) = 1 := by
  rw [monicDividedBasis, leadingCoeff_C_mul MonomialOrder.lex
    (inv_ne_zero (leadingCoeff_dividedBasis_ne_zero hB hne i)),
    inv_mul_cancel₀ (leadingCoeff_dividedBasis_ne_zero hB hne i)]

/-- `lazardView (monicDividedBasis hB hne i)` is associated to the cofactor. -/
theorem lazardView_monicDividedBasis_associated {K : Type*} [Field K]
    {I : Ideal (MvPolynomial (Fin 2) K)} {B : Finset (MvPolynomial (Fin 2) K)}
    (hB : IsReducedGroebnerBasis MonomialOrder.lex I (↑B : Set (MvPolynomial (Fin 2) K)))
    (hne : (Finset.univ : Finset (Fin B.card)).Nonempty) (i : Fin B.card) :
    Associated (gbYGcdCofactor hB hne i) (lazardView (monicDividedBasis hB hne i)) := by
  rw [monicDividedBasis, lazardView_C_scalar_mul, lazardView_dividedBasis]
  refine associated_unit_mul_right _ _ (Polynomial.isUnit_C.mpr ?_)
  exact (inv_ne_zero (leadingCoeff_dividedBasis_ne_zero hB hne i)).isUnit.map MvPolynomial.C

open scoped Classical in
/-- The quotient ideal generated by the monic divided basis. -/
noncomputable def dividedIdeal {K : Type*} [Field K] {I : Ideal (MvPolynomial (Fin 2) K)}
    {B : Finset (MvPolynomial (Fin 2) K)}
    (hB : IsReducedGroebnerBasis MonomialOrder.lex I (↑B : Set (MvPolynomial (Fin 2) K)))
    (hne : (Finset.univ : Finset (Fin B.card)).Nonempty) : Ideal (MvPolynomial (Fin 2) K) :=
  Ideal.span (Set.range (monicDividedBasis hB hne))

/-- `span {monicDividedBasis} = span {dividedBasis}`. -/
theorem span_monicDividedBasis_eq {K : Type*} [Field K] {I : Ideal (MvPolynomial (Fin 2) K)}
    {B : Finset (MvPolynomial (Fin 2) K)}
    (hB : IsReducedGroebnerBasis MonomialOrder.lex I (↑B : Set (MvPolynomial (Fin 2) K)))
    (hne : (Finset.univ : Finset (Fin B.card)).Nonempty) :
    Ideal.span (Set.range (monicDividedBasis hB hne))
      = Ideal.span (Set.range (dividedBasis hB hne)) := by
  apply le_antisymm <;> rw [Ideal.span_le] <;> rintro _ ⟨i, rfl⟩
  · rw [monicDividedBasis, SetLike.mem_coe]
    exact Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨i, rfl⟩)
  · rw [SetLike.mem_coe]
    have : dividedBasis hB hne i
        = MvPolynomial.C (MonomialOrder.lex.leadingCoeff (dividedBasis hB hne i))
            * monicDividedBasis hB hne i := by
      rw [monicDividedBasis, ← mul_assoc, ← C_mul,
        mul_inv_cancel₀ (leadingCoeff_dividedBasis_ne_zero hB hne i), C_1, one_mul]
    rw [this]
    exact Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨i, rfl⟩)

/-- The divided-ideal membership equivalence `g ∈ I' ↔ H * g ∈ I`. -/
theorem mem_dividedIdeal_iff {K : Type*} [Field K] {I : Ideal (MvPolynomial (Fin 2) K)}
    {B : Finset (MvPolynomial (Fin 2) K)}
    (hB : IsReducedGroebnerBasis MonomialOrder.lex I (↑B : Set (MvPolynomial (Fin 2) K)))
    (hne : (Finset.univ : Finset (Fin B.card)).Nonempty) (g : MvPolynomial (Fin 2) K) :
    g ∈ dividedIdeal hB hne ↔ gbCommonYFactor hB * g ∈ I := by
  classical
  rw [dividedIdeal, span_monicDividedBasis_eq hB hne,
    mem_span_divided_iff (dividedBasis hB hne) (gbCommonYFactor_ne_zero hB hne) g]
  have hfun : (fun i => gbCommonYFactor hB * dividedBasis hB hne i) = sortedByYDegree hB :=
    funext (fun i => gbCommonYFactor_mul_dividedBasis hB hne i)
  rw [hfun, range_sortedByYDegree hB, hB.isGroebnerBasis.span_eq]

/-- Leading-monomial domination for the divided ideal. -/
theorem exists_degree_le_dividedIdeal {K : Type*} [Field K] {I : Ideal (MvPolynomial (Fin 2) K)}
    {B : Finset (MvPolynomial (Fin 2) K)}
    (hB : IsReducedGroebnerBasis MonomialOrder.lex I (↑B : Set (MvPolynomial (Fin 2) K)))
    (hne : (Finset.univ : Finset (Fin B.card)).Nonempty)
    {g : MvPolynomial (Fin 2) K} (hgI : g ∈ dividedIdeal hB hne) (hg0 : g ≠ 0) :
    ∃ b ∈ Set.range (monicDividedBasis hB hne),
      MonomialOrder.lex.degree b ≤ MonomialOrder.lex.degree g := by
  have hH : gbCommonYFactor hB ≠ 0 := gbCommonYFactor_ne_zero hB hne
  have hHg0 : gbCommonYFactor hB * g ≠ 0 := mul_ne_zero hH hg0
  have hHgI : gbCommonYFactor hB * g ∈ I := (mem_dividedIdeal_iff hB hne g).mp hgI
  obtain ⟨b, hbB, _, hble⟩ := hB.isGroebnerBasis.exists_degree_le hHgI hHg0
  rw [← range_sortedByYDegree hB] at hbB
  obtain ⟨ib, rfl⟩ := hbB
  rw [← gbCommonYFactor_mul_dividedBasis hB hne ib] at hble
  rw [degree_mul hH (dividedBasis_ne_zero hB hne ib), degree_mul hH hg0,
    add_le_add_iff_left] at hble
  exact ⟨monicDividedBasis hB hne ib, ⟨ib, rfl⟩,
    (degree_monicDividedBasis hB hne ib).le.trans hble⟩

/-- The monic divided family is a Groebner basis of the quotient ideal. -/
theorem isGroebnerBasis_dividedBasis {K : Type*} [Field K] {I : Ideal (MvPolynomial (Fin 2) K)}
    {B : Finset (MvPolynomial (Fin 2) K)}
    (hB : IsReducedGroebnerBasis MonomialOrder.lex I (↑B : Set (MvPolynomial (Fin 2) K)))
    (hne : (Finset.univ : Finset (Fin B.card)).Nonempty) :
    IsGroebnerBasis MonomialOrder.lex (dividedIdeal hB hne)
      (Set.range (monicDividedBasis hB hne)) := by
  refine isGroebnerBasis_of_exists_leadingMonomial_le ?_ ?_ ?_
  · rintro _ ⟨i, rfl⟩
    exact Ideal.subset_span ⟨i, rfl⟩
  · rintro _ ⟨i, rfl⟩
    rw [leadingCoeff_monicDividedBasis hB hne i]
    exact isUnit_one
  · rintro g hgI hg0
    exact exists_degree_le_dividedIdeal hB hne hgI hg0

/-- The divided basis is index-injective. -/
theorem monicDividedBasis_injective {K : Type*} [Field K] {I : Ideal (MvPolynomial (Fin 2) K)}
    {B : Finset (MvPolynomial (Fin 2) K)}
    (hB : IsReducedGroebnerBasis MonomialOrder.lex I (↑B : Set (MvPolynomial (Fin 2) K)))
    (hne : (Finset.univ : Finset (Fin B.card)).Nonempty) :
    Function.Injective (monicDividedBasis hB hne) := by
  intro i j hij
  set ci := MonomialOrder.lex.leadingCoeff (dividedBasis hB hne i) with hci_def
  set cj := MonomialOrder.lex.leadingCoeff (dividedBasis hB hne j) with hcj_def
  have hci : ci ≠ 0 := leadingCoeff_dividedBasis_ne_zero hB hne i
  have hcj : cj ≠ 0 := leadingCoeff_dividedBasis_ne_zero hB hne j
  have key : MvPolynomial.C ci⁻¹ * sortedByYDegree hB i
      = MvPolynomial.C cj⁻¹ * sortedByYDegree hB j := by
    have e : ∀ k : Fin B.card,
        gbCommonYFactor hB * monicDividedBasis hB hne k
          = MvPolynomial.C (MonomialOrder.lex.leadingCoeff (dividedBasis hB hne k))⁻¹
            * sortedByYDegree hB k := by
      intro k
      rw [monicDividedBasis, mul_left_comm, gbCommonYFactor_mul_dividedBasis]
    have := congrArg (fun p => gbCommonYFactor hB * p) hij
    simp only [e] at this
    exact this
  have hlc := congrArg (fun p => MonomialOrder.lex.leadingCoeff p) key
  simp only [leadingCoeff_C_mul MonomialOrder.lex (inv_ne_zero hci),
    leadingCoeff_C_mul MonomialOrder.lex (inv_ne_zero hcj),
    hB.2.1 _ (sortedByYDegree_mem hB i), hB.2.1 _ (sortedByYDegree_mem hB j), mul_one] at hlc
  rw [hlc] at key
  exact sortedByYDegree_injective hB
    (mul_left_cancel₀ (by rw [Ne, MvPolynomial.C_eq_zero]; exact inv_ne_zero hcj) key)

/-- The divided basis has pairwise non-dividing leading monomials. -/
theorem dividedBasis_leadingMonomial_not_le {K : Type*} [Field K]
    {I : Ideal (MvPolynomial (Fin 2) K)} {B : Finset (MvPolynomial (Fin 2) K)}
    (hB : IsReducedGroebnerBasis MonomialOrder.lex I (↑B : Set (MvPolynomial (Fin 2) K)))
    (hne : (Finset.univ : Finset (Fin B.card)).Nonempty) {i i' : Fin B.card} (hii : i ≠ i') :
    ¬ (MonomialOrder.lex.degree (monicDividedBasis hB hne i')
        ≤ MonomialOrder.lex.degree (monicDividedBasis hB hne i)) := by
  rw [degree_monicDividedBasis, degree_monicDividedBasis]
  refine leadingMonomial_cofactor_not_le hB (gbCommonYFactor_ne_zero hB hne)
    (dividedBasis_ne_zero hB hne i) (dividedBasis_ne_zero hB hne i') ?_ ?_ ?_
  · rw [gbCommonYFactor_mul_dividedBasis]; exact sortedByYDegree_mem hB i
  · rw [gbCommonYFactor_mul_dividedBasis]; exact sortedByYDegree_mem hB i'
  · rw [gbCommonYFactor_mul_dividedBasis, gbCommonYFactor_mul_dividedBasis]
    exact fun h => hii (sortedByYDegree_injective hB h)

/-- The monic divided family has no common `y`-factor. -/
theorem monicDividedBasis_hasNoCommonYFactor {K : Type*} [Field K]
    {I : Ideal (MvPolynomial (Fin 2) K)} {B : Finset (MvPolynomial (Fin 2) K)}
    (hB : IsReducedGroebnerBasis MonomialOrder.lex I (↑B : Set (MvPolynomial (Fin 2) K)))
    (hne : (Finset.univ : Finset (Fin B.card)).Nonempty)
    (P : Polynomial (MvPolynomial (Fin 1) K))
    (hP : ∀ i : Fin B.card, P ∣ lazardView (monicDividedBasis hB hne i)) : IsUnit P := by
  refine cofactor_hasNoCommonYFactor hB hne P (fun i => ?_)
  exact (hP i).trans (lazardView_monicDividedBasis_associated hB hne i).symm.dvd

/-- Ideal-membership transfer of `P ∣ lazardView`. -/
theorem dvd_lazardView_of_mem_span {K : Type*}
    [Field K] {P : Polynomial (MvPolynomial (Fin 1) K)}
    {B' : Set (MvPolynomial (Fin 2) K)} (hP : ∀ b' ∈ B', P ∣ lazardView b')
    {g : MvPolynomial (Fin 2) K} (hg : g ∈ Ideal.span B') : P ∣ lazardView g := by
  refine Submodule.span_induction ?_ ?_ ?_ ?_ hg
  · intro x hx; exact hP x hx
  · rw [lazardView, map_zero]; exact dvd_zero _
  · intro x y _ _ hx hy; rw [lazardView, map_add]; exact dvd_add hx hy
  · intro a x _ hx
    rw [lazardView, smul_eq_mul, map_mul]
    exact Dvd.dvd.mul_left hx _

/-- Any reduced Groebner basis of the divided ideal has no common `y`-factor. -/
theorem hasNoCommonYFactor_of_dividedIdeal {K : Type*} [Field K]
    {I : Ideal (MvPolynomial (Fin 2) K)} {B : Finset (MvPolynomial (Fin 2) K)}
    (hB : IsReducedGroebnerBasis MonomialOrder.lex I (↑B : Set (MvPolynomial (Fin 2) K)))
    (hne : (Finset.univ : Finset (Fin B.card)).Nonempty)
    {B' : Finset (MvPolynomial (Fin 2) K)}
    (hB' : IsReducedGroebnerBasis MonomialOrder.lex (dividedIdeal hB hne)
      (↑B' : Set (MvPolynomial (Fin 2) K))) :
    HasNoCommonYFactor hB' := by
  intro P hP
  have hPB' : ∀ b' ∈ (↑B' : Set (MvPolynomial (Fin 2) K)), P ∣ lazardView b' := by
    intro b' hb'
    rw [← range_sortedByYDegree hB'] at hb'
    obtain ⟨j, rfl⟩ := hb'
    exact hP j
  have hPg : ∀ g ∈ dividedIdeal hB hne, P ∣ lazardView g := by
    intro g hg
    refine dvd_lazardView_of_mem_span hPB' ?_
    rwa [hB'.isGroebnerBasis.span_eq]
  refine monicDividedBasis_hasNoCommonYFactor hB hne P (fun i => ?_)
  exact hPg _ (Ideal.subset_span ⟨i, rfl⟩)

/-- Lazard factorization for any reduced basis of the divided ideal. -/
theorem lazard_Pk_eq_Rk_Sk_dividedIdeal {K : Type*} [Field K]
    {I : Ideal (MvPolynomial (Fin 2) K)} {B : Finset (MvPolynomial (Fin 2) K)}
    (hB : IsReducedGroebnerBasis MonomialOrder.lex I (↑B : Set (MvPolynomial (Fin 2) K)))
    (hne : (Finset.univ : Finset (Fin B.card)).Nonempty)
    {B' : Finset (MvPolynomial (Fin 2) K)}
    (hB' : IsReducedGroebnerBasis MonomialOrder.lex (dividedIdeal hB hne)
      (↑B' : Set (MvPolynomial (Fin 2) K)))
    (j : Fin B'.card) :
    ∃ S : Polynomial (MvPolynomial (Fin 1) K),
      lazardView (sortedByYDegree hB' j) = Polynomial.C (@Polynomial.content _ _
          (normalizedGcdMonoidMvPolynomialFinOne K) (lazardView (sortedByYDegree hB' j))) * S ∧
        Associated (@Polynomial.content _ _ (normalizedGcdMonoidMvPolynomialFinOne K)
          (lazardView (sortedByYDegree hB' j))) (leadingYCoeff (sortedByYDegree hB' j)) ∧
        S.IsPrimitive ∧ IsUnit S.leadingCoeff :=
  lazard_Pk_eq_Rk_Sk_of_hasNoCommonYFactor hB'
    (hasNoCommonYFactor_of_dividedIdeal hB hne hB') j

/-- Lazard factorization after dividing out the common factor, with no extra hypothesis. -/
theorem lazard_Pk_eq_Rk_Sk_unconditional {K : Type*} [Field K]
    {I : Ideal (MvPolynomial (Fin 2) K)} {B : Finset (MvPolynomial (Fin 2) K)}
    (hB : IsReducedGroebnerBasis MonomialOrder.lex I (↑B : Set (MvPolynomial (Fin 2) K)))
    (hne : (Finset.univ : Finset (Fin B.card)).Nonempty) :
    ∃ B' : Finset (MvPolynomial (Fin 2) K),
      ∃ hB' : IsReducedGroebnerBasis MonomialOrder.lex (dividedIdeal hB hne)
        (↑B' : Set (MvPolynomial (Fin 2) K)),
      ∀ j : Fin B'.card, ∃ S : Polynomial (MvPolynomial (Fin 1) K),
        lazardView (sortedByYDegree hB' j) = Polynomial.C (@Polynomial.content _ _
            (normalizedGcdMonoidMvPolynomialFinOne K) (lazardView (sortedByYDegree hB' j))) * S ∧
          Associated (@Polynomial.content _ _ (normalizedGcdMonoidMvPolynomialFinOne K)
            (lazardView (sortedByYDegree hB' j))) (leadingYCoeff (sortedByYDegree hB' j)) ∧
          S.IsPrimitive ∧ IsUnit S.leadingCoeff := by
  obtain ⟨B', hB'⟩ := exists_isReducedGroebnerBasis MonomialOrder.lex (dividedIdeal hB hne)
  exact ⟨B', hB', fun j => lazard_Pk_eq_Rk_Sk_dividedIdeal hB hne hB' j⟩

end DeepWiki.SymbolicIntegration
