import DeepWiki.Refine.CCOmega.ProofTransfer
import DeepWiki.Refine.ProofTransfer
import Sources.Doi_10_1145_3737283.Source

/-! # Section 3.1 - Proof transfer in type theory

Catalog pointers for the revised paper's CCω presentation, relational transfer witness, interface
encodings, and functional-pullback boundary case.

## NOT YET FORMALIZED

- Propositional equality and dependent-pair extensions, PDF p. 7 — [infra] semantic examples use
  Lean equality and structures, but the intrinsically scoped object syntax has not been extended
  with equality or sigma constructors.
- Structural synthesis by a meta-program composing registered related terms, PDF p. 8 — [deferred]
  the operational synthesis algorithm belongs to the later plugin sections rather than the `CCω`
  object language.
- Comparison with generalized rewriting and CoqEAL, PDF p. 8 — [external] these are capability
  claims about external tools rather than internal mathematical statements.
-/

namespace DeepWiki.CcmToplas

/-- **Section 3.1, PDF p. 7:** intrinsically scoped terms realize the five-constructor `CCω` grammar. -/
abbrev ccω_terms := DeepWiki.Refine.DependentCalculus.Term

/-- **Section 3.1, PDF p. 7:** dependent contexts are empty or extended by a typed declaration. -/
abbrev ccω_contexts := DeepWiki.Refine.DependentCalculus.Context

/-- **Section 3.1, PDF p. 7:** the parameters `S`, `T`, `V`, `W`, `RInput`, and `ROutput`. -/
abbrev proof_transfer_problem_context :=
  DeepWiki.Refine.DependentCalculus.TypeFormerTransfer.problemContext

/-- **Section 3.1, PDF p. 7:** the type `∀ s t, RInput s t → ROutput (V s) (W t)`. -/
abbrev proof_transfer_witness_type :=
  DeepWiki.Refine.DependentCalculus.TypeFormerTransfer.witnessType

/-- **Section 3.1, PDF p. 7:** the displayed transfer witness is a well-formed small type. -/
abbrev proof_transfer_witness_type_hasType :=
  DeepWiki.Refine.DependentCalculus.TypeFormerTransfer.witnessType_hasType

/-- **Section 3.1, PDF p. 7:** a solution packages the synthesized target `W` and witness `w`. -/
abbrev proof_transfer_solution := @DeepWiki.Refine.TypeFormerTransferSolution

/-- **Section 3.1, PDF p. 7:** the common output relation `ROutput A B := B → A`. -/
abbrev backward_output_relation :=
  DeepWiki.Refine.DependentCalculus.TypeFormerTransfer.backwardOutputRelation

/-- **Section 3.1, PDF p. 7:** the backward output relation is well typed in `CCω`. -/
abbrev backward_output_relation_hasType :=
  DeepWiki.Refine.DependentCalculus.TypeFormerTransfer.backwardOutputRelation_hasType

/-- **Section 3.1, PDF p. 7:** the semantic counterpart of the object-level backward relation. -/
abbrev backward_output_relation_semantics := @DeepWiki.Refine.BackwardArrow

/-- **Section 3.1, PDF p. 7:** a backward witness turns a target proof into a source proof. -/
abbrev backward_transfer_step := @DeepWiki.Refine.TypeFormerTransferSolution.transferProof

/-- **Section 3.1, PDF p. 8:** a carrier, zero, and successor form the common induction interface. -/
abbrev natural_number_interface := DeepWiki.Refine.NatSignature

/-- **Section 3.1, PDF p. 8:** the dependent eliminator generated by the common interface. -/
abbrev natural_number_interface_eliminator := @DeepWiki.Refine.NatSignature.Eliminator

/-- **Section 3.1, PDF p. 8:** an interface equivalence transfers its dependent eliminator. -/
abbrev natural_number_interface_transfer := @DeepWiki.Refine.NatSignatureEquiv.eliminator

/-- **Section 3.1, PDF p. 8:** a fixed-carrier zero/successor pair parameterizes induction. -/
abbrev fixed_carrier_operation_pair := DeepWiki.Refine.NatOperationPair

/-- **Section 3.1, PDF p. 8:** the fixed-carrier induction-shaped type former. -/
abbrev fixed_carrier_induction := DeepWiki.Refine.NatOperationPair.Induction

/-- **Section 3.1, PDF p. 8:** a functional input relation is the graph of a map `φ`. -/
abbrev functional_input_relation := @DeepWiki.Refine.PullbackRel

/-- **Section 3.1, PDF p. 8:** the canonical functional solution synthesizes `W = V ∘ φ`. -/
abbrev functional_pullback_solution := @DeepWiki.Refine.functionalPullbackSolution

/-- **Section 3.1, PDF p. 8:** the functional solution's target is definitionally `V (φ t)`. -/
abbrev functional_pullback_target := @DeepWiki.Refine.functionalPullbackSolution_target

/-- **Section 3.1, PDF p. 8:** structural conjugation gives the deliberately weak `W₂` candidate. -/
abbrev structural_induction_candidate := DeepWiki.Refine.NatOperationPair.ConjugatedInduction

end DeepWiki.CcmToplas
