import DeepWiki.SymbolicIntegration.DifferentialAlgebra
import DeepWiki.SymbolicIntegration.Core.Differential.NormalSpecial.Special

/-! # Differential ideals

Ideals closed under the derivation, including the bottom ideal and principal ideals generated by
special elements.
-/

open scoped Differential

namespace DeepWiki.SymbolicIntegration

/-- A **differential ideal** of `(R, D)` is an ideal `I` closed under `D` (`D I ⊆ I`). -/
def IsDifferentialIdeal {R : Type*} [CommRing R] [Differential R] (I : Ideal R) : Prop :=
  ∀ a ∈ I, a′ ∈ I

/-- `⊥` is a differential ideal and `constants R` is closed under `D`. -/
theorem isDifferentialIdeal_bot_and_deriv_mem_constants {R : Type*} [CommRing R] [Differential R] :
    IsDifferentialIdeal (⊥ : Ideal R) ∧ ∀ a ∈ constants R, a′ ∈ constants R := by
  refine ⟨fun a ha => ?_, fun a ha => ?_⟩
  · simp only [Ideal.mem_bot] at ha ⊢; simp [ha]
  · simp only [mem_constants] at ha ⊢; simp [ha]

/-- A special polynomial spans a differential ideal: `p ∣ p' → IsDifferentialIdeal (span {p})`. -/
theorem IsSpecial.isDifferentialIdeal {R : Type*} [CommRing R] [Differential R] {p : R}
    (hp : IsSpecial p) : IsDifferentialIdeal (Ideal.span {p}) := by
  intro a ha
  rw [Ideal.mem_span_singleton] at ha ⊢
  obtain ⟨b, rfl⟩ := ha
  rw [deriv_mul_eq]
  exact dvd_add (dvd_mul_right p b′) (hp.mul_left b)

end DeepWiki.SymbolicIntegration
