name = "deepwiki"
defaultTargets = ["Book"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "git#v4.30.0"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "v4.30.0"

[[lean_lib]]
name = "Book"
