import DeepWiki.SymbolicIntegration.RationalIntegrationGcdLogForm
import DeepWiki.SymbolicIntegration.RationalIntegrationAlgorithms.RothsteinTrager.ResidueMultiplicity
import DeepWiki.SymbolicIntegration.Core.Polynomial.Groebner
import DeepWiki.SymbolicIntegration.RationalIntegrationAlgorithms.RothsteinTrager.CzichowskiNormalPosition
import Sources.Doi_10_1006_jsco_1995_1043.Source

/-! # Czichowski catalog — the integral connection (Lemma 2.3 + part (iii))
Pointers to the library theorems realizing Czichowski's integral *connection*: his Gröbner-basis
logarithms `S(x,c) = gcd(D, A − c·D')` are exactly the Rothstein–Trager gcds (Lemma 2.3), so his integral
`∫ A/D = ∑ c·log(gcd(D, A − c·D'))` is the same logarithmic part as the §2.4/§2.5 RT/LRT result.

## NOT YET FORMALIZED (subtractive — delete each item once it is formalized) -/

open scoped Classical

namespace DeepWiki.Czi

/-- **Lemma 2.3** (p.165), Czichowski's logs are the Rothstein–Trager gcds: for split squarefree
`D = ∏_{α∈s}(X−α)`, `gcd(D, A − a·D') = ∏_{α∈s, A(α)/D'(α)=a}(X−α)` — the Gröbner-basis primitive part
`S(x,a)` at a residue `a` equals the Rothstein–Trager `Gₐ`. The library's `gcd_nodal_eq_prod_residue`. -/
abbrev lemma_2_3_gcd := @DeepWiki.SymbolicIntegration.gcd_nodal_eq_prod_residue

/-- **Czichowski part (iii)** (p.165, the integral): for `deg A < #s` over split squarefree
`D = ∏_{α∈s}(X−α)`, `∫ A/D = ∑_a a·log(gcd(D, A − a·D'))` — the same logarithmic part as Rothstein–Trager /
Lazard–Rioboo–Trager (§2.4/§2.5), with the RT gcd as the log argument. The library's
`ratFunc_eq_sum_residue_gcd`. -/
abbrev integral_logForm_gcd := @DeepWiki.SymbolicIntegration.ratFunc_eq_sum_residue_gcd

/-- **Lemma 2.2(iii)** (p.165, resultant side): the distinct roots of `R = res_x(A − t·D', D)` are exactly
the distinct residues `{A(α)/D'(α) : D(α) = 0}`, so the radical (squarefree part) of the resultant is
`∏(t − distinct residue)` — Czichowski's `R₁`. The library's `rtResultant_roots_toFinset`. -/
abbrev lemma_2_2_iii_roots := @DeepWiki.SymbolicIntegration.rtResultant_roots_toFinset

/-- **Lemma 2.2(iii)** (p.165, radical-divides): `R₁ = ∏(t − distinct root) ∣ R` — `R₁` is the squarefree
part (radical) of the resultant. The library's `czichowskiR1_dvd_rtResultant`. -/
abbrev lemma_2_2_iii_radical_dvd := @DeepWiki.SymbolicIntegration.czichowskiR1_dvd_rtResultant

/-- **Lemma 2.2(iii)** (p.165, the `z`-elimination ideal): the `z`-elimination ideal `I ∩ K[z]` of
`I = ⟨A − z·D', D⟩` is `(R₁)`, generated by the monic squarefree `R₁ = ∏_{distinct residue a}(z − a)` —
the content of the first pure-`z` element of the reduced Gröbner basis for the p.l. ordering `x > z`. The
library's `elimZ_eq_span_czichowskiR1`. -/
abbrev lemma_2_2_iii_elimination := @DeepWiki.SymbolicIntegration.elimZ_eq_span_czichowskiR1

/-- **Lemma 2.2(iii)** (p.165, `R₁ = radical(resultant)`): Czichowski's `R₁` equals the radical
(squarefree part) of the Rothstein–Trager resultant `R = res_x(A − z·D', D)`. The library's
`czichowskiR1_eq_radical_rtResultant`. -/
abbrev lemma_2_2_iii_radical_eq := @DeepWiki.SymbolicIntegration.czichowskiR1_eq_radical_rtResultant

/-- **The reduced-Gröbner-basis structure** Czichowski's note rests on, now general (Bronstein §2.6
defers to it): `Pₖ = Rₖ·Sₖ` for any reduced bivariate GB (`lazard_Pk_eq_Rk_Sk_unconditional`), built on
reduced-GB existence (`exists_isReducedGroebnerBasis`). The library's `lazard_Pk_eq_Rk_Sk_unconditional`. -/
abbrev groebner_structure_Pk_eq_Rk_Sk :=
  @DeepWiki.SymbolicIntegration.lazard_Pk_eq_Rk_Sk_unconditional

end DeepWiki.Czi
