import DeepWiki.ReactiveSystems.TimedTransitionSystems
import DeepWiki.ReactiveSystems.TimedCcs
import DeepWiki.ReactiveSystems.TimedCcsParallel
import DeepWiki.ReactiveSystems.TimedCcsDeterminacy
import DeepWiki.ReactiveSystems.TimedAlarmTimer
import DeepWiki.ReactiveSystems.TimedCcsDelayExamples
import DeepWiki.ReactiveSystems.TimedLightSwitch
import Sources.Doi_10_1017_CBO9780511814105.Source

/-! # Reactive Systems catalog — Chapter 9: CCS with time delays
Book-numbered restatements for the timed transition-system model of §9.2, the syntax and SOS rules of
timed CCS (§9.3), and parallel composition with maximal progress (§9.4), discharged by the
`DeepWiki.ReactiveSystems` library. -/

namespace DeepWiki.Rs

open DeepWiki.ReactiveSystems
open scoped NNReal

/-! ## §9.2 Timed labelled transition systems -/

/-- **Definition 9.1** (§9.2, p.164). A timed labelled transition system: an LTS
with label set `Lab = Act ∪ ℝ≥0` (ordinary actions and time delays). The
library's `TLTS` (over the combined label type `Act ⊕ ℝ≥0`). -/
abbrev def_9_1 := @TLTS

/-- **(9.2)** (§9.2, p.164), time determinism: a delay transition leads to a
unique state. The library's `TLTS.TimeDeterministic`. -/
abbrev eq_9_2 := @TLTS.TimeDeterministic

/-- **(9.3)** (§9.2, p.164), zero delay: every state reaches itself with a zero
delay. The library's `TLTS.ZeroDelay`. -/
abbrev eq_9_3 := @TLTS.ZeroDelay

/-- **(9.4)** (§9.2, p.165), time additivity / continuity: a delay of `d₁ + d₂`
is exactly a delay `d₁` followed by a delay `d₂`. The library's
`TLTS.TimeAdditive`. -/
abbrev eq_9_4 := @TLTS.TimeAdditive

/-! ## §9.3 Syntax and SOS rules of timed CCS (TCCS) -/

/-- **§9.3** (p.166). Timed CCS expressions: CCS extended with the delay-prefix
`ε(d).P` (`eps d P`). The library's `TCCS`. -/
abbrev timedCCS := @TCCS

/-- **§9.3** (Table 9.1, p.167), action SOS for TCCS: the CCS action rules plus
`ε(0).P —α→ P'`. The library's `TAct`. -/
abbrev tccsAct := @TAct

/-- **§9.3** (Table 9.1, p.167), delay SOS for TCCS: delay-prefix countdown and
consume, patient action-prefixes (`α ≠ τ`), componentwise choice/restrict/relabel
delays. The library's `TDelay`. -/
abbrev tccsDelay := @TDelay

/-- **Definition 9.1 / §9.3** (p.166). The timed LTS generated by a TCCS
definition environment. The library's `tccsTLTS`. -/
abbrev tccsTLTS := @DeepWiki.ReactiveSystems.tccsTLTS

/-- **§9.3** (eq. below 9.5, p.167). A delay-prefixed guard `ε(t).P` lets any
`d ≤ t` elapse, decrementing the prefix to `ε(t−d).P` — delays do not resolve
choices (they are deterministic). -/
theorem tccs_eps_delay {Name K : Type*} (defn : K → TCCS Name K) (t d : ℝ≥0)
    (h : d ≤ t) (P : TCCS Name K) :
    (DeepWiki.ReactiveSystems.tccsTLTS defn).delay (.eps t P) d (.eps (t - d) P) :=
  DeepWiki.ReactiveSystems.light_delay defn t d h P

/-! ## §9.4 Parallel composition: the maximal-progress assumption -/

/-- **§9.4** (p.170). The *maximal-progress assumption*: the silent action `τ` is
urgent — a state able to perform `τ` cannot let positive time elapse. The
library's `TLTS.MaximalProgress`. (This is the side condition forcing
synchronisations in a parallel composition to happen without delay; the full
parallel SOS with its `NoSync` premise is noted in the library.) -/
abbrev maximalProgress := @TLTS.MaximalProgress

/-- **§9.4** (p.170). The TCCS `τ`-prefix witnesses maximal progress: `τ.P` can
perform `τ` yet cannot delay any positive amount of time. -/
theorem tccs_tau_urgent {Name K : Type*} (defn : K → TCCS Name K) (P : TCCS Name K)
    (d : ℝ≥0) (hd : 0 < d) :
    ¬ ∃ Q, (DeepWiki.ReactiveSystems.tccsTLTS defn).delay (.pre DeepWiki.ReactiveSystems.Act.tau P) d Q :=
  DeepWiki.ReactiveSystems.tccs_tau_maximalProgress defn P d hd

/-- **Definition 9.2** (§9.3, p.166). Guardedness of a TCCS expression: every
constant occurrence lies within an action or positive-delay prefix. The library's
`IsGuarded` (process-level: `IsGuardedDefn`). -/
abbrev def_9_2 := @DeepWiki.ReactiveSystems.IsGuarded

/-- **Definition 9.2** (§9.3, p.166). A guarded definition environment. The
library's `IsGuardedDefn`. -/
abbrev def_9_2_defn := @DeepWiki.ReactiveSystems.IsGuardedDefn

/-- **Exercise 9.6** (§9.4, p.171). Of the four TCCS agents `M₁ ≝ ε(3).(ε(2).a.M₁+b.M₁)`,
`M₂ ≝ ε(5).a.M₂+ε(3).b.M₂`, `M₃ ≝ ε(3).(ε(2).a.M₃+τ.M₃)`, `M₄ ≝ ε(5).a.M₄+ε(3).τ.M₄`,
exactly `M₁` and `M₂` can delay by `4` (the `b`-prefix idles); `M₃`, `M₄` cannot, as
a `τ` becomes urgent after `3` units (maximal progress). The library's `tccsAgents_delay4_characterization`. -/
theorem ex_9_6 :
    TDelay DeepWiki.ReactiveSystems.defn96 (TCCS.const .M1) 4
        (TCCS.choice (TCCS.eps 1 (TCCS.pre (Act.name .a) (TCCS.const .M1)))
          (TCCS.pre (Act.name .b) (TCCS.const .M1))) ∧
    TDelay DeepWiki.ReactiveSystems.defn96 (TCCS.const .M2) 4
        (TCCS.choice (TCCS.eps 1 (TCCS.pre (Act.name .a) (TCCS.const .M2)))
          (TCCS.pre (Act.name .b) (TCCS.const .M2))) ∧
    (¬ ∃ Q, TDelay DeepWiki.ReactiveSystems.defn96 (TCCS.const .M3) 4 Q) ∧
    (¬ ∃ Q, TDelay DeepWiki.ReactiveSystems.defn96 (TCCS.const .M4) 4 Q) :=
  DeepWiki.ReactiveSystems.tccsAgents_delay4_characterization

/-- **Exercise 9.1** (§9.3, p.166). The timed light-switch specification
`Light ≝ ε(1.4).τ.press.Off + press.Bright` (with `Off ≝ press.Light`,
`Bright ≝ press.Off`) is guarded. The library's `lightDefn_isGuarded`. -/
theorem ex_9_1 : IsGuardedDefn DeepWiki.ReactiveSystems.lightDefn :=
  DeepWiki.ReactiveSystems.lightDefn_isGuarded

/-- **Exercise 9.2** (§9.3, p.168). From the `Light` state a delay `d ≤ 1.4` counts
the delay-prefix down: `Light —d→ ε(1.4−d).τ.press.Off + press.Bright`. The library's
`lightDefn_light_delayReduces`. -/
theorem ex_9_2 {d : ℝ≥0} (h : d ≤ 1.4) :
    (tccsTLTS DeepWiki.ReactiveSystems.lightDefn).delay (.const .Light) d
      (.choice (.eps (1.4 - d) (.pre Act.tau (.pre (.name .press) (.const .Off))))
        (.pre (.name .press) (.const .Bright))) :=
  DeepWiki.ReactiveSystems.lightDefn_light_delayReduces h

/-- **Exercise 9.3**, determinacy of delay (§9.3, p.168). For constant-free TCCS
terms, a delay leads to a unique state *up to* the identification `ε(0).P = P`: if
`P —d→ P'` and `P —d→ P''` then `P'` and `P''` are `ε(0)`-congruent. (Literal
equality fails — `ε(1).a.0` delays `1` to both `ε(0).a.0` and `a.0` — which is
exactly the reason the book does not distinguish `P` from `ε(0).P`.) The library's
`tDelay_determinacy_epsCong`. -/
theorem ex_9_3_determinacy {Name K : Type*} {defn : K → TCCS Name K} {P : TCCS Name K}
    (hcf : IsConstantFree P) {d : ℝ≥0} {P' P'' : TCCS Name K}
    (h₁ : TDelay defn P d P') (h₂ : TDelay defn P d P'') : EpsCong P' P'' :=
  tDelay_determinacy_epsCong hcf h₁ h₂

/-- **Exercise 9.3**, persistency of action (§9.3, p.168). For constant-free TCCS
terms, a time delay never disables a visible action: if `P` can perform `a` and
`P —d→ Q`, then `Q` can still perform `a`. The library's
`tAct_persistent_through_delay`. -/
theorem ex_9_3_persistency {Name K : Type*} {defn : K → TCCS Name K} {P : TCCS Name K}
    (hcf : IsConstantFree P) {a : Act Name} {Q : TCCS Name K} {d : ℝ≥0}
    (ha : ∃ P', TAct defn P a P') (hd : TDelay defn P d Q) : ∃ Q', TAct defn Q a Q' :=
  tAct_persistent_through_delay hcf ha hd

/-- **Exercise 9.4** (§9.3, p.168). An alarm timer modelled as a TCCS agent
(`alarmDefn`): `Idle` is set to a period by `set5`/`set10`/`set30`, each `Armed_d`
counts `d` down and signals the time-out by `t̄o`, and a new `set` re-arms it at any
moment. Representative behaviour for the 5-period — it arms (`Idle —set5→ Armed5`),
times out after `5` (`Armed5 —5→ · —t̄o→ Idle`), and can be reset mid-wait
(`Armed5 —d→ · —set10→ Armed10` for `d ≤ 5`). -/
theorem ex_9_4 :
    (tccsTLTS alarmDefn).act (.const .Idle) (Act.name .set5) (.const .Armed5) ∧
    (tccsTLTS alarmDefn).delay (.const .Armed5) 5
        (.choice (.eps 0 (.pre (.coname .to) (.const .Idle))) alarmSet) ∧
    (tccsTLTS alarmDefn).act
        (.choice (.eps 0 (.pre (.coname .to) (.const .Idle))) alarmSet)
        (Act.coname .to) (.const .Idle) ∧
    (∀ d : ℝ≥0, d ≤ 5 → ∃ Y, (tccsTLTS alarmDefn).delay (.const .Armed5) d Y ∧
        (tccsTLTS alarmDefn).act Y (Act.name .set10) (.const .Armed10)) :=
  ⟨alarm_idle_arms, alarm5_countdown, alarm5_timeOut, fun _ h => alarm5_reset h⟩

/-! ## §9.4 Parallel composition (maximal progress) -/

/-- **§9.4** (p.169): the action SOS of timed CCS with parallel composition — interleaving (`com1`,
`com2`) and synchronisation (`com3`). The library's `PAct`. -/
abbrev def_9_4_act := @DeepWiki.ReactiveSystems.PAct

/-- **§9.4** (p.170): the delay relation respecting **maximal progress** — the stratified reading of the
book's `NoSync(P,Q,d)` parallel side condition (raw componentwise delay, filtered so no intermediate
state reachable by delaying `< d` is `τ`-urgent). The library's `PDelay`. -/
abbrev def_9_4_delay := @DeepWiki.ReactiveSystems.PDelay

/-- **§9.4 maximal-progress assumption** (p.170): if `P —τ→` then `P` cannot delay by any positive
amount. The library's `pdelay_maximalProgress`. -/
alias prop_9_4_maximalProgress := DeepWiki.ReactiveSystems.pdelay_maximalProgress

/-- **Exercise 9.5** (p.170), second expression: `((press̄.P) | (ε(t).τ.press.Q + press.R)) \ press`
synchronises immediately, so it cannot delay by any positive amount. -/
alias ex_9_5_immediate := DeepWiki.ReactiveSystems.parRestrict_immediateSync_noDelay

/-- **Exercise 9.5** (p.170), first expression: `((ε(0.3).press̄.P) | (ε(1.1).τ.press.Q + press.R)) \
press` cannot delay by `0.4` — at the intermediate time `0.3` the guard expires and a synchronisation
becomes available (here in general form, `t₁ < t₂`, `t₁ ≤ t₃`). -/
alias ex_9_5_guardExpiry := DeepWiki.ReactiveSystems.parRestrict_guardExpiry_noDelay

/-- **Exercise 9.5** (p.170), closing question: `ε(t).τ.0 + a.0` cannot delay past `t` (so, with the
patience of the `a`-prefix giving every `d ≤ t`, it delays exactly up to `t`). -/
alias ex_9_5_eps_bound := DeepWiki.ReactiveSystems.epsChoice_noDelay_gt

end DeepWiki.Rs
