import DeepWiki.ReactiveSystems.LabelledTransitionSystems
import DeepWiki.ReactiveSystems.Ccs
import DeepWiki.ReactiveSystems.CcsProcessGraph
import DeepWiki.ReactiveSystems.CcsBuffer
import DeepWiki.ReactiveSystems.Chapter2Examples
import Sources.Doi_10_1017_CBO9780511814105.Source

/-! # Reactive Systems catalog — Chapter 2: The language CCS
Each numbered item of the book's Chapter 2 is one declaration named by its
book number: an `abbrev` aliasing the library declaration for definitions, a
`theorem` (the book-faithful statement, discharged by the `DeepWiki` library)
for theorems/propositions. The book numbering lives here in the catalog, never
in the library; the citation (section, page) is in each docstring, the source's
DOI in `Sources.Doi_10_1017_CBO9780511814105.Source`. -/

namespace DeepWiki.Rs

open DeepWiki.ReactiveSystems

/-! ## §2.2.1 The model of labelled transition systems -/

/-- **Definition 2.1** (§2.2.1, p.19). A labelled transition system is a triple
`(Proc, Act, {→ᵃ | a ∈ Act})` of states, labels, and a transition relation per
label. The library's `LTS`. -/
abbrev def_2_1 := @LTS

/-- **§2.2.1** (p.17), the refusal predicate `p ↛ᵃ`: `p` admits no `a`-move.
The library's `LTS.Refuses`. -/
abbrev refuses := @LTS.Refuses

/-- **§2.2.1, Remark 2.1** (p.18), reachable states: `q` is reachable from `p`
by finitely many transitions. The library's `LTS.Reachable`. -/
abbrev reachable := @LTS.Reachable

/-- **Definition 2.1** (§2.2.1, p.19), finiteness: an LTS is finite when its
state and label sets are both finite. The library's `LTS.IsFinite`. -/
abbrev def_2_1_finite := @LTS.IsFinite

/-! ## §2.2.2 The formal syntax and semantics of CCS -/

/-- **§2.2.2** (p.20). CCS actions `Act = L ∪ {τ}` with labels `L = A ∪ Ā`
(names and complementary co-names). The library's `Act`. -/
abbrev act := @Act

/-- **§2.2.2** (p.20), complementation `·̄` on labels (involutive, `τ̄ = τ`).
The library's `Act.co`. -/
abbrev complement := @Act.co

/-- **Definition 2.3** (§2.2.2, p.22). The collection of CCS expressions
`P ::= K ∣ a.P ∣ Σᵢ Pᵢ ∣ P∣Q ∣ P[f] ∣ P∖L`. The library's `CCS` (with the
indexed sum taken via `nil` and binary `choice`). -/
abbrev def_2_3 := @CCS

/-- **Definition 2.3** (§2.2.2, p.22), the relabelling constraint: `f` fixes `τ`
and commutes with complementation, `f(ᾱ) = f(α)‾`. The library's
`IsRelabelling`. -/
abbrev def_2_3_relabelling := @IsRelabelling

/-- **Table 2.2** (SOS rules for CCS, §2.2.2, p.24). The transition relation
`P —α→ P'` inductively generated by ACT, SUM, COM1–3, RES, REL, CON under a
definition environment for the process constants. The library's `Step`. -/
abbrev tbl_2_2 := @Step

/-- **§2.2.2** (p.24). The SOS rules generate an LTS whose states are CCS
expressions and whose labels are actions. The library's `ccsLTS`. -/
abbrev ccsLTS := @DeepWiki.ReactiveSystems.ccsLTS

/-- Verification of the synchronisation rule COM3: `(a.0 ∣ ā.0) —τ→ (0 ∣ 0)`. -/
example : (ccsLTS (Name := Bool) (K := Empty) (fun e => e.elim)) ⊢
    ⟪ (.name true) ▸ 𝟬 ∥ (.coname true) ▸ 𝟬 ⟫ ⟶[Act.tau] ⟪ 𝟬 ∥ 𝟬 ⟫ :=
  Step.com3 (by rintro ⟨⟩) (Step.act _ _) (Step.act _ _)

/-! ## Solved exercises -/

/-- Channel names `a, b` for Exercise 2.8. -/
inductive Ex2Name | a | b
  deriving DecidableEq

/-- Process constants `A, B` for Exercise 2.8 (`A ≝ b.a.B`). -/
inductive Ex28K | A | B
  deriving DecidableEq

/-- Exercise 2.8 definition environment: `A ≝ b.a.B` (and `B ≝ 0`). -/
def ex28defn : Ex28K → CCS Ex2Name Ex28K
  | .A => ⟪ (.name .b) ▸ (.name .a) ▸ ‹.const .B› ⟫
  | .B => ⟪ 𝟬 ⟫

/-- **Exercise 2.8** (§2.2.2, p.26). With `A ≝ b.a.B`, the SOS rules derive the
synchronisation `(A ∣ b̄.0)∖{b} —τ→ (a.B ∣ 0)∖{b}` (COM3+RES), its relabelling
`(A ∣ b̄.0)[f] —f(b)→ (a.B ∣ b̄.0)[f]` (REL), and the plain left move
`(A ∣ b̄.0) —b→ (a.B ∣ b̄.0)` (COM1+CON+ACT). -/
theorem ex_2_8 :
    ((ccsLTS ex28defn) ⊢
        ⟪ (‹.const .A› ∥ (.coname .b) ▸ 𝟬) ∖ {Act.name Ex2Name.b} ⟫ ⟶[Act.tau]
        ⟪ ((.name .a) ▸ ‹.const .B› ∥ 𝟬) ∖ {Act.name Ex2Name.b} ⟫) ∧
    (∀ f : Act Ex2Name → Act Ex2Name, (ccsLTS ex28defn) ⊢
        ⟪ (‹.const .A› ∥ (.coname .b) ▸ 𝟬)⟦f⟧ ⟫ ⟶[f (.name .b)]
        ⟪ ((.name .a) ▸ ‹.const .B› ∥ (.coname .b) ▸ 𝟬)⟦f⟧ ⟫) ∧
    ((ccsLTS ex28defn) ⊢
        ⟪ ‹.const .A› ∥ (.coname .b) ▸ 𝟬 ⟫ ⟶[.name .b]
        ⟪ (.name .a) ▸ ‹.const .B› ∥ (.coname .b) ▸ 𝟬 ⟫) := by
  refine ⟨?_, fun f => Step.rel (Step.com1 (Step.con (Step.act _ _))),
    Step.com1 (Step.con (Step.act _ _))⟩
  refine Step.res ?_ ?_ (Step.com3 (by rintro ⟨⟩) (Step.con (Step.act _ _)) (Step.act _ _))
  · rintro ⟨⟩
  · rintro ⟨⟩

/-! ## Solved exercises -/

/-- **Exercise 2.3** (§2.2, p.21). The CCS process describing a finite process
graph `(Q, A, δ, q₀)` (with `δ : Q → Act A → List Q`): each state becomes a
process constant whose body is the choice-sum of `a.(const q')` over the
graph's transitions. The library's `graphToCCS`. -/
abbrev ex_2_3_encoding := @graphToCCS

/-- **Exercise 2.3** (§2.2, p.21), faithfulness: the encoding `const q` has
exactly the transitions of the graph — `const q —a→ R` iff `R = const q'` for
some successor `q' ∈ δ q a`. The library's `graphToCCS_step_iff`. -/
theorem ex_2_3 {Q A : Type*} (delta : Q → DeepWiki.ReactiveSystems.Act A → List Q)
    (allActs : List (DeepWiki.ReactiveSystems.Act A)) (q : Q)
    (a : DeepWiki.ReactiveSystems.Act A) (R : CCS A Q) (ha : a ∈ allActs) :
    ((ccsLTS (graphToCCS delta allActs)) ⊢ CCS.const q ⟶[a] R) ↔
      ∃ q', q' ∈ delta q a ∧ R = CCS.const q' :=
  graphToCCS_step_iff delta allActs q a R ha

/-- **Exercise 2.12** (§2.2, p.34). The one-place buffer `Cell = in(x).Cell(x)`,
`Cell(x) = out(x).Cell`, with value passing over a finite data domain encoded as
action families `inᵥ`/`outᵥ`. The library's `cellDefn`. -/
noncomputable abbrev ex_2_12_cell := @DeepWiki.ReactiveSystems.cellDefn

/-- **Exercise 2.12** (§2.2, p.34). A two-place bag built from `Cell`: two cells
in parallel. The library's `twoBag`. -/
noncomputable abbrev ex_2_12_bag := @DeepWiki.ReactiveSystems.twoBag

/-- **Exercise 2.12** (§2.2, p.34). A two-place FIFO queue built from `Cell` by
the linking combinator: the first cell's output is renamed (relabelling) to an
internal link feeding the second cell's input, then restricted. The library's
`fifoQueue`. -/
noncomputable abbrev ex_2_12_queue := @DeepWiki.ReactiveSystems.fifoQueue

/-- **Exercise 2.12**, faithfulness: the empty cell's only moves are inputs —
`Cell —a→ R` iff `a = inᵥ` and `R = Cell(v)` for some value `v`. -/
theorem ex_2_12_cell_behaviour {D : Type*} [Fintype D]
    (a : DeepWiki.ReactiveSystems.Act (DeepWiki.ReactiveSystems.CellChan D))
    (R : CCS (DeepWiki.ReactiveSystems.CellChan D) (DeepWiki.ReactiveSystems.CellK D)) :
    Step DeepWiki.ReactiveSystems.cellDefn (CCS.const DeepWiki.ReactiveSystems.CellK.cell) a R ↔
      ∃ v, a = DeepWiki.ReactiveSystems.Act.name (DeepWiki.ReactiveSystems.CellChan.inp v) ∧
        R = CCS.const (DeepWiki.ReactiveSystems.CellK.cellVal v) :=
  DeepWiki.ReactiveSystems.cell_input_iff a R

/-- **Exercise 2.5** (§2.2.1, p.21). In the Figure 2.6 LTS, every state is
reachable from `p₂` (the reachable set is the full `{p, p₁, p₂}`). The library's
`fig26_reachable_from_p2`; the contrast `p₂` unreachable from `p` is
`fig26_p_not_reach_p2`. -/
theorem ex_2_5 (q : DeepWiki.ReactiveSystems.Fig26) :
    (DeepWiki.ReactiveSystems.fig26).Reachable .p2 q :=
  DeepWiki.ReactiveSystems.fig26_reachable_from_p2 q

/-- **Exercise 2.7** (§2.1/§2.2, p.16/p.20). The SOS rules derive the LTS of
`SmUni = (CM ∣ CS) ∖ {coin, coffee}`: `SmUni —pub→ (CM∣CS₁)∖L —τ→ (CM₁∣CS₂)∖L
—τ→ (CM∣CS)∖L`. The library's `smUni_lts`. -/
theorem ex_2_7 :
    ((ccsLTS DeepWiki.ReactiveSystems.smuniDefn) ⊢ DeepWiki.ReactiveSystems.smUni
        ⟶[Act.name DeepWiki.ReactiveSystems.SmuniName.pub]
      (CCS.restrict (CCS.par (CCS.const .CM) (CCS.const .CS1))
        DeepWiki.ReactiveSystems.smuniRestrict)) ∧
    ((ccsLTS DeepWiki.ReactiveSystems.smuniDefn) ⊢
        (CCS.restrict (CCS.par (CCS.const .CM) (CCS.const .CS1))
          DeepWiki.ReactiveSystems.smuniRestrict) ⟶[Act.tau]
      (CCS.restrict (CCS.par (CCS.const .CM1) (CCS.const .CS2))
        DeepWiki.ReactiveSystems.smuniRestrict)) ∧
    ((ccsLTS DeepWiki.ReactiveSystems.smuniDefn) ⊢
        (CCS.restrict (CCS.par (CCS.const .CM1) (CCS.const .CS2))
          DeepWiki.ReactiveSystems.smuniRestrict) ⟶[Act.tau]
      (CCS.restrict (CCS.par (CCS.const .CM) (CCS.const .CS))
        DeepWiki.ReactiveSystems.smuniRestrict)) :=
  DeepWiki.ReactiveSystems.smUni_lts

end DeepWiki.Rs
