import DeepWiki.ReactiveSystems.TimedTransitionSystems
import DeepWiki.ReactiveSystems.TimedCCS
import Sources.Doi_10_1017_CBO9780511814105.Source

/-! # Reactive Systems catalog — Chapter 9: CCS with time delays
Book-numbered restatements for the timed transition-system model of §9.2 and the
syntax and SOS rules of timed CCS (§9.3), discharged by the
`DeepWiki.ReactiveSystems` library. (§9.4 parallel composition / §9.5 discussion
are noted in the library.) -/

namespace DeepWiki.Rs

open DeepWiki.ReactiveSystems
open scoped NNReal

/-! ## §9.2 Timed labelled transition systems -/

/-- **Definition 9.1** (§9.2, p.164). A timed labelled transition system: an LTS
with label set `Lab = Act ∪ ℝ≥0` (ordinary actions and time delays). The
library's `TLTS` (over the combined label type `Act ⊕ ℝ≥0`). -/
abbrev def_9_1 := @TLTS

/-- **(9.2)** (§9.2, p.164), time determinism: a delay transition leads to a
unique state. The library's `TLTS.TimeDeterministic`. -/
abbrev eq_9_2 := @TLTS.TimeDeterministic

/-- **(9.3)** (§9.2, p.164), zero delay: every state reaches itself with a zero
delay. The library's `TLTS.ZeroDelay`. -/
abbrev eq_9_3 := @TLTS.ZeroDelay

/-- **(9.4)** (§9.2, p.165), time additivity / continuity: a delay of `d₁ + d₂`
is exactly a delay `d₁` followed by a delay `d₂`. The library's
`TLTS.TimeAdditive`. -/
abbrev eq_9_4 := @TLTS.TimeAdditive

/-! ## §9.3 Syntax and SOS rules of timed CCS (TCCS) -/

/-- **§9.3** (p.166). Timed CCS expressions: CCS extended with the delay-prefix
`ε(d).P` (`eps d P`). The library's `TCCS`. -/
abbrev timedCCS := @TCCS

/-- **§9.3** (Table 9.1, p.167), action SOS for TCCS: the CCS action rules plus
`ε(0).P —α→ P'`. The library's `TAct`. -/
abbrev tccsAct := @TAct

/-- **§9.3** (Table 9.1, p.167), delay SOS for TCCS: delay-prefix countdown and
consume, patient action-prefixes (`α ≠ τ`), componentwise choice/restrict/relabel
delays. The library's `TDelay`. -/
abbrev tccsDelay := @TDelay

/-- **Definition 9.1 / §9.3** (p.166). The timed LTS generated by a TCCS
definition environment. The library's `tccsTLTS`. -/
abbrev tccsTLTS := @DeepWiki.ReactiveSystems.tccsTLTS

/-- **§9.3** (eq. below 9.5, p.167). A delay-prefixed guard `ε(t).P` lets any
`d ≤ t` elapse, decrementing the prefix to `ε(t−d).P` — delays do not resolve
choices (they are deterministic). -/
theorem tccs_eps_delay {Name K : Type*} (defn : K → TCCS Name K) (t d : ℝ≥0)
    (h : d ≤ t) (P : TCCS Name K) :
    (DeepWiki.ReactiveSystems.tccsTLTS defn).delay (.eps t P) d (.eps (t - d) P) :=
  DeepWiki.ReactiveSystems.light_delay defn t d h P

/-! ## §9.4 Parallel composition: the maximal-progress assumption -/

/-- **§9.4** (p.170). The *maximal-progress assumption*: the silent action `τ` is
urgent — a state able to perform `τ` cannot let positive time elapse. The
library's `TLTS.MaximalProgress`. (This is the side condition forcing
synchronisations in a parallel composition to happen without delay; the full
parallel SOS with its `NoSync` premise is noted in the library.) -/
abbrev maximalProgress := @TLTS.MaximalProgress

/-- **§9.4** (p.170). The TCCS `τ`-prefix witnesses maximal progress: `τ.P` can
perform `τ` yet cannot delay any positive amount of time. -/
theorem tccs_tau_urgent {Name K : Type*} (defn : K → TCCS Name K) (P : TCCS Name K)
    (d : ℝ≥0) (hd : 0 < d) :
    ¬ ∃ Q, (DeepWiki.ReactiveSystems.tccsTLTS defn).delay (.pre DeepWiki.ReactiveSystems.Act.tau P) d Q :=
  DeepWiki.ReactiveSystems.tccs_tau_maximalProgress defn P d hd

/-- **Definition 9.2** (§9.3, p.166). Guardedness of a TCCS expression: every
constant occurrence lies within an action or positive-delay prefix. The library's
`IsGuarded` (process-level: `IsGuardedDefn`). -/
abbrev def_9_2 := @DeepWiki.ReactiveSystems.IsGuarded

/-- **Definition 9.2** (§9.3, p.166). A guarded definition environment. The
library's `IsGuardedDefn`. -/
abbrev def_9_2_defn := @DeepWiki.ReactiveSystems.IsGuardedDefn

end DeepWiki.Rs
