import DeepWiki.ReactiveSystems.LabelledTransitionSystems
import DeepWiki.ReactiveSystems.Ccs
import Sources.Doi_10_1017_CBO9780511814105.Source

/-! # Reactive Systems catalog — Chapter 2: The language CCS
Each numbered item of the book's Chapter 2 is one declaration named by its
book number: an `abbrev` aliasing the library declaration for definitions, a
`theorem` (the book-faithful statement, discharged by the `DeepWiki` library)
for theorems/propositions. The book numbering lives here in the catalog, never
in the library; the citation (section, page) is in each docstring, the source's
DOI in `Sources.Doi_10_1017_CBO9780511814105.Source`. -/

namespace DeepWiki.Rs

open DeepWiki.ReactiveSystems

/-! ## §2.2.1 The model of labelled transition systems -/

/-- **Definition 2.1** (§2.2.1, p.19). A labelled transition system is a triple
`(Proc, Act, {→ᵃ | a ∈ Act})` of states, labels, and a transition relation per
label. The library's `LTS`. -/
abbrev def_2_1 := @LTS

/-- **§2.2.1** (p.17), the refusal predicate `p ↛ᵃ`: `p` admits no `a`-move.
The library's `LTS.Refuses`. -/
abbrev refuses := @LTS.Refuses

/-- **§2.2.1, Remark 2.1** (p.18), reachable states: `q` is reachable from `p`
by finitely many transitions. The library's `LTS.Reachable`. -/
abbrev reachable := @LTS.Reachable

/-- **Definition 2.1** (§2.2.1, p.19), finiteness: an LTS is finite when its
state and label sets are both finite. The library's `LTS.IsFinite`. -/
abbrev def_2_1_finite := @LTS.IsFinite

/-! ## §2.2.2 The formal syntax and semantics of CCS -/

/-- **§2.2.2** (p.20). CCS actions `Act = L ∪ {τ}` with labels `L = A ∪ Ā`
(names and complementary co-names). The library's `Act`. -/
abbrev act := @Act

/-- **§2.2.2** (p.20), complementation `·̄` on labels (involutive, `τ̄ = τ`).
The library's `Act.co`. -/
abbrev complement := @Act.co

/-- **Definition 2.3** (§2.2.2, p.22). The collection of CCS expressions
`P ::= K ∣ a.P ∣ Σᵢ Pᵢ ∣ P∣Q ∣ P[f] ∣ P∖L`. The library's `CCS` (with the
indexed sum taken via `nil` and binary `choice`). -/
abbrev def_2_3 := @CCS

/-- **Definition 2.3** (§2.2.2, p.22), the relabelling constraint: `f` fixes `τ`
and commutes with complementation, `f(ᾱ) = f(α)‾`. The library's
`IsRelabelling`. -/
abbrev def_2_3_relabelling := @IsRelabelling

/-- **Table 2.2** (SOS rules for CCS, §2.2.2, p.24). The transition relation
`P —α→ P'` inductively generated by ACT, SUM, COM1–3, RES, REL, CON under a
definition environment for the process constants. The library's `Step`. -/
abbrev tbl_2_2 := @Step

/-- **§2.2.2** (p.24). The SOS rules generate an LTS whose states are CCS
expressions and whose labels are actions. The library's `ccsLTS`. -/
abbrev ccsLTS := @DeepWiki.ReactiveSystems.ccsLTS

/-- Verification of the synchronisation rule COM3: `(a.0 ∣ ā.0) —τ→ (0 ∣ 0)`. -/
example : Step (Name := Bool) (K := Empty) (fun e => e.elim)
    ((CCS.pre (.name true) .nil).par (CCS.pre (.coname true) .nil))
    Act.tau (CCS.nil.par CCS.nil) :=
  Step.com3 (by rintro ⟨⟩) (Step.act _ _) (Step.act _ _)

end DeepWiki.Rs
