import DeepWiki.Refine.Dependent
import Mathlib.Logic.Equiv.Defs

/-! # Proof transfer in dependent type theory

Proof transfer synthesizes a target type former and a witness relating it to a given source type
former. Structured natural-number interfaces and functional pullbacks illustrate useful and
degenerate solutions respectively. -/

namespace DeepWiki.Refine

universe u v r p q s

/-- Raw terms in the universe/application/lambda/dependent-product grammar of a predicative
dependent lambda calculus. -/
inductive CalculusTerm where
  /-- A universe in the predicative hierarchy. -/
  | universe (level : Nat)
  /-- A de Bruijn variable. -/
  | var (index : Nat)
  /-- Function application. -/
  | app (function argument : CalculusTerm)
  /-- Lambda abstraction with an explicit domain type. -/
  | lam (domain body : CalculusTerm)
  /-- A dependent function type. -/
  | pi (domain codomain : CalculusTerm)
  deriving DecidableEq, Repr

/-- A solution to a proof-transfer problem consists of a synthesized target type former and a
uniform relational witness from related inputs to related outputs. -/
structure TypeFormerTransferSolution {T₁ : Type u} {T₂ : Type v}
    (inputRel : T₁ → T₂ → Sort r)
    (outputRel : Sort p → Sort q → Sort s)
    (source : T₁ → Sort p) where
  /-- The synthesized target type former. -/
  target : T₂ → Sort q
  /-- Related inputs are sent to outputs related by `outputRel`. -/
  witness : ∀ t₁ t₂, inputRel t₁ t₂ → outputRel (source t₁) (target t₂)

/-- The right-to-left arrow relation used when a target proof should solve a source goal. -/
def BackwardArrow (source : Sort p) (target : Sort q) := target → source

/-- Apply a right-to-left transfer witness to turn a target proof into a source proof. -/
def TypeFormerTransferSolution.transferProof {T₁ : Type u} {T₂ : Type v}
    {inputRel : T₁ → T₂ → Sort r} {source : T₁ → Sort p}
    (solution : TypeFormerTransferSolution inputRel BackwardArrow source)
    {t₁ : T₁} {t₂ : T₂} (related : inputRel t₁ t₂)
    (proof : solution.target t₂) : source t₁ :=
  solution.witness t₁ t₂ related proof

/-- A natural-number interface consists only of a carrier, zero, and successor. -/
structure NatSignature where
  /-- The carrier representing natural numbers. -/
  Carrier : Type u
  /-- The representation of zero. -/
  zero : Carrier
  /-- The representation of successor. -/
  succ : Carrier → Carrier

/-- The induction principle generated by a natural-number interface. -/
def NatSignature.Induction (signature : NatSignature.{u}) : Prop :=
  ∀ P : signature.Carrier → Prop,
    P signature.zero →
    (∀ n, P n → P (signature.succ n)) →
    ∀ n, P n

/-- Reencode a natural-number interface through an arbitrary pair of carrier maps. -/
def NatSignature.reencode (signature : NatSignature.{v}) {Carrier : Type u}
    (up : signature.Carrier → Carrier) (down : Carrier → signature.Carrier) : NatSignature.{u} where
  Carrier := Carrier
  zero := up signature.zero
  succ := fun n => up (signature.succ (down n))

/-- Induction for a reencoded interface exposes the inserted down-up round trip at successor. -/
theorem NatSignature.reencode_induction (signature : NatSignature.{v}) {Carrier : Type u}
    (up : signature.Carrier → Carrier) (down : Carrier → signature.Carrier) :
    (signature.reencode up down).Induction ↔
      ∀ P : Carrier → Prop,
        P (up signature.zero) →
        (∀ n, P n → P (up (signature.succ (down n)))) →
        ∀ n, P n :=
  Iff.rfl

/-- An equivalence of natural-number interfaces preserves zero and successor. -/
structure NatSignatureEquiv (left : NatSignature.{u}) (right : NatSignature.{v}) where
  /-- The equivalence between the carriers. -/
  carrier : left.Carrier ≃ right.Carrier
  /-- The carrier equivalence preserves zero. -/
  map_zero : carrier left.zero = right.zero
  /-- The carrier equivalence preserves successor. -/
  map_succ : ∀ n, carrier (left.succ n) = right.succ (carrier n)

/-- Reverse an equivalence of natural-number interfaces. -/
def NatSignatureEquiv.symm {left : NatSignature.{u}} {right : NatSignature.{v}}
    (equiv : NatSignatureEquiv left right) : NatSignatureEquiv right left where
  carrier := equiv.carrier.symm
  map_zero := by
    apply equiv.carrier.injective
    simpa using equiv.map_zero.symm
  map_succ n := by
    apply equiv.carrier.injective
    simpa using (equiv.map_succ (equiv.carrier.symm n)).symm

/-- An interface equivalence transports its induction principle from left to right. -/
theorem NatSignatureEquiv.induction {left : NatSignature.{u}} {right : NatSignature.{v}}
    (equiv : NatSignatureEquiv left right) : left.Induction → right.Induction := by
  intro induction P hzero hsucc n
  let Q : left.Carrier → Prop := fun m => P (equiv.carrier m)
  have qzero : Q left.zero := by
    change P (equiv.carrier left.zero)
    rw [equiv.map_zero]
    exact hzero
  have qsucc : ∀ m, Q m → Q (left.succ m) := by
    intro m hm
    change P (equiv.carrier (left.succ m))
    rw [equiv.map_succ]
    exact hsucc (equiv.carrier m) hm
  have result := induction Q qzero qsucc (equiv.carrier.symm n)
  change P (equiv.carrier (equiv.carrier.symm n)) at result
  simpa using result

/-- Equivalent natural-number interfaces have logically equivalent induction principles. -/
theorem NatSignatureEquiv.induction_iff {left : NatSignature.{u}} {right : NatSignature.{v}}
    (equiv : NatSignatureEquiv left right) : left.Induction ↔ right.Induction :=
  ⟨equiv.induction, equiv.symm.induction⟩

/-- Interface equivalence gives a proof-transfer solution for the induction type former. -/
def natInductionTransfer :
    TypeFormerTransferSolution
      (fun left : NatSignature.{u} => fun right : NatSignature.{v} =>
        NatSignatureEquiv left right)
      BackwardArrow NatSignature.Induction where
  target := NatSignature.Induction
  witness := fun _ _ equiv => equiv.induction_iff.mpr

/-- Any function `φ : T₂ → T₁` induces the graph relation `t₁ = φ t₂`. -/
def PullbackRel {T₁ : Type u} {T₂ : Type v} (φ : T₂ → T₁) : T₁ → T₂ → Prop :=
  fun t₁ t₂ => t₁ = φ t₂

/-- Pulling the source type former back along `φ` is the canonical but often uninformative solution
for the graph relation of `φ`. -/
def functionalPullbackSolution {T₁ : Type u} {T₂ : Type v} (φ : T₂ → T₁)
    (source : T₁ → Sort p) :
    TypeFormerTransferSolution (PullbackRel φ) BackwardArrow source where
  target := fun t₂ => source (φ t₂)
  witness := fun _ _ related => by
    cases related
    exact id

/-- The functional pullback synthesizes definitionally the composite `source ∘ φ`. -/
theorem functionalPullbackSolution_target {T₁ : Type u} {T₂ : Type v} (φ : T₂ → T₁)
    (source : T₁ → Sort p) (t₂ : T₂) :
    (functionalPullbackSolution φ source).target t₂ = source (φ t₂) :=
  rfl

/-- The functional pullback proof performs no mathematical work after graph equality is used. -/
theorem functionalPullbackSolution_transfer {T₁ : Type u} {T₂ : Type v} (φ : T₂ → T₁)
    (source : T₁ → Sort p) {t₁ : T₁} {t₂ : T₂} (related : PullbackRel φ t₁ t₂)
    (proof : source (φ t₂)) :
    (functionalPullbackSolution φ source).transferProof related proof =
      related ▸ proof := by
  cases related
  rfl

/-- A zero/successor pair on the fixed carrier `Nat`. -/
abbrev NatOperationPair := Nat × (Nat → Nat)

/-- The induction-shaped type former associated with a fixed-carrier zero/successor pair. -/
def NatOperationPair.Induction (operations : NatOperationPair) : Prop :=
  ∀ P : Nat → Prop,
    P operations.1 →
    (∀ n, P n → P (operations.2 n)) →
    ∀ n, P n

/-- Conjugate the structural entries of a zero/successor pair by arbitrary up/down maps. -/
def NatOperationPair.conjugate (up down : Nat → Nat) (operations : NatOperationPair) :
    NatOperationPair :=
  (up operations.1, fun n => up (operations.2 (down n)))

/-- The deliberately weak induction candidate obtained by changing only structural arguments. -/
def NatOperationPair.ConjugatedInduction
    (up down : Nat → Nat) (operations : NatOperationPair) : Prop :=
  ∀ P : Nat → Prop,
    P (up operations.1) →
    (∀ n, P n → P (up (operations.2 (down n)))) →
    ∀ n, P n

/-- Structural conjugation is exactly the functional pullback of the induction-shaped type former. -/
theorem NatOperationPair.conjugatedInduction_eq_pullback
    (up down : Nat → Nat) (operations : NatOperationPair) :
    operations.ConjugatedInduction up down =
      NatOperationPair.Induction (operations.conjugate up down) :=
  rfl

/-- The weak structural candidate is synthesized by the generic functional pullback solution. -/
theorem NatOperationPair.functionalPullback_target
    (up down : Nat → Nat) (operations : NatOperationPair) :
    (functionalPullbackSolution (NatOperationPair.conjugate up down)
      NatOperationPair.Induction).target operations =
        operations.ConjugatedInduction up down :=
  rfl

example {left : NatSignature.{u}} {right : NatSignature.{v}}
    (equiv : NatSignatureEquiv left right) (induction : right.Induction) : left.Induction :=
  natInductionTransfer.transferProof equiv induction

example {left : NatSignature.{u}} {right : NatSignature.{v}}
    (equiv : NatSignatureEquiv left right) : left.Induction → right.Induction :=
  equiv.induction

example {left : NatSignature.{u}} {right : NatSignature.{v}}
    (equiv : NatSignatureEquiv left right) : left.Induction ↔ right.Induction :=
  equiv.induction_iff

example (signature : NatSignature.{v}) {Carrier : Type u}
    (up : signature.Carrier → Carrier) (down : Carrier → signature.Carrier) :
    (signature.reencode up down).Induction ↔
      ∀ P : Carrier → Prop,
        P (up signature.zero) →
        (∀ n, P n → P (up (signature.succ (down n)))) →
        ∀ n, P n :=
  NatSignature.reencode_induction signature up down

example {T₁ : Type u} {T₂ : Type v} (φ : T₂ → T₁) (source : T₁ → Prop)
    {t₁ : T₁} {t₂ : T₂} (related : t₁ = φ t₂) (proof : source (φ t₂)) : source t₁ :=
  (functionalPullbackSolution φ source).transferProof related proof

example {T₁ : Type u} {T₂ : Type v} (φ : T₂ → T₁) (source : T₁ → Sort p) (t₂ : T₂) :
    (functionalPullbackSolution φ source).target t₂ = source (φ t₂) :=
  functionalPullbackSolution_target φ source t₂

example {T₁ : Type u} {T₂ : Type v} (φ : T₂ → T₁) (source : T₁ → Sort p)
    {t₁ : T₁} {t₂ : T₂} (related : PullbackRel φ t₁ t₂) (proof : source (φ t₂)) :
    (functionalPullbackSolution φ source).transferProof related proof = related ▸ proof :=
  functionalPullbackSolution_transfer φ source related proof

example (up down : Nat → Nat) (operations : NatOperationPair) :
    operations.ConjugatedInduction up down =
      NatOperationPair.Induction (operations.conjugate up down) :=
  NatOperationPair.conjugatedInduction_eq_pullback up down operations

example (up down : Nat → Nat) (operations : NatOperationPair) :
    (functionalPullbackSolution (NatOperationPair.conjugate up down)
      NatOperationPair.Induction).target operations =
        operations.ConjugatedInduction up down :=
  NatOperationPair.functionalPullback_target up down operations

end DeepWiki.Refine
