import DeepWiki.Refine.ParametricitySequents
import DeepWiki.Refine.UnivalentRelationStructure
import DeepWiki.Refine.UniverseRelationStructure
import DeepWiki.Refine.PiRelationStructure

/-! # Univalent parametricity sequents

Scoped binary parametricity sequents use fixed object-language realizers for the univalent
universe and dependent-product relation constructors. Their typing theorem remains an explicit
claim because the raw term language does not quote relation-record projections.
-/

namespace DeepWiki.Refine.DependentCalculus.UnivalentParametricitySequents

open RawParametricity ParametricitySequents

universe u v u' v'

/-- Object-language terms realizing the univalent universe and dependent-product witnesses. -/
structure SyntaxRealizers where
  /-- Realize the top universe relation witness at a universe level and ambient scope. -/
  universeRelation : (level scope : Nat) → Term scope
  /-- Realize the top dependent-product constructor on domain and codomain witnesses. -/
  dependentProduct : {n : Nat} → Term n → Term (n + 3) → Term n

/-- The scoped univalent-parametricity sequent generated by fixed syntax realizers. -/
inductive Sequent (realizers : SyntaxRealizers) :
    (context : ParametricityContext n) → Term n → Term n → Term n → Prop where
  /-- A universe relates to itself through the fixed top universe witness. -/
  | sort (context : ParametricityContext n) (level : Nat) :
      Sequent realizers context (.sort level) (.sort level)
        (realizers.universeRelation level n)
  /-- A well-formed context triple translates its original variable to its primed and witness variables. -/
  | var {context : ParametricityContext n} (contextWellFormed : context.WellFormed)
      {triple : VariableTriple n} (member : triple ∈ context) :
      Sequent realizers context (.var triple.original) (.var triple.primed)
        (.var triple.witness)
  /-- Application applies a function witness to the original, primed, and witness arguments. -/
  | app {context : ParametricityContext n}
      {function function' functionRelation argument argument' argumentRelation : Term n}
      (functionSequent : Sequent realizers context function function' functionRelation)
      (argumentSequent : Sequent realizers context argument argument' argumentRelation) :
      Sequent realizers context (.app function argument) (.app function' argument')
        (.app (.app (.app functionRelation argument) argument') argumentRelation)
  /-- Lambda translation first translates its domain and then extends the variable triples. -/
  | lam {context : ParametricityContext n}
      {domain primedDomain domainRelation : Term n}
      {body body' : Term (n + 1)} {bodyRelation : Term (n + 3)}
      (domainSequent : Sequent realizers context domain primedDomain domainRelation)
      (bodySequent : Sequent realizers context.extend
        (body.rename originalBinderRenaming) (body'.rename primedBinderRenaming)
        bodyRelation) :
      Sequent realizers context (.lam domain body) (.lam primedDomain body')
        (lambdaWitness domain primedDomain (relatedDomain domainRelation) bodyRelation)
  /-- Dependent products combine their translated domain and codomain with the fixed top constructor. -/
  | pi {context : ParametricityContext n}
      {domain primedDomain domainRelation : Term n}
      {codomain primedCodomain : Term (n + 1)} {codomainRelation : Term (n + 3)}
      (domainSequent : Sequent realizers context domain primedDomain domainRelation)
      (codomainSequent : Sequent realizers context.extend
        (codomain.rename originalBinderRenaming)
        (primedCodomain.rename primedBinderRenaming) codomainRelation) :
      Sequent realizers context (.pi domain codomain) (.pi primedDomain primedCodomain)
        (realizers.dependentProduct domainRelation codomainRelation)

/-- A typing context is admissible when every sequent-translated lookup has coherent triple types. -/
def Admissible (realizers : SyntaxRealizers) (typingContext : Context n)
    (context : ParametricityContext n) : Prop :=
  context.WellFormed ∧ WellFormed typingContext ∧
    ∀ {triple : VariableTriple n}, triple ∈ context →
      ∀ {primedType relationType : Term n},
        Sequent realizers context (typingContext.lookup triple.original)
          primedType relationType →
        typingContext.lookup triple.primed = primedType ∧
          typingContext.lookup triple.witness =
            .app (.app relationType (.var triple.original)) (.var triple.primed)

/-- The univalent abstraction theorem stated as a proposition with explicit univalence evidence. -/
def AbstractionClaim (realizers : SyntaxRealizers) : Prop :=
  IsUnivalentUniverse.{u} →
    ∀ {n : Nat} {typingContext : Context n} {context : ParametricityContext n}
      {term term' termRelation type type' typeRelation : Term n},
      Admissible realizers typingContext context →
      HasType typingContext term type →
      Sequent realizers context term term' termRelation →
      Sequent realizers context type type' typeRelation →
      AbstractionConclusion typingContext term' termRelation type' typeRelation term

/-- The top universe relation fiber is definitionally the type of top structured relations. -/
@[simp] theorem universeRelationTop_fiber (univalent : IsUnivalentUniverse.{u})
    (A B : Type u) :
    (universeStructuredRelationTop univalent).rel A B =
      StructuredRelation.{u, u, u} Annotation.equivalence A B :=
  rfl

/-- A top universe relation fiber is equivalent to a relation with univalent maps both ways. -/
def universeRelationTopFiberEquiv (univalent : IsUnivalentUniverse.{u})
    (A B : Type u) :
    (universeStructuredRelationTop univalent).rel A B ≃
      BidirectionallyUnivalentRelationData.{u, u, u} A B :=
  (bidirectionallyUnivalentEquivStructuredRelation A B).symm

/-- Every top universe relation fiber has the bidirectionally univalent sigma characterization. -/
theorem universeRelationTopFiber_characterization
    (univalent : IsUnivalentUniverse.{u}) (A B : Type u) :
    Nonempty
      ((universeStructuredRelationTop univalent).rel A B ≃
        (Σ R : A → B → Type u, IsUmap R × IsUmap (Converse R))) :=
  ⟨universeRelationTopFiberEquiv univalent A B⟩

/-- Top dependent-product relation data is constructed from top domain and fiber relations. -/
def univalentDependentProductRelation {A : Type u} {B : Type v}
    {C : A → Type u'} {D : B → Type v'}
    (domain : StructuredRelation Annotation.equivalence A B)
    (fibers : ∀ a b (_related : domain.rel a b),
      StructuredRelation Annotation.equivalence (C a) (D b)) :
    StructuredRelation Annotation.equivalence
      ((a : A) → C a) ((b : B) → D b) :=
  StructuredRelation.pi Annotation.equivalence domain fibers

/-- Fixed realizers make the scoped univalent-parametricity translation functional. -/
theorem Sequent.functional {realizers : SyntaxRealizers}
    {context : ParametricityContext n} (contextWellFormed : context.WellFormed)
    {term left right leftRelation rightRelation : Term n}
    (leftSequent : Sequent realizers context term left leftRelation)
    (rightSequent : Sequent realizers context term right rightRelation) :
    (left, leftRelation) = (right, rightRelation) := by
  induction leftSequent with
  | sort context level =>
      cases rightSequent
      rfl
  | @var _ context _ triple leftMember =>
      generalize sourceEqual : (Term.var triple.original) = source at rightSequent
      cases rightSequent with
      | sort => cases sourceEqual
      | @var _ _ _ rightTriple rightMember =>
          injection sourceEqual with _ originalEqual
          have tripleEqual :=
            contextWellFormed.eq_of_original_eq leftMember rightMember originalEqual
          cases tripleEqual
          rfl
      | app => cases sourceEqual
      | lam => cases sourceEqual
      | pi => cases sourceEqual
  | app functionSequent argumentSequent functionInduction argumentInduction =>
      cases rightSequent with
      | app rightFunction rightArgument =>
          have functionEqual := functionInduction contextWellFormed rightFunction
          have argumentEqual := argumentInduction contextWellFormed rightArgument
          cases functionEqual
          cases argumentEqual
          rfl
  | lam domainSequent bodySequent domainInduction bodyInduction =>
      cases rightSequent with
      | lam rightDomain rightBody =>
          have domainEqual := domainInduction contextWellFormed rightDomain
          have bodyEqual := bodyInduction contextWellFormed.extend rightBody
          have primedBodyEqual := Term.rename_injective primedBinderRenaming
            primedBinderRenaming_injective (congrArg Prod.fst bodyEqual)
          have bodyRelationEqual := congrArg Prod.snd bodyEqual
          cases domainEqual
          cases primedBodyEqual
          cases bodyRelationEqual
          rfl
  | pi domainSequent codomainSequent domainInduction codomainInduction =>
      cases rightSequent with
      | pi rightDomain rightCodomain =>
          have domainEqual := domainInduction contextWellFormed rightDomain
          have codomainEqual := codomainInduction contextWellFormed.extend rightCodomain
          have primedCodomainEqual := Term.rename_injective primedBinderRenaming
            primedBinderRenaming_injective (congrArg Prod.fst codomainEqual)
          have codomainRelationEqual := congrArg Prod.snd codomainEqual
          cases domainEqual
          cases primedCodomainEqual
          cases codomainRelationEqual
          rfl

example (realizers : SyntaxRealizers) (context : ParametricityContext n) (level : Nat) :
    Sequent realizers context (.sort level) (.sort level)
      (realizers.universeRelation level n) :=
  .sort context level

example {realizers : SyntaxRealizers} {context : ParametricityContext n}
    (contextWellFormed : context.WellFormed)
    {triple : VariableTriple n} (member : triple ∈ context) :
    Sequent realizers context (.var triple.original) (.var triple.primed)
      (.var triple.witness) :=
  .var contextWellFormed member

example {realizers : SyntaxRealizers} {context : ParametricityContext n}
    {function function' functionRelation argument argument' argumentRelation : Term n}
    (functionSequent : Sequent realizers context function function' functionRelation)
    (argumentSequent : Sequent realizers context argument argument' argumentRelation) :
    Sequent realizers context (.app function argument) (.app function' argument')
      (.app (.app (.app functionRelation argument) argument') argumentRelation) :=
  .app functionSequent argumentSequent

example {realizers : SyntaxRealizers} {context : ParametricityContext n}
    {domain primedDomain domainRelation : Term n}
    {body body' : Term (n + 1)} {bodyRelation : Term (n + 3)}
    (domainSequent : Sequent realizers context domain primedDomain domainRelation)
    (bodySequent : Sequent realizers context.extend
      (body.rename originalBinderRenaming) (body'.rename primedBinderRenaming)
      bodyRelation) :
    Sequent realizers context (.lam domain body) (.lam primedDomain body')
      (lambdaWitness domain primedDomain (relatedDomain domainRelation) bodyRelation) :=
  .lam domainSequent bodySequent

example {realizers : SyntaxRealizers} {context : ParametricityContext n}
    {domain primedDomain domainRelation : Term n}
    {codomain primedCodomain : Term (n + 1)} {codomainRelation : Term (n + 3)}
    (domainSequent : Sequent realizers context domain primedDomain domainRelation)
    (codomainSequent : Sequent realizers context.extend
      (codomain.rename originalBinderRenaming)
      (primedCodomain.rename primedBinderRenaming) codomainRelation) :
    Sequent realizers context (.pi domain codomain) (.pi primedDomain primedCodomain)
      (realizers.dependentProduct domainRelation codomainRelation) :=
  .pi domainSequent codomainSequent

example (realizers : SyntaxRealizers) : Prop :=
  AbstractionClaim.{u} realizers

example (univalent : IsUnivalentUniverse.{u}) (A B : Type u) :
    (universeStructuredRelationTop univalent).rel A B ≃
      (Σ R : A → B → Type u, IsUmap R × IsUmap (Converse R)) :=
  universeRelationTopFiberEquiv univalent A B

example {A : Type u} {B : Type v} {C : A → Type u'} {D : B → Type v'}
    (domain : StructuredRelation Annotation.equivalence A B)
    (fibers : ∀ a b (_related : domain.rel a b),
      StructuredRelation Annotation.equivalence (C a) (D b)) :
    StructuredRelation Annotation.equivalence
      ((a : A) → C a) ((b : B) → D b) :=
  univalentDependentProductRelation domain fibers

end DeepWiki.Refine.DependentCalculus.UnivalentParametricitySequents
