import DeepWiki.NetworkCalculus.ScalingFunction
import DeepWiki.NetworkCalculus.StabilityNetworkScalingTrajectory
import DeepWiki.NetworkCalculus.StabilityNetworkScalingCycle
import Sources.Doi_10_1145_1140277_1140310.Source

/-! # Fidler–Schmitt — network calculus with data scaling — catalog
Paper-side ("double reference") pointers to the `DeepWiki.NetworkCalculus` theorems formalizing this
paper, complementing the DNC book catalog's `Chapter12` (§12.4.2 defers its data-scaling calculus + the
constant-scaling instability trajectory here). The achievable core — the scaling operator, the maximal
scaling curve, the scaled arrival-curve propagation, and the gain-identity grounding the §12.4.2
divergence in genuine scaling operations — is formalized; the explicit adversarial piecewise-linear
backlog-growing trajectory (Fig. 12.5) stays `[deferred]`. -/

namespace DeepWiki.Fs

open DeepWiki

/-- **Definition 3.1** (p.290): a scaling function `S ∈ ℱ` — `S 0 = 0` and monotone — applied to a
flow's cumulative `scale S F = S ∘ F`. The library's `DeepWiki.IsScalingFunction` / `DeepWiki.scale`. -/
abbrev def_3_1 := @IsScalingFunction

/-- **Definition 3.2** (p.290): a maximal scaling curve `S̄` for `S` — the additive bound
`S(b+a) ≤ S̄ b + S a` (equivalently `S̄ ≥ S ⊘ S`). The library's `DeepWiki.IsMaximalScalingCurve`. -/
abbrev def_3_2 := @IsMaximalScalingCurve

/-- **Corollary 3.4** (p.292): the scaled output of an `α`-constrained flow has arrival curve
`α_S = S̄ ∘ α` — `scale S F` is `(S̄ ∘ α)`-arrival-bounded. The library's
`DeepWiki.IsMaximalScalingCurve.isMaximalArrivalBound_scale`. -/
alias cor_3_4 := IsMaximalScalingCurve.isMaximalArrivalBound_scale

/-- **§12.4.2 gain grounding** (Lemma 12.6 link): the cyclic-network instability gain
`m₂m₄/((1−m₂)(1−m₄))` factors per-hop, and its numerator `m₂·m₄` is the composed cross-flow linear
scaling `(linearScale m₄ ∘ linearScale m₂) 1` — connecting the formalized `scalingIterate_unbounded`
divergence to genuine data-scaling operations. The library's
`DeepWiki.scaling_gain_eq_perHop_prod` / `DeepWiki.scaling_gain_numerator_eq_comp`. -/
alias gain_grounding := scaling_gain_numerator_eq_comp

/-- **§12.4.2 geometric backlog (Lemma 12.6 trajectory), explicit closed form**: the per-phase burst
sequence `σₙ = (c·σ + d)^[n] σ₀` has the division-free form `cⁿ·σ₀ + d·∑_{k<n} cᵏ`
(`burstSeq_eq`) and diverges `→ ⊤` in the unstable regime `c ≥ 1, d > 0` (`burstSeq_tendsto_atTop`),
with `c` = the scaling gain `m₂m₄/((1−m₂)(1−m₄))` (`scalingBurstSeq_unbounded`). The library's
`DeepWiki.burstSeq_eq`. -/
alias lemma_12_6_geometric := burstSeq_eq

/-- **§12.4.2 adversarial witness trajectory**: a concrete bursty-staircase cumulative
`burstTrajectory` (data injected at each phase boundary, reaching `σₙ`) is a genuine flow whose backlog
against a stalled departure is unbounded — `Deviation.backlog = ⊤` and `maxBackloggedLength = ⊤`
(`backlog_burstTrajectory`), realizing the geometric divergence along an actual flow. The library's
`DeepWiki.backlog_burstTrajectory` (sequence `DeepWiki.burstTrajectory`). (The full Fig-12.5 coupled
cyclic served-pair dynamics + the [FID 06b] Def-3.3 descaled `S⁻¹` backlog reading stay `[deferred]`.) -/
alias fig_12_5_witness := backlog_burstTrajectory

/-- **§12.4.2 Fig-12.5 coupled cycle dynamics**: the per-cycle burst map is literally the COMPOSITION of
the two servers' scale+residual operations — `cycleBurst m2 m4 = hopBurst m4 ∘ hopBurst m2`, where each
`hopBurst` is grounded in the genuine NC output operation (`hopBurst_eq_descaledOutputBurst` = residual
rate-latency + Theorem 7.1 deconvolution) — and it equals the affine step `σ ↦ cycleGain·σ + cycleOffset`
(`cycleBurst_eq`, `cycleGain = m₂m₄/((1−m₂)(1−m₄))`). The library's `DeepWiki.cycleBurst_eq`. -/
alias fig_12_5_cycle := cycleBurst_eq

/-- **§12.4.2 the geometric trajectory GENERATED by the coupled loop**: iterating the cycle map is the
geometric `burstSeq` (`cycleBurst_iterate_eq_burstSeq`), and the witness trajectory's backlog `= ⊤` is
realized BY the coupled dynamics (`backlog_burstTrajectory_cycle`, for `m₂+m₄ ≥ 1`) — not merely
posited. The library's `DeepWiki.backlog_burstTrajectory_cycle`. (Residual `[infra]`/`[deferred]`: the
general multi-flow served-pair network model + the literal continuous-time Fig-12.6 sample path.) -/
alias fig_12_5_generated := backlog_burstTrajectory_cycle

end DeepWiki.Fs
