import DeepWiki.Refine.Basic
import DeepWiki.Refine.RelationStructure
import DeepWiki.Refine.AnnotationLattice
import DeepWiki.Refine.RelationEquivalence
import DeepWiki.Refine.DependencyRequirements
import DeepWiki.Refine.DependencyMinimality
import DeepWiki.Refine.AnnotationConstraintSolver
import DeepWiki.Refine.AnnotationConstraintGraph
import DeepWiki.Refine.TypeEquivalence
import DeepWiki.Refine.FunctionalRelation
import DeepWiki.Refine.UniverseRelationStructure
import DeepWiki.Refine.Dependent
import DeepWiki.Refine.DependentCalculusSyntax
import DeepWiki.Refine.DependentCalculusTyping
import DeepWiki.Refine.DependentCalculusConfluence
import DeepWiki.Refine.RawParametricitySyntax
import DeepWiki.Refine.RawParametricityTyping
import DeepWiki.Refine.RawParametricityConversion
import DeepWiki.Refine.RawParametricityAbstraction
import DeepWiki.Refine.UnivalentUniverseQuotation
import DeepWiki.Refine.ParametricitySequents
import DeepWiki.Refine.ParametricitySequentRenaming
import DeepWiki.Refine.RawParametricityAbstractionCounterexample
import DeepWiki.Refine.UnivalentParametricitySequents
import DeepWiki.Refine.AnnotatedDependentCalculus
import DeepWiki.Refine.MaximalAnnotation
import DeepWiki.Refine.AnnotatedCalculusConservativity
import DeepWiki.Refine.DependentCalculusRegularity
import DeepWiki.Refine.DependentCalculusPrincipalTyping
import DeepWiki.Refine.DependentCalculusCumulativeInversion
import DeepWiki.Refine.DependentCalculusSubjectReduction
import DeepWiki.Refine.AnnotatedCalculusApplicationTransport
import DeepWiki.Refine.AnnotatedRelationTranslation
import DeepWiki.Refine.AnnotatedTranslationErasure
import DeepWiki.Refine.AnnotatedParametricityErasure
import DeepWiki.Refine.AnnotatedParametricityErasureRealizers
import DeepWiki.Refine.MaximalAnnotationScopeBridge
import DeepWiki.Refine.UniverseWitnessConsequences
import DeepWiki.Refine.StructuredUniverseQuotationSyntax
import DeepWiki.Refine.StructuredUniverseQuotationContext
import DeepWiki.Refine.StructuredUniverseQuotationTyping
import DeepWiki.Refine.RegisteredConstantSyntax
import DeepWiki.Refine.RegisteredConstantTranslationLawfulness
import DeepWiki.Refine.RegisteredConstantWeakeningRows
import DeepWiki.Refine.RecursiveWitnessWeakening
import DeepWiki.Refine.RecursiveWitnessWeakeningSubtypeIndexed
import DeepWiki.Refine.MetaWitnessWeakeningEvaluator
import DeepWiki.Refine.ArrowRelationStructure
import DeepWiki.Refine.PiRelationStructure
import DeepWiki.Refine.ProofTransfer
import DeepWiki.Refine.RetractiveNaturalInduction
import DeepWiki.Refine.ExtendedNonnegativeSums
import DeepWiki.Refine.BitVectorRepresentation
import DeepWiki.Refine.IntegerModularRetraction
import DeepWiki.Refine.Examples
import DeepWiki.Refine.SummableSequenceTransfer
import DeepWiki.Refine.PolymorphicListRelations
import DeepWiki.Refine.TupleVectorTransfer
import DeepWiki.Refine.CoreParametricity
import DeepWiki.Refine.ParametricityTranslations
import DeepWiki.Refine.UnivalentRelationStructure
import DeepWiki.Refine.WitnessWeakening
import DeepWiki.Refine.Resolve
import DeepWiki.Refine.Goal
import DeepWiki.Refine.Poly
import DeepWiki.Refine.Gcd
import DeepWiki.Refine.ResolverTheory

/-! # Relational refinement and proof transfer

This library combines a heterogeneous refinement kernel, structured relations indexed by annotation
strength, dependent relation translations, and first-order proof-transfer automation. `Refines.app`
composes operation witnesses, `refine_transfer` synthesizes related abstract terms, and `refine_goal`
transfers first-order propositions. Additional modules provide relation structure, dependent
products, witness weakening, concrete representations, and a multisorted semantics for the resolver. -/
