-- ## Abstract theory on Mathlib carriers
import DeepWiki.SymbolicIntegration.AlgebraicConstants
import DeepWiki.SymbolicIntegration.AlgebraicCompleteness
import DeepWiki.SymbolicIntegration.CanonicalRepresentation
import DeepWiki.SymbolicIntegration.CompletePartialFraction
import DeepWiki.SymbolicIntegration.Constants
import DeepWiki.SymbolicIntegration.DifferentialAlgebra
import DeepWiki.SymbolicIntegration.DifferentialAlgebraFacts
import DeepWiki.SymbolicIntegration.Core
import DeepWiki.SymbolicIntegration.DifferentialExtensions
import DeepWiki.SymbolicIntegration.GroebnerBasis
import DeepWiki.SymbolicIntegration.HorowitzLinearSolve
import DeepWiki.SymbolicIntegration.InFieldIntegration
import DeepWiki.SymbolicIntegration.InFieldIntegrationCapstone
import DeepWiki.SymbolicIntegration.LaurentCoefficients
import DeepWiki.SymbolicIntegration.LiouvilleExpExtension
import DeepWiki.SymbolicIntegration.LiouvilleLog
import DeepWiki.SymbolicIntegration.LiouvilleStructure
import DeepWiki.SymbolicIntegration.LrtMonicLogs
import DeepWiki.SymbolicIntegration.MonomialConstants
import DeepWiki.SymbolicIntegration.PartialFraction
import DeepWiki.Algebra.PseudoDivision
import DeepWiki.SymbolicIntegration.PseudoRemainderSequence
import DeepWiki.SymbolicIntegration.RationalFunctionDerivative
import DeepWiki.SymbolicIntegration.RationalIntegration
import DeepWiki.SymbolicIntegration.RationalIntegrationExamples
import DeepWiki.SymbolicIntegration.RationalIntegrationAlgorithms
import DeepWiki.SymbolicIntegration.RationalIntegrationGcdLogForm
import DeepWiki.SymbolicIntegration.RationalIntegrationInvXPow
import DeepWiki.SymbolicIntegration.RationalIntegrationLiouville
import DeepWiki.SymbolicIntegration.RationalIntegrationLogForm
import DeepWiki.SymbolicIntegration.RealFieldExamples
import DeepWiki.SymbolicIntegration.RecognizingLogDeriv
import DeepWiki.SymbolicIntegration.Residues
import DeepWiki.SymbolicIntegration.RiobooCoprimality
import DeepWiki.SymbolicIntegration.RiobooCoprimalityLrt
import DeepWiki.SymbolicIntegration.RiobooLogToAtan
import DeepWiki.SymbolicIntegration.RiobooLogToAtanExample
import DeepWiki.SymbolicIntegration.RiobooLogToReal
import DeepWiki.SymbolicIntegration.RiobooLogToRealRecursion
import DeepWiki.SymbolicIntegration.RiobooLogToRealSplit
import DeepWiki.SymbolicIntegration.RiobooRealLogarithm
import DeepWiki.SymbolicIntegration.SpecialFirstKind
import DeepWiki.SymbolicIntegration.CanonicalRepresentation.SpecialNormalCoprime
import DeepWiki.ComputableAlgebra.PolySquarefreeTheory
import DeepWiki.SymbolicIntegration.SubresultantCorrectness
import DeepWiki.Algebra.SubresultantPRS
import DeepWiki.Algebra.SubresultantSpec

-- ## Concrete `Compute` layer + generic executable `Engine`
import DeepWiki.SymbolicIntegration.Compute
import DeepWiki.SymbolicIntegration.Engine

/-! # Symbolic Integration — topic aggregator

The abstract theory on Mathlib carriers, the concrete `Compute` layer over Mathlib
`Polynomial`, and the generic executable Risch `Engine` (core, base Risch DE,
hyperexponential, coupled systems, towers, algebraic functions, and the
soundness/completeness capstone). -/
