import DeepWiki.SymbolicIntegration.Engine.Algebraic.FiniteFieldFactor

/-! # Computable Hensel factor-lift: one quadratic Newton step mod `p^m` → mod `p^{2m}`

Lifts a coprime factorization `f ≡ g·h (mod p^m)` (with Bézout cofactors) to mod `p^{2m}`
on `List ℤ` coefficient lists, congruence phrased as `C (n : ℤ) ∣ (a − b)` (`polyCongr`).
Multiply-back soundness `liftStep_congr` and the cofactor lift `liftBezout_congr` are proven;
`reduceModN` keeps coefficients small for `native_decide` validation. -/

open Polynomial

namespace DeepWiki.SymbolicIntegration

/-! ## Congruence of `ℤ`-polynomials modulo `n`

`polyCongr n a b` is `C (n : ℤ) ∣ (a − b)` on `ℤ[X]`: an equivalence congruent with `+`, `−`, `*`. -/

/-- `a ≡ b (mod n)` at the polynomial level: `C (n : ℤ)` divides `a − b`. The congruence in the
ideal generated by the constant `n`. -/
def polyCongr (n : ℕ) (a b : ℤ[X]) : Prop := (C (n : ℤ)) ∣ (a - b)

/-- `polyCongr n a a`: every polynomial is congruent to itself. -/
theorem polyCongr_refl (n : ℕ) (a : ℤ[X]) : polyCongr n a a := by
  simp [polyCongr]

/-- `polyCongr n a b` iff `C n ∣ (a − b)` — definitional, exposed for rewriting. -/
theorem polyCongr_iff (n : ℕ) (a b : ℤ[X]) : polyCongr n a b ↔ (C (n : ℤ)) ∣ (a - b) := Iff.rfl

/-- A congruence from an explicit witness: `a − b = C n * k → a ≡ b (mod n)`. -/
theorem polyCongr_of_eq (n : ℕ) {a b : ℤ[X]} (k : ℤ[X]) (h : a - b = C (n : ℤ) * k) :
    polyCongr n a b := ⟨k, h⟩

/-- Symmetry: `a ≡ b → b ≡ a`. -/
theorem polyCongr_symm {n : ℕ} {a b : ℤ[X]} (h : polyCongr n a b) : polyCongr n b a := by
  rw [polyCongr] at h ⊢
  rcases h with ⟨k, hk⟩
  exact ⟨-k, by rw [mul_neg, ← hk]; ring⟩

/-- Transitivity: `a ≡ b → b ≡ c → a ≡ c`. -/
theorem polyCongr_trans {n : ℕ} {a b c : ℤ[X]} (hab : polyCongr n a b) (hbc : polyCongr n b c) :
    polyCongr n a c := by
  rw [polyCongr] at hab hbc ⊢
  have : a - c = (a - b) + (b - c) := by ring
  rw [this]; exact dvd_add hab hbc

/-! ## Divisibility by `C (p^m)` squares into `C (p^{2m})` -/

/-- `C (p^m) * C (p^m) = C (p^{2m})` (so the squared modulus appears from two `mod p^m` factors). -/
theorem C_pow_mul_C_pow (p m : ℕ) :
    (C ((p ^ m : ℕ) : ℤ)) * (C ((p ^ m : ℕ) : ℤ)) = C ((p ^ (2 * m) : ℕ) : ℤ) := by
  rw [← C_mul]
  congr 1
  push_cast
  rw [two_mul, pow_add]

/-- If `C (p^m) ∣ u` and `C (p^m) ∣ v` then `C (p^{2m}) ∣ (u * v)`. -/
theorem C_pow_two_mul_dvd_mul {p m : ℕ} {u v : ℤ[X]}
    (hu : (C ((p ^ m : ℕ) : ℤ)) ∣ u) (hv : (C ((p ^ m : ℕ) : ℤ)) ∣ v) :
    (C ((p ^ (2 * m) : ℕ) : ℤ)) ∣ (u * v) := by
  rcases hu with ⟨a, ha⟩
  rcases hv with ⟨b, bk⟩
  refine ⟨a * b, ?_⟩
  rw [ha, bk, ← C_pow_mul_C_pow]; ring

/-! ## The lifting-step data (computable, over `List ℤ`)

The defect `e = f − g·h`, the lifted factors `g' = g + t·e`, `h' = h + s·e`, and the
coefficient reducer `reduceModN`. -/

/-- The defect `f − g·h` of a factorization, as a coefficient list. -/
def defectL (f g h : List ℤ) : List ℤ := subL f (mulL g h)

/-- `listToPoly (defectL f g h) = toPolyZ f − toPolyZ g * toPolyZ h`. -/
theorem toPoly_defectL (f g h : List ℤ) :
    listToPoly (defectL f g h) = toPolyZ f - toPolyZ g * toPolyZ h := by
  rw [defectL, toPoly_subL, toPoly_mulL, toPolyZ, toPolyZ, toPolyZ]

/-- Reduce every coefficient mod `n` (entrywise `Int.emod` into `[0, n)`). -/
def reduceModN (n : ℕ) (l : List ℤ) : List ℤ := l.map (fun a => a % (n : ℤ))

/-- Each reduced coefficient differs from the original by a multiple of `n`:
`a − a % n = n * (a / n)`. -/
theorem reduceModN_congr_coeff (n : ℕ) (a : ℤ) : a - a % (n : ℤ) = (n : ℤ) * (a / (n : ℤ)) := by
  have := Int.mul_ediv_add_emod a (n : ℤ)
  linarith [this]

/-- `reduceModN` is congruent to the identity mod `n`: `listToPoly (reduceModN n l) ≡ listToPoly l (mod n)`. -/
theorem polyCongr_toPoly_reduceModN (n : ℕ) (l : List ℤ) :
    polyCongr n (listToPoly (reduceModN n l)) (listToPoly l) := by
  induction l with
  | nil => simp [reduceModN]; exact polyCongr_refl n 0
  | cons a as ih =>
    rw [reduceModN, List.map_cons, toPoly_cons, toPoly_cons, ← reduceModN]
    rcases ih with ⟨k, hk⟩
    refine ⟨-C (a / (n : ℤ)) + X * k, ?_⟩
    have hcoeff : C (a % (n : ℤ)) - C a = -(C (n : ℤ) * C (a / (n : ℤ))) := by
      rw [← C_mul, ← C_neg, ← C_sub]
      congr 1
      have := reduceModN_congr_coeff n a
      linarith [this]
    rw [show (C (a % (n : ℤ)) + X * listToPoly (reduceModN n as))
          - (C a + X * listToPoly as)
        = (C (a % (n : ℤ)) - C a) + X * (listToPoly (reduceModN n as) - listToPoly as) by ring,
      hcoeff, hk]
    ring

/-- The quadratic lifting step: from `f, g, h, s, t` compute `(g', h')` mod `p^{2m}` with
`g' = g + t·e`, `h' = h + s·e` (`e = f − g·h`), each reduced mod `p^{2m}`. -/
def liftStep (p m : ℕ) (f g h s t : List ℤ) : List ℤ × List ℤ :=
  let e := defectL f g h
  let n2 := p ^ (2 * m)
  (reduceModN n2 (addL g (mulL t e)), reduceModN n2 (addL h (mulL s e)))

/-! ## Multiply-back soundness of one step

The Newton quadratic-convergence identity read through the congruence algebra:
`f − g₀·h₀ = e·(1 − (s·g + t·h)) − s·t·e²`, both summands `≡ 0 (mod p^{2m})`. -/

/-- The exact polynomial Newton identity over `ℤ`: with `e := F − G*H`,
`F − (G + T*e)*(H + S*e) = e*(1 − (S*G + T*H)) − S*T*e²`. -/
theorem newton_identity (F G H S T : ℤ[X]) :
    let e := F - G * H
    F - (G + T * e) * (H + S * e)
      = e * (1 - (S * G + T * H)) - S * T * (e * e) := by
  intro e
  show F - (G + T * (F - G * H)) * (H + S * (F - G * H))
      = (F - G * H) * (1 - (S * G + T * H)) - S * T * ((F - G * H) * (F - G * H))
  ring

/-- Un-reduced multiply-back: with `e := toPolyZ f − toPolyZ g * toPolyZ h`,
`toPolyZ f ≡ (toPolyZ g + toPolyZ t * e) * (toPolyZ h + toPolyZ s * e) (mod p^{2m})`, given
`f ≡ g·h (mod p^m)` and `s·g + t·h ≡ 1 (mod p^m)`. -/
theorem liftStepRaw_congr (p m : ℕ) (f g h s t : List ℤ)
    (hdef : polyCongr (p ^ m) (toPolyZ f) (toPolyZ g * toPolyZ h))
    (hbez : polyCongr (p ^ m) (toPolyZ s * toPolyZ g + toPolyZ t * toPolyZ h) 1) :
    polyCongr (p ^ (2 * m)) (toPolyZ f)
      ((toPolyZ g + toPolyZ t * (toPolyZ f - toPolyZ g * toPolyZ h)) *
        (toPolyZ h + toPolyZ s * (toPolyZ f - toPolyZ g * toPolyZ h))) := by
  set F := toPolyZ f
  set G := toPolyZ g
  set H := toPolyZ h
  set S := toPolyZ s
  set T := toPolyZ t
  set e := F - G * H with hedef
  -- e ≡ 0 (mod p^m): C (p^m) ∣ e
  have he : (C ((p ^ m : ℕ) : ℤ)) ∣ e := by
    rcases hdef with ⟨k, hk⟩; exact ⟨k, by rw [hedef, hk]⟩
  -- 1 − (S*G + T*H) ≡ 0 (mod p^m)
  have hb : (C ((p ^ m : ℕ) : ℤ)) ∣ (1 - (S * G + T * H)) := by
    rcases hbez with ⟨k, hk⟩; exact ⟨-k, by rw [mul_neg, ← hk]; ring⟩
  -- the two summands of the Newton residue are each divisible by C (p^{2m})
  have h1 : (C ((p ^ (2 * m) : ℕ) : ℤ)) ∣ (e * (1 - (S * G + T * H))) :=
    C_pow_two_mul_dvd_mul he hb
  have h2 : (C ((p ^ (2 * m) : ℕ) : ℤ)) ∣ (S * T * (e * e)) := by
    have hee : (C ((p ^ (2 * m) : ℕ) : ℤ)) ∣ (e * e) := C_pow_two_mul_dvd_mul he he
    exact Dvd.dvd.mul_left hee (S * T)
  -- f − g'·h' = first − second, divisible by C (p^{2m})
  rw [polyCongr]
  have hid := newton_identity F G H S T
  simp only at hid
  rw [hid]
  exact dvd_sub h1 h2

/-- Multiply-back soundness of one Hensel step: for `(g', h') = liftStep p m f g h s t`, given
`f ≡ g·h (mod p^m)` and `s·g + t·h ≡ 1 (mod p^m)`,
`toPolyZ f ≡ toPolyZ g' * toPolyZ h' (mod p^{2m})`. -/
theorem liftStep_congr (p m : ℕ) (f g h s t : List ℤ)
    (hdef : polyCongr (p ^ m) (toPolyZ f) (toPolyZ g * toPolyZ h))
    (hbez : polyCongr (p ^ m) (toPolyZ s * toPolyZ g + toPolyZ t * toPolyZ h) 1) :
    polyCongr (p ^ (2 * m)) (toPolyZ f)
      (toPolyZ (liftStep p m f g h s t).1 * toPolyZ (liftStep p m f g h s t).2) := by
  -- abbreviations for the raw (un-reduced) lifted factors
  set e := defectL f g h with hedef
  set g0 := addL g (mulL t e) with hg0def
  set h0 := addL h (mulL s e) with hh0def
  -- the reduced factors are the liftStep output
  have hfst : (liftStep p m f g h s t).1 = reduceModN (p ^ (2 * m)) g0 := rfl
  have hsnd : (liftStep p m f g h s t).2 = reduceModN (p ^ (2 * m)) h0 := rfl
  rw [hfst, hsnd]
  -- step 1: toPolyZ g' ≡ toPolyZ g0, toPolyZ h' ≡ toPolyZ h0 (mod p^{2m})
  have hcg : polyCongr (p ^ (2 * m)) (listToPoly (reduceModN (p ^ (2 * m)) g0)) (listToPoly g0) :=
    polyCongr_toPoly_reduceModN _ _
  have hch : polyCongr (p ^ (2 * m)) (listToPoly (reduceModN (p ^ (2 * m)) h0)) (listToPoly h0) :=
    polyCongr_toPoly_reduceModN _ _
  -- listToPoly g0 = listToPoly g + listToPoly t * (listToPoly f − listToPoly g * listToPoly h)  (toPolyZ = listToPoly defeq)
  have hg0poly : listToPoly g0 = listToPoly g + listToPoly t * (listToPoly f - listToPoly g * listToPoly h) := by
    rw [hg0def, toPoly_addL, toPoly_mulL, hedef, toPoly_defectL, toPolyZ, toPolyZ, toPolyZ]
  have hh0poly : listToPoly h0 = listToPoly h + listToPoly s * (listToPoly f - listToPoly g * listToPoly h) := by
    rw [hh0def, toPoly_addL, toPoly_mulL, hedef, toPoly_defectL, toPolyZ, toPolyZ, toPolyZ]
  -- the product of the reduced factors ≡ the product of g0,h0 (mod p^{2m})
  have hprod : polyCongr (p ^ (2 * m))
      (listToPoly (reduceModN (p ^ (2 * m)) g0) * listToPoly (reduceModN (p ^ (2 * m)) h0))
      (listToPoly g0 * listToPoly h0) := by
    -- g'h' − g0h0 = (g' − g0) h' + g0 (h' − h0)
    rcases hcg with ⟨kg, hkg⟩
    rcases hch with ⟨kh, hkh⟩
    refine ⟨kg * listToPoly (reduceModN (p ^ (2 * m)) h0) + listToPoly g0 * kh, ?_⟩
    have hexpand :
        listToPoly (reduceModN (p ^ (2 * m)) g0) * listToPoly (reduceModN (p ^ (2 * m)) h0)
          - listToPoly g0 * listToPoly h0
        = (listToPoly (reduceModN (p ^ (2 * m)) g0) - listToPoly g0)
            * listToPoly (reduceModN (p ^ (2 * m)) h0)
          + listToPoly g0 * (listToPoly (reduceModN (p ^ (2 * m)) h0) - listToPoly h0) := by ring
    rw [hexpand, hkg, hkh]; ring
  -- the raw multiply-back (mod p^{2m}); `toPolyZ` unfolds to `listToPoly` (defeq)
  have hraw := liftStepRaw_congr p m f g h s t hdef hbez
  simp only [toPolyZ] at hraw ⊢
  rw [← hg0poly, ← hh0poly] at hraw
  -- chain: f ≡ g0·h0 ≡ g'·h'
  exact polyCongr_trans hraw (polyCongr_symm hprod)

/-! ## Lifting the Bézout cofactors (to iterate)

With the Bézout defect `b := s·g' + t·h' − 1`, set `s' := s − s·b`, `t' := t − t·b`
(reduced mod `p^{2m}`); then `s'·g' + t'·h' = 1 − b² ≡ 1 (mod p^{2m})`, so the relation lifts. -/

/-- The Bézout defect of cofactors `s, t` for factors `gp, hp`: `s·gp + t·hp − 1`, as a
coefficient list. -/
def bezoutDefectL (s t gp hp : List ℤ) : List ℤ :=
  subL (addL (mulL s gp) (mulL t hp)) [1]

/-- `listToPoly (bezoutDefectL s t gp hp) = toPolyZ s * toPolyZ gp + toPolyZ t * toPolyZ hp − 1`. -/
theorem toPoly_bezoutDefectL (s t gp hp : List ℤ) :
    listToPoly (bezoutDefectL s t gp hp)
      = toPolyZ s * toPolyZ gp + toPolyZ t * toPolyZ hp - 1 := by
  rw [bezoutDefectL, toPoly_subL, toPoly_addL, toPoly_mulL, toPoly_mulL, toPolyZ, toPolyZ, toPolyZ,
    toPolyZ]
  simp [listToPoly]

/-- Lift the Bézout cofactors for `gp, hp`: with `b := s·gp + t·hp − 1`,
`s' := s − s·b`, `t' := t − t·b`, each reduced mod `p^{2m}`. -/
def liftBezout (p m : ℕ) (s t gp hp : List ℤ) : List ℤ × List ℤ :=
  let b := bezoutDefectL s t gp hp
  let n2 := p ^ (2 * m)
  (reduceModN n2 (subL s (mulL s b)), reduceModN n2 (subL t (mulL t b)))

/-- Raw Bézout-cofactor lift soundness: with `b := S·Gp + T·Hp − 1`, the raw lifted cofactors
`S − S·b`, `T − T·b` satisfy `(S − S·b)·Gp + (T − T·b)·Hp ≡ 1 (mod p^{2m})`, given
`S·Gp + T·Hp ≡ 1 (mod p^m)`. -/
theorem liftBezoutRaw_congr (p m : ℕ) (s t gp hp : List ℤ)
    (hbdef : polyCongr (p ^ m) (toPolyZ s * toPolyZ gp + toPolyZ t * toPolyZ hp) 1) :
    polyCongr (p ^ (2 * m))
      ((toPolyZ s - toPolyZ s * (toPolyZ s * toPolyZ gp + toPolyZ t * toPolyZ hp - 1)) * toPolyZ gp
        + (toPolyZ t - toPolyZ t * (toPolyZ s * toPolyZ gp + toPolyZ t * toPolyZ hp - 1))
            * toPolyZ hp)
      1 := by
  set S := toPolyZ s
  set T := toPolyZ t
  set Gp := toPolyZ gp
  set Hp := toPolyZ hp
  set b := S * Gp + T * Hp - 1 with hbdef'
  -- b ≡ 0 (mod p^m)
  have hb : (C ((p ^ m : ℕ) : ℤ)) ∣ b := by
    rcases hbdef with ⟨k, hk⟩; exact ⟨k, by rw [hbdef', hk]⟩
  -- b² ≡ 0 (mod p^{2m})
  have hbb : (C ((p ^ (2 * m) : ℕ) : ℤ)) ∣ (b * b) := C_pow_two_mul_dvd_mul hb hb
  -- (S − S·b)·Gp + (T − T·b)·Hp − 1 = −b²
  rw [polyCongr]
  have hid : ((S - S * b) * Gp + (T - T * b) * Hp) - 1 = -(b * b) := by
    show ((S - S * b) * Gp + (T - T * b) * Hp) - 1 = -((S * Gp + T * Hp - 1) * (S * Gp + T * Hp - 1))
    ring
  rw [hid]
  exact (dvd_neg).2 hbb

/-- Bézout-cofactor lift soundness: for `(s', t') = liftBezout p m s t gp hp`, given
`s·gp + t·hp ≡ 1 (mod p^m)`,
`toPolyZ s' * toPolyZ gp + toPolyZ t' * toPolyZ hp ≡ 1 (mod p^{2m})`. -/
theorem liftBezout_congr (p m : ℕ) (s t gp hp : List ℤ)
    (hbdef : polyCongr (p ^ m) (toPolyZ s * toPolyZ gp + toPolyZ t * toPolyZ hp) 1) :
    polyCongr (p ^ (2 * m))
      (toPolyZ (liftBezout p m s t gp hp).1 * toPolyZ gp
        + toPolyZ (liftBezout p m s t gp hp).2 * toPolyZ hp)
      1 := by
  set b := bezoutDefectL s t gp hp with hbdef0
  set s0 := subL s (mulL s b) with hs0def
  set t0 := subL t (mulL t b) with ht0def
  have hfst : (liftBezout p m s t gp hp).1 = reduceModN (p ^ (2 * m)) s0 := rfl
  have hsnd : (liftBezout p m s t gp hp).2 = reduceModN (p ^ (2 * m)) t0 := rfl
  rw [hfst, hsnd]
  -- `toPolyZ` unfolds to `listToPoly` (defeq); normalize the goal
  simp only [toPolyZ]
  -- reduced cofactors are congruent to the raw ones (mod p^{2m})
  have hcs : polyCongr (p ^ (2 * m)) (listToPoly (reduceModN (p ^ (2 * m)) s0)) (listToPoly s0) :=
    polyCongr_toPoly_reduceModN _ _
  have hct : polyCongr (p ^ (2 * m)) (listToPoly (reduceModN (p ^ (2 * m)) t0)) (listToPoly t0) :=
    polyCongr_toPoly_reduceModN _ _
  -- raw cofactors as polynomials (in `listToPoly` form throughout)
  have hs0poly : listToPoly s0
      = listToPoly s - listToPoly s * (listToPoly s * listToPoly gp + listToPoly t * listToPoly hp - 1) := by
    rw [hs0def, toPoly_subL, toPoly_mulL, hbdef0, toPoly_bezoutDefectL, toPolyZ, toPolyZ, toPolyZ,
      toPolyZ]
  have ht0poly : listToPoly t0
      = listToPoly t - listToPoly t * (listToPoly s * listToPoly gp + listToPoly t * listToPoly hp - 1) := by
    rw [ht0def, toPoly_subL, toPoly_mulL, hbdef0, toPoly_bezoutDefectL, toPolyZ, toPolyZ, toPolyZ,
      toPolyZ]
  -- the Bézout combination with reduced cofactors ≡ that with raw cofactors (mod p^{2m})
  have hcomb : polyCongr (p ^ (2 * m))
      (listToPoly (reduceModN (p ^ (2 * m)) s0) * listToPoly gp
        + listToPoly (reduceModN (p ^ (2 * m)) t0) * listToPoly hp)
      (listToPoly s0 * listToPoly gp + listToPoly t0 * listToPoly hp) := by
    rcases hcs with ⟨ks, hks⟩
    rcases hct with ⟨kt, hkt⟩
    refine ⟨ks * listToPoly gp + kt * listToPoly hp, ?_⟩
    have hexpand :
        (listToPoly (reduceModN (p ^ (2 * m)) s0) * listToPoly gp
          + listToPoly (reduceModN (p ^ (2 * m)) t0) * listToPoly hp)
          - (listToPoly s0 * listToPoly gp + listToPoly t0 * listToPoly hp)
        = (listToPoly (reduceModN (p ^ (2 * m)) s0) - listToPoly s0) * listToPoly gp
          + (listToPoly (reduceModN (p ^ (2 * m)) t0) - listToPoly t0) * listToPoly hp := by ring
    rw [hexpand, hks, hkt]; ring
  -- raw soundness
  have hraw := liftBezoutRaw_congr p m s t gp hp hbdef
  simp only [toPolyZ] at hraw
  rw [← hs0poly, ← ht0poly] at hraw
  -- chain: combination(reduced) ≡ combination(raw) ≡ 1
  exact polyCongr_trans hcomb hraw

/-! ## `native_decide` validation of one lifting step

Lift `x² + 1` from its mod-`5` factorization `(x + 3)(x + 2)` one quadratic step to mod `25` and
verify multiply-back, on the list-level `mulL`/`reduceModN` output. -/

-- The mod-`5` defect of `x² + 1 = (x + 3)(x + 2)` vanishes.
example : reduceModN 5 (defectL [1, 0, 1] [3, 1] [2, 1]) = [0, 0, 0] := by native_decide

-- The Bézout relation `1·(x + 3) + (−1)·(x + 2) = 1` holds at list level.
example : subL (addL (mulL [1] [3, 1]) (mulL [-1] [2, 1])) [1] = [0, 0] := by native_decide

-- One quadratic Hensel step lifts `(x + 3, x + 2)` to `(6x + 8, 21x + 22)` mod `25`.
example : liftStep 5 1 [1, 0, 1] [3, 1] [2, 1] [1] [-1] = ([8, 6, 0], [22, 21, 0]) := by
  native_decide

-- Multiply-back mod `25`: the lifted factors reduce to `x² + 1`.
example :
    (let (g', h') := liftStep 5 1 [1, 0, 1] [3, 1] [2, 1] [1] [-1];
      reduceModN 25 (mulL g' h')) = [1, 0, 1, 0, 0] := by native_decide

-- The new defect `f − g'·h'` vanishes mod `25` after one step.
example :
    (let (g', h') := liftStep 5 1 [1, 0, 1] [3, 1] [2, 1] [1] [-1];
      reduceModN 25 (defectL [1, 0, 1] g' h')) = [0, 0, 0, 0, 0] := by native_decide

-- The lifted cofactors for `(6x + 8, 21x + 22)` still satisfy the Bézout relation mod `25`.
example :
    (let (s', t') := liftBezout 5 1 [1] [-1] [8, 6, 0] [22, 21, 0];
      reduceModN 25 (bezoutDefectL s' t' [8, 6, 0] [22, 21, 0])) = [0, 0, 0, 0, 0] := by
  native_decide

/-! ## Downstream iteration and recombination

This file supplies the one-step Hensel primitives: `liftStep`/`liftStep_congr` and
`liftBezout`/`liftBezout_congr`, giving one sound iteration
`(f, g, h, s, t) ↦ (f, g', h', s', t')` over `mod p^m → mod p^{2m}`. The iterative lift and
factor recombination live downstream in `ZassenhausDecider`. -/

end DeepWiki.SymbolicIntegration
