import DeepWiki.ReactiveSystems.LabelledTransitionSystems
import Mathlib.Data.Set.Basic

/-! # CCS: syntax and operational semantics
Milner's Calculus of Communicating Systems. Actions are `Act = L ∪ {τ}` with
`L = A ∪ Ā` (names and complementary co-names); CCS expressions are built from
`nil`, prefixing, choice, parallel composition, restriction, relabelling and
process constants; and the SOS rules inductively generate the
transition relation of the LTS whose states are CCS expressions. The book's
general indexed sum `Σᵢ∈I Pᵢ` is taken via its instances `nil` (`0`) and binary
`choice` (`+`), exactly as the development uses it. -/

namespace DeepWiki.ReactiveSystems

/-- CCS actions over channel names `Name`: the silent action `τ`, an input name
`a`, or an output co-name `ā`. (`Act = L ∪ {τ}` with `L = A ∪ Ā`.) -/
inductive Act (Name : Type*)
  | tau : Act Name
  | name : Name → Act Name
  | coname : Name → Act Name
  deriving DecidableEq

namespace Act

variable {Name : Type*}

/-- Complementation `·̄` on actions: swaps a name and its co-name, fixes `τ`. -/
def co : Act Name → Act Name
  | tau => tau
  | name a => coname a
  | coname a => name a

@[simp] theorem co_tau : (tau : Act Name).co = tau := rfl

@[simp] theorem co_name (a : Name) : (name a).co = coname a := rfl

@[simp] theorem co_coname (a : Name) : (coname a).co = name a := rfl

/-- Complementation is an involution: `ᾱ̄ = α`. -/
@[simp] theorem co_co (a : Act Name) : a.co.co = a := by cases a <;> rfl

/-- `a` is a label (an element of `L`): a name or co-name, not `τ`. -/
def IsLabel (a : Act Name) : Prop := a ≠ tau

/-- The complement of a label is a label. -/
theorem IsLabel.co {a : Act Name} (h : a.IsLabel) : a.co.IsLabel := by
  cases a <;> simp_all [IsLabel]

end Act

/-- A relabelling function: it fixes `τ` and commutes with
complementation, `f(ᾱ) = f(α)‾`. -/
structure IsRelabelling {Name : Type*} (f : Act Name → Act Name) : Prop where
  /-- A relabelling preserves the silent action. -/
  map_tau : f Act.tau = Act.tau
  /-- A relabelling commutes with complementation. -/
  map_co : ∀ a, f a.co = (f a).co

/-- CCS process expressions over channel names `Name` and process constants `K`.
The book's indexed sum `Σᵢ∈I Pᵢ` is represented by its
instances `nil` (empty sum) and binary `choice` (two-element sum). -/
inductive CCS (Name K : Type*)
  /-- The inactive process `0` (empty sum). -/
  | nil : CCS Name K
  /-- A process constant `K`, with body supplied by a definition environment. -/
  | const : K → CCS Name K
  /-- Action prefixing `a.P`. -/
  | pre : Act Name → CCS Name K → CCS Name K
  /-- Binary choice `P + Q`. -/
  | choice : CCS Name K → CCS Name K → CCS Name K
  /-- Parallel composition `P | Q`. -/
  | par : CCS Name K → CCS Name K → CCS Name K
  /-- Restriction `P \ L`. -/
  | restrict : CCS Name K → Set (Act Name) → CCS Name K
  /-- Relabelling `P[f]`. -/
  | relabel : CCS Name K → (Act Name → Act Name) → CCS Name K

/-- The CCS SOS transition relation, parametrised by a definition
environment `defn` giving each process constant `K0` its body `K0 ≝ defn K0`.
`Step defn P α P'` means `P —α→ P'`. -/
inductive Step {Name K : Type*} (defn : K → CCS Name K) :
    CCS Name K → Act Name → CCS Name K → Prop
  /-- ACT: `α.P —α→ P`. -/
  | act (α : Act Name) (P : CCS Name K) : Step defn (.pre α P) α P
  /-- SUM (left summand): a move of `P` is a move of `P + Q`. -/
  | suml {P P' Q : CCS Name K} {α : Act Name} :
      Step defn P α P' → Step defn (.choice P Q) α P'
  /-- SUM (right summand): a move of `Q` is a move of `P + Q`. -/
  | sumr {P Q Q' : CCS Name K} {α : Act Name} :
      Step defn Q α Q' → Step defn (.choice P Q) α Q'
  /-- COM1: `P` moves on its own inside `P | Q`. -/
  | com1 {P P' Q : CCS Name K} {α : Act Name} :
      Step defn P α P' → Step defn (.par P Q) α (.par P' Q)
  /-- COM2: `Q` moves on its own inside `P | Q`. -/
  | com2 {P Q Q' : CCS Name K} {α : Act Name} :
      Step defn Q α Q' → Step defn (.par P Q) α (.par P Q')
  /-- COM3: synchronisation of complementary labels into a `τ`-move. -/
  | com3 {P P' Q Q' : CCS Name K} {ℓ : Act Name} :
      ℓ.IsLabel → Step defn P ℓ P' → Step defn Q ℓ.co Q' →
      Step defn (.par P Q) Act.tau (.par P' Q')
  /-- RES: a move surviving restriction (`α, ᾱ ∉ L`). -/
  | res {P P' : CCS Name K} {α : Act Name} {L : Set (Act Name)} :
      α ∉ L → α.co ∉ L → Step defn P α P' → Step defn (.restrict P L) α (.restrict P' L)
  /-- REL: a move under relabelling, `P[f] —f(α)→ P'[f]`. -/
  | rel {P P' : CCS Name K} {α : Act Name} {f : Act Name → Act Name} :
      Step defn P α P' → Step defn (.relabel P f) (f α) (.relabel P' f)
  /-- CON: a constant `K0` moves as its body does (`K0 ≝ defn K0`). -/
  | con {K0 : K} {α : Act Name} {P' : CCS Name K} :
      Step defn (defn K0) α P' → Step defn (.const K0) α P'

variable {Name K : Type*}

/-- The labelled transition system generated by the CCS SOS rules under a
definition environment: states are CCS expressions, labels are actions. -/
def ccsLTS (defn : K → CCS Name K) : LTS (CCS Name K) (Act Name) := ⟨Step defn⟩

@[simp] theorem ccsLTS_step (defn : K → CCS Name K) (P : CCS Name K) (α : Act Name)
    (P' : CCS Name K) : (ccsLTS defn).step P α P' ↔ Step defn P α P' := Iff.rfl

/-- The inactive process `nil` (`0`) has no transitions. -/
@[simp] theorem not_step_nil {defn : K → CCS Name K} {α : Act Name} {P' : CCS Name K} :
    ¬ Step defn CCS.nil α P' := by intro h; cases h

variable {defn : K → CCS Name K}

/-- Inversion for prefixing: `α.P —β→ P'` iff `β = α` and `P' = P`. -/
@[simp] theorem step_pre_iff {α β : Act Name} {P P' : CCS Name K} :
    Step defn (CCS.pre α P) β P' ↔ β = α ∧ P' = P := by
  constructor
  · rintro h; cases h; exact ⟨rfl, rfl⟩
  · rintro ⟨rfl, rfl⟩; exact Step.act _ _

/-- Inversion for choice: a move of `P + Q` is a move of `P` or of `Q`. -/
@[simp] theorem step_choice_iff {P Q P' : CCS Name K} {α : Act Name} :
    Step defn (CCS.choice P Q) α P' ↔ Step defn P α P' ∨ Step defn Q α P' := by
  constructor
  · rintro h; cases h with
    | suml h => exact Or.inl h
    | sumr h => exact Or.inr h
  · rintro (h | h)
    · exact Step.suml h
    · exact Step.sumr h

/-- Inversion for a process constant: it moves exactly as its body does. -/
theorem step_const_iff {K0 : K} {α : Act Name} {P' : CCS Name K} :
    Step defn (CCS.const K0) α P' ↔ Step defn (defn K0) α P' := by
  constructor
  · rintro h; cases h; assumption
  · exact Step.con

/-- Inversion for parallel composition: a move of `P ∣ Q` is a move of `P` alone
(COM1), of `Q` alone (COM2), or a synchronisation of complementary labels (COM3). -/
theorem step_par_iff {P Q : CCS Name K} {α : Act Name} {R : CCS Name K} :
    Step defn (CCS.par P Q) α R ↔
      (∃ P', Step defn P α P' ∧ R = CCS.par P' Q) ∨
      (∃ Q', Step defn Q α Q' ∧ R = CCS.par P Q') ∨
      (∃ ℓ P' Q', α = Act.tau ∧ ℓ.IsLabel ∧
        Step defn P ℓ P' ∧ Step defn Q ℓ.co Q' ∧ R = CCS.par P' Q') := by
  constructor
  · rintro h
    cases h with
    | com1 hP => exact Or.inl ⟨_, hP, rfl⟩
    | com2 hQ => exact Or.inr (Or.inl ⟨_, hQ, rfl⟩)
    | com3 hℓ hP hQ => exact Or.inr (Or.inr ⟨_, _, _, rfl, hℓ, hP, hQ, rfl⟩)
  · rintro (⟨P', hP, rfl⟩ | ⟨Q', hQ, rfl⟩ | ⟨ℓ, P', Q', rfl, hℓ, hP, hQ, rfl⟩)
    · exact Step.com1 hP
    · exact Step.com2 hQ
    · exact Step.com3 hℓ hP hQ

/-- Inversion for restriction: `P ∖ L` moves only via a move of `P` on an action
`α` with `α, ᾱ ∉ L`. -/
theorem step_restrict_iff {P : CCS Name K} {L : Set (Act Name)} {α : Act Name}
    {R : CCS Name K} :
    Step defn (CCS.restrict P L) α R ↔
      ∃ P', α ∉ L ∧ α.co ∉ L ∧ Step defn P α P' ∧ R = CCS.restrict P' L := by
  constructor
  · rintro h; cases h with | res h1 h2 hP => exact ⟨_, h1, h2, hP, rfl⟩
  · rintro ⟨P', h1, h2, hP, rfl⟩; exact Step.res h1 h2 hP

/-- Inversion for relabelling: `P[f]` moves on `f α` exactly when `P` moves on `α`. -/
theorem step_relabel_iff {P : CCS Name K} {f : Act Name → Act Name} {β : Act Name}
    {R : CCS Name K} :
    Step defn (CCS.relabel P f) β R ↔
      ∃ α P', β = f α ∧ Step defn P α P' ∧ R = CCS.relabel P' f := by
  constructor
  · rintro h; cases h with | rel hP => exact ⟨_, _, rfl, hP, rfl⟩
  · rintro ⟨α, P', rfl, hP, rfl⟩; exact Step.rel hP

/-! ## Book notation for CCS process terms

A syntax category `ccs` lets process expressions be written in (almost) the
book's concrete syntax inside `⟪ … ⟫`, elaborating to `CCS` constructors. The
prefix uses `▸` for `a.P` (Lean reserves `.` for field projection); `‹t›`
splices an existing `CCS` term (e.g. a constant or variable). -/

/-- Syntax category for CCS process terms in book-like notation. -/
declare_syntax_cat ccs

/-- The inactive process `0`. -/
syntax "𝟬" : ccs
/-- Parenthesised process. -/
syntax "(" ccs ")" : ccs
/-- A spliced `CCS` term (constant or variable). -/
syntax "‹" term "›" : ccs
/-- Action prefixing `a ▸ P` (the book's `a.P`). -/
syntax:65 term:max " ▸ " ccs:65 : ccs
/-- Choice `P + Q`. -/
syntax:50 ccs:51 " + " ccs:50 : ccs
/-- Parallel composition `P ∥ Q`. -/
syntax:55 ccs:56 " ∥ " ccs:55 : ccs
/-- Restriction `P ∖ L`. -/
syntax:60 ccs:60 " ∖ " term:max : ccs
/-- Relabelling `P⟦f⟧`. -/
syntax:65 ccs:66 "⟦" term "⟧" : ccs

/-- Elaborate a CCS process term written in book notation. -/
syntax "⟪" ccs "⟫" : term

macro_rules
  | `(⟪ 𝟬 ⟫) => `(CCS.nil)
  | `(⟪ ($p) ⟫) => `(⟪ $p ⟫)
  | `(⟪ ‹$t› ⟫) => `($t)
  | `(⟪ $a:term ▸ $p ⟫) => `(CCS.pre $a ⟪ $p ⟫)
  | `(⟪ $p + $q ⟫) => `(CCS.choice ⟪ $p ⟫ ⟪ $q ⟫)
  | `(⟪ $p ∥ $q ⟫) => `(CCS.par ⟪ $p ⟫ ⟪ $q ⟫)
  | `(⟪ $p ∖ $L:term ⟫) => `(CCS.restrict ⟪ $p ⟫ $L)
  | `(⟪ $p ⟦$f:term⟧ ⟫) => `(CCS.relabel ⟪ $p ⟫ $f)

example {N K : Type} (a : Act N) (P Q : CCS N K) (L : Set (Act N))
    (f : Act N → Act N) :
    ((⟪ a ▸ 𝟬 ⟫ : CCS N K) = CCS.pre a CCS.nil) ∧
    (⟪ ‹P› + ‹Q› ⟫ = CCS.choice P Q) ∧
    (⟪ ‹P› ∥ ‹Q› ⟫ = CCS.par P Q) ∧
    (⟪ ‹P› ∖ L ⟫ = CCS.restrict P L) ∧
    (⟪ ‹P›⟦f⟧ ⟫ = CCS.relabel P f) ∧
    (⟪ a ▸ ‹P› ∥ ‹Q› ⟫ = CCS.par (CCS.pre a P) Q) :=
  ⟨rfl, rfl, rfl, rfl, rfl, rfl⟩

end DeepWiki.ReactiveSystems
