import DeepWiki.SymbolicIntegration.DifferentialAlgebra.Basic

/-! # Constants subfield

The constants of a differential field as a subfield and its closure API.
-/

open scoped Differential

namespace DeepWiki.SymbolicIntegration

section ConstantsSubfield
variable {E : Type*} [Field E] [Differential E]

/-- Constants of a differential field form a subfield. -/
def constantsSubfield (E : Type*) [Field E] [Differential E] : Subfield E where
  toSubring := constants E
  inv_mem' := fun a (ha : a′ = 0) => by
    show (a⁻¹)′ = 0
    rcases eq_or_ne a 0 with rfl | hne
    · simp
    · have h1 : (a * a⁻¹)′ = 0 := by rw [mul_inv_cancel₀ hne]; simp
      rw [Derivation.leibniz, ha, smul_zero, add_zero, smul_eq_mul] at h1
      exact (mul_eq_zero.mp h1).resolve_left hne

/-- Membership in `constantsSubfield E` is the equation `a′ = 0`. -/
@[simp] theorem mem_constantsSubfield {a : E} : a ∈ constantsSubfield E ↔ a′ = 0 := Iff.rfl

/-- The constants subfield inherits characteristic zero from the ambient field. -/
instance charZero_constantsSubfield [CharZero E] : CharZero (constantsSubfield E) where
  cast_injective m n h := by
    have hι := (constantsSubfield E).subtype.injective
    apply Nat.cast_injective (R := E)
    have := congrArg (constantsSubfield E).subtype h
    rwa [map_natCast, map_natCast] at this

/-- The subfield generated by constants is contained in the constants. -/
theorem subfieldClosure_subset_constants {S : Set E} (hS : ∀ s ∈ S, s′ = 0) :
    Subfield.closure S ≤ constantsSubfield E :=
  (Subfield.closure_le).mpr (fun s hs => mem_constantsSubfield.mpr (hS s hs))

end ConstantsSubfield

section ConstantsIntermediateField
variable {F E : Type*} [Field F] [Field E] [Differential F] [Differential E]
  [Algebra F E] [DifferentialAlgebra F E]

/-- The constants of a differential extension as an intermediate field over the base constants. -/
def constantsIntermediateField (F E : Type*) [Field F] [Field E]
    [Differential F] [Differential E] [Algebra F E] [DifferentialAlgebra F E] :
    IntermediateField (constantsSubfield F) E :=
  (constantsSubfield E).toIntermediateField fun c => by
    change (algebraMap F E (c : F))′ = 0
    rw [deriv_algebraMap, c.property, map_zero]

/-- Membership in `constantsIntermediateField F E` is the equation `x′ = 0`. -/
@[simp] theorem mem_constantsIntermediateField {x : E} :
    x ∈ constantsIntermediateField F E ↔ x′ = 0 := Iff.rfl

/-- The underlying subfield of `constantsIntermediateField F E` is `constantsSubfield E`. -/
@[simp] theorem constantsIntermediateField_toSubfield :
    (constantsIntermediateField F E).toSubfield = constantsSubfield E := rfl

/-- `constantsIntermediateField F E = ⊥` iff every constant of `E` lies in the image of the constants of `F`. -/
theorem constantsIntermediateField_eq_bot_iff_constantsSubfield_eq_image :
    constantsIntermediateField F E = ⊥ ↔
      (constantsSubfield E : Set E) =
        algebraMap F E '' (constantsSubfield F : Set F) := by
  constructor
  · intro h
    ext x
    constructor
    · intro hx
      have hxbot : x ∈ (⊥ : IntermediateField (constantsSubfield F) E) := by
        rw [← h]
        exact hx
      obtain ⟨c, hc⟩ := IntermediateField.mem_bot.mp hxbot
      exact ⟨c, c.property, hc⟩
    · rintro ⟨c, hc, rfl⟩
      exact mem_constantsSubfield.mpr (by
        rw [deriv_algebraMap, hc, map_zero])
  · intro h
    apply le_antisymm
    · intro x hx
      have hxsub : x ∈ (constantsSubfield E : Set E) := hx
      have hximage :
          x ∈ algebraMap F E '' (constantsSubfield F : Set F) := by
        rw [← h]
        exact hxsub
      obtain ⟨c, hc, hcx⟩ := hximage
      exact IntermediateField.mem_bot.mpr ⟨⟨c, hc⟩, hcx⟩
    · exact bot_le

end ConstantsIntermediateField

end DeepWiki.SymbolicIntegration
