import DeepWiki.SymbolicIntegration.DifferentialAlgebra.Basic

/-! # Constants subfield

The constants of a differential field as a subfield and its closure API.
-/

open scoped Differential

namespace DeepWiki.SymbolicIntegration

section ConstantsSubfield
variable {E : Type*} [Field E] [Differential E]

/-- Constants of a differential field form a subfield. -/
def constantsSubfield (E : Type*) [Field E] [Differential E] : Subfield E where
  toSubring := constants E
  inv_mem' := fun a (ha : a′ = 0) => by
    show (a⁻¹)′ = 0
    rcases eq_or_ne a 0 with rfl | hne
    · simp
    · have h1 : (a * a⁻¹)′ = 0 := by rw [mul_inv_cancel₀ hne]; simp
      rw [Derivation.leibniz, ha, smul_zero, add_zero, smul_eq_mul] at h1
      exact (mul_eq_zero.mp h1).resolve_left hne

/-- Membership in `constantsSubfield E` is the equation `a′ = 0`. -/
@[simp] theorem mem_constantsSubfield {a : E} : a ∈ constantsSubfield E ↔ a′ = 0 := Iff.rfl

/-- The subfield generated by constants is contained in the constants. -/
theorem subfieldClosure_subset_constants {S : Set E} (hS : ∀ s ∈ S, s′ = 0) :
    Subfield.closure S ≤ constantsSubfield E :=
  (Subfield.closure_le).mpr (fun s hs => mem_constantsSubfield.mpr (hS s hs))

end ConstantsSubfield

end DeepWiki.SymbolicIntegration
