import DeepWiki.SymbolicIntegration.DifferentialAlgebra.Basic
import DeepWiki.SymbolicIntegration.DifferentialAlgebra.PolynomialDerivative
import DeepWiki.SymbolicIntegration.Core.Differential.NormalSpecial.Special

/-! # Differential ideals

Ideals closed under the derivation, including the bottom ideal and principal ideals generated by
special elements.
-/

open scoped Differential
open Polynomial

namespace DeepWiki.SymbolicIntegration

/-- An ideal of a differential ring that is closed under the derivation. -/
structure DifferentialIdeal (R : Type*) [CommRing R] [Differential R] where
  /-- The underlying ring ideal. -/
  toIdeal : Ideal R
  /-- The underlying ideal is closed under the derivation. -/
  deriv_mem' : ∀ a ∈ toIdeal, a′ ∈ toIdeal

namespace DifferentialIdeal

/-- A differential ideal coerces to its underlying set. -/
instance {R : Type*} [CommRing R] [Differential R] : SetLike (DifferentialIdeal R) R where
  coe I := I.toIdeal
  coe_injective I J h := by
    cases I with
    | mk I hI =>
      cases J with
      | mk J hJ =>
        simp only at h
        have hIJ : I = J := SetLike.coe_injective h
        subst J
        rfl

/-- Differential ideals are equal when their underlying ideals are equal. -/
@[ext] theorem ext {R : Type*} [CommRing R] [Differential R] {I J : DifferentialIdeal R}
    (h : I.toIdeal = J.toIdeal) : I = J := by
  cases I
  cases J
  cases h
  rfl

/-- A differential ideal is closed under the derivation. -/
theorem deriv_mem {R : Type*} [CommRing R] [Differential R] (I : DifferentialIdeal R)
    {a : R} (ha : a ∈ I) : a′ ∈ I :=
  I.deriv_mem' a ha

/-- The derivation on `R ⧸ I` induced by a differential ideal `I`. -/
noncomputable def quotientDerivation {R : Type*} [CommRing R] [Differential R]
    (I : DifferentialIdeal R) : Derivation ℤ (R ⧸ I.toIdeal) (R ⧸ I.toIdeal) := by
  let π := Ideal.Quotient.mkₐ ℤ I.toIdeal
  refine Derivation.liftOfSurjective (f := π) (d := Differential.deriv)
    Ideal.Quotient.mk_surjective ?_
  intro a ha
  change Ideal.Quotient.mk I.toIdeal a = 0 at ha
  change Ideal.Quotient.mk I.toIdeal a′ = 0
  rw [Ideal.Quotient.eq_zero_iff_mem] at ha ⊢
  exact I.deriv_mem ha

/-- The induced quotient derivation satisfies `D*(a + I) = D(a) + I`. -/
@[simp] theorem quotientDerivation_mk {R : Type*} [CommRing R]
    [Differential R] (I : DifferentialIdeal R) (a : R) :
    I.quotientDerivation (Ideal.Quotient.mk I.toIdeal a) = Ideal.Quotient.mk I.toIdeal a′ := by
  unfold quotientDerivation
  apply Derivation.liftOfSurjective_apply

/-- A differential ideal induces a derivation on its quotient commuting with the projection. -/
theorem exists_quotientDerivation {R : Type*} [CommRing R] [Differential R]
    (I : DifferentialIdeal R) :
    ∃ Dstar : Derivation ℤ (R ⧸ I.toIdeal) (R ⧸ I.toIdeal),
      ∀ a : R, Dstar (Ideal.Quotient.mk I.toIdeal a) = Ideal.Quotient.mk I.toIdeal a′ :=
  ⟨I.quotientDerivation, I.quotientDerivation_mk⟩

/-- Every ideal is differential when the derivation on the ring is zero. -/
def ofDerivEqZero {R : Type*} [CommRing R] [Differential R]
    (I : Ideal R) (hD : (Differential.deriv : Derivation ℤ R R) = 0) :
    DifferentialIdeal R where
  toIdeal := I
  deriv_mem' := by
    intro a _
    rw [hD]
    exact Ideal.zero_mem I

/-- A quotient derivation induced by the zero derivation is itself zero. -/
theorem quotientDerivation_eq_zero_of_deriv_eq_zero
    {R : Type*} [CommRing R] [Differential R] (I : DifferentialIdeal R)
    (hD : (Differential.deriv : Derivation ℤ R R) = 0) : I.quotientDerivation = 0 := by
  ext x
  obtain ⟨a, rfl⟩ := Ideal.Quotient.mk_surjective x
  rw [I.quotientDerivation_mk]
  change Ideal.Quotient.mk I.toIdeal (Differential.deriv a) = 0
  rw [hD]
  rfl

/-- The bottom differential ideal. -/
@[reducible]
noncomputable instance {R : Type*} [CommRing R] [Differential R] : Bot (DifferentialIdeal R) where
  bot :=
    { toIdeal := ⊥
      deriv_mem' := by
        intro a ha
        simp only [Ideal.mem_bot] at ha ⊢
        simp [ha] }

/-- The top differential ideal. -/
@[reducible]
noncomputable instance {R : Type*} [CommRing R] [Differential R] : Top (DifferentialIdeal R) where
  top :=
    { toIdeal := ⊤
      deriv_mem' := fun _ _ => Submodule.mem_top }

/-- The underlying ideal of `⊥ : DifferentialIdeal R` is `⊥`. -/
@[simp] theorem toIdeal_bot {R : Type*} [CommRing R] [Differential R] :
    (⊥ : DifferentialIdeal R).toIdeal = ⊥ := rfl

/-- The underlying ideal of `⊤ : DifferentialIdeal R` is `⊤`. -/
@[simp] theorem toIdeal_top {R : Type*} [CommRing R] [Differential R] :
    (⊤ : DifferentialIdeal R).toIdeal = ⊤ := rfl

/-- The constants are closed under the derivation. -/
theorem deriv_mem_constants {R : Type*} [CommRing R] [Differential R]
    {a : R} (ha : a ∈ constants R) : a′ ∈ constants R := by
  simp only [mem_constants] at ha ⊢
  simp [ha]

/-- The differential ideal spanned by a special element `p` satisfying `p ∣ p'`. -/
def ofSpecial {R : Type*} [CommRing R] [Differential R] {p : R}
    (hp : IsSpecial p) : DifferentialIdeal R where
  toIdeal := Ideal.span {p}
  deriv_mem' := by
    intro a ha
    rw [Ideal.mem_span_singleton] at ha ⊢
    obtain ⟨b, rfl⟩ := ha
    rw [deriv_mul_eq]
    exact dvd_add (dvd_mul_right p b′) (hp.mul_left b)

end DifferentialIdeal

section PolynomialDerivative

variable {K : Type*} [Field K]
open scoped FormalDiff

/-- The `(deg p)`-fold polynomial derivative is the constant `(deg p)! · lc(p)`. -/
theorem iterate_derivative_natDegree_eq_C (p : K[X]) :
    Polynomial.derivative^[p.natDegree] p
      = Polynomial.C (Nat.factorial p.natDegree • p.leadingCoeff) := by
  have hle : (Polynomial.derivative^[p.natDegree] p).natDegree ≤ 0 := by
    simpa using Polynomial.natDegree_iterate_derivative p p.natDegree
  rw [Polynomial.eq_C_of_natDegree_eq_zero (Nat.le_zero.mp hle)]
  congr 1
  rw [Polynomial.coeff_iterate_derivative]
  simp only [zero_add, Nat.descFactorial_self]
  rw [Polynomial.coeff_natDegree]

/-- The only differential ideals of `(K[X], d/dX)` in characteristic zero are `⊥` and `⊤`. -/
theorem differentialIdeal_eq_bot_or_top [CharZero K] (I : DifferentialIdeal K[X]) :
    I.toIdeal = ⊥ ∨ I.toIdeal = ⊤ := by
  rcases eq_or_ne I.toIdeal ⊥ with h | h
  · exact Or.inl h
  · refine Or.inr ?_
    obtain ⟨p, hpI, hp0⟩ := (Submodule.ne_bot_iff I.toIdeal).mp h
    have hiter : ∀ k, Polynomial.derivative^[k] p ∈ I.toIdeal := by
      intro k
      induction k with
      | zero => simpa using hpI
      | succ m ih =>
          rw [Function.iterate_succ_apply']
          exact I.deriv_mem ih
    have hmem := hiter p.natDegree
    rw [iterate_derivative_natDegree_eq_C p] at hmem
    have hc : (Nat.factorial p.natDegree • p.leadingCoeff) ≠ 0 := by
      simp only [nsmul_eq_mul, ne_eq, mul_eq_zero, not_or]
      exact ⟨by exact_mod_cast Nat.factorial_ne_zero _, Polynomial.leadingCoeff_ne_zero.mpr hp0⟩
    exact Ideal.eq_top_of_isUnit_mem I.toIdeal hmem
      (Polynomial.isUnit_C.mpr (isUnit_iff_ne_zero.mpr hc))

/-- Under `K[X] ⧸ ⊥ ≃ K[X]`, the induced quotient derivation is `d/dX`. -/
theorem polynomialDerivative_quotientBot_apply (x : K[X] ⧸ (⊥ : Ideal K[X])) :
    RingEquiv.quotientBot K[X]
        ((⊥ : DifferentialIdeal K[X]).quotientDerivation x) =
      Polynomial.derivative (RingEquiv.quotientBot K[X] x) := by
  obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective x
  change RingEquiv.quotientBot K[X]
      ((⊥ : DifferentialIdeal K[X]).quotientDerivation
        (Ideal.Quotient.mk (⊥ : DifferentialIdeal K[X]).toIdeal p)) =
    Polynomial.derivative (RingEquiv.quotientBot K[X] (Ideal.Quotient.mk ⊥ p))
  rw [DifferentialIdeal.quotientDerivation_mk]
  change RingEquiv.quotientBot K[X] (Ideal.Quotient.mk ⊥ p′) =
    Polynomial.derivative (RingEquiv.quotientBot K[X] (Ideal.Quotient.mk ⊥ p))
  rw [RingEquiv.quotientBot_mk, RingEquiv.quotientBot_mk]
  rfl

/-- The derivation induced on `K[X] ⧸ ⊤` is zero. -/
theorem polynomialDerivative_quotientTop_eq_zero :
    ((⊤ : DifferentialIdeal K[X]).quotientDerivation) = 0 := by
  ext x
  obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective x
  rw [DifferentialIdeal.quotientDerivation_mk]
  exact Ideal.Quotient.eq_zero_iff_mem.mpr Submodule.mem_top

end PolynomialDerivative

end DeepWiki.SymbolicIntegration
