import DeepWiki.SymbolicIntegration.DifferentialAlgebra.AlgebraicConstants
import DeepWiki.SymbolicIntegration.DifferentialAlgebra.TranscendentalExtension

/-! # Constants of simple differential extensions

Constants in `F⟮t⟯` when the adjoined generator has derivative zero.
-/

open scoped Differential IntermediateField
open Polynomial

namespace DeepWiki.SymbolicIntegration

/-- A zero coefficient derivative on `F(X)` gives the normalized numerator-denominator relation. -/
theorem ratFunc_mapCoeffs_relation_of_coefficient_deriv_eq_zero
    {F : Type*} [Field F] [Differential F] (f : RatFunc F)
    (hf : (ratFuncExtensionOfValue (0 : RatFunc F)).deriv f = 0) :
    f.denom * Differential.mapCoeffs f.num =
      f.num * Differential.mapCoeffs f.denom := by
  let Δ := ratFuncExtensionOfValue (0 : RatFunc F)
  letI : Differential (RatFunc F) := Δ.toDifferential
  have hf' :
      (algebraMap F[X] (RatFunc F) f.num /
        algebraMap F[X] (RatFunc F) f.denom)′ = 0 := by
    rw [RatFunc.num_div_denom]
    exact hf
  rw [deriv_div, ratFuncExtensionOfValue_zero_algebraMap,
    ratFuncExtensionOfValue_zero_algebraMap] at hf'
  have hden :
      algebraMap F[X] (RatFunc F) f.denom ^ 2 ≠ 0 :=
    pow_ne_zero 2
      ((map_ne_zero_iff _ (RatFunc.algebraMap_injective F)).mpr f.denom_ne_zero)
  have hnum :
      algebraMap F[X] (RatFunc F) f.denom *
          algebraMap F[X] (RatFunc F) (Differential.mapCoeffs f.num) -
        algebraMap F[X] (RatFunc F) f.num *
          algebraMap F[X] (RatFunc F) (Differential.mapCoeffs f.denom) = 0 :=
    (div_eq_zero_iff.mp hf').resolve_right hden
  rw [← map_mul, ← map_mul, ← map_sub] at hnum
  exact sub_eq_zero.mp
    ((map_eq_zero_iff _ (RatFunc.algebraMap_injective F)).mp hnum)

/-- A polynomial whose coefficients are constants is the image of a polynomial over the constants. -/
theorem exists_constantsSubfield_polynomial_map_eq
    {F : Type*} [Field F] [Differential F] (p : F[X])
    (hp : ∀ i, (p.coeff i)′ = 0) :
    ∃ q : (constantsSubfield F)[X],
      q.map (constantsSubfield F).subtype = p := by
  have hlifts : p ∈ Polynomial.lifts (constantsSubfield F).subtype := by
    rw [Polynomial.lifts_iff_coeff_lifts]
    intro i
    exact ⟨⟨p.coeff i, mem_constantsSubfield.mpr (hp i)⟩, rfl⟩
  obtain ⟨q, hq, _⟩ := Polynomial.exists_support_eq_of_mem_lifts hlifts
  exact ⟨q, hq⟩

/-- In an algebraic simple extension generated by a constant, all constants come from adjoining that generator to the base constants. -/
theorem constantsIntermediateField_adjoin_eq_adjoin_constants_of_isIntegral
    {F E : Type*} [Field F] [Field E] [Algebra F E] [Differential F]
    (t : E) (ht : IsIntegral F t) (Δ : DifferentialExtension F (F⟮t⟯))
    (hgen : Δ.deriv (IntermediateField.AdjoinSimple.gen F t) = 0) :
    letI : Differential (F⟮t⟯) := Δ.toDifferential
    letI : DifferentialAlgebra F (F⟮t⟯) := Δ.differentialAlgebra
    constantsIntermediateField F (F⟮t⟯) =
      IntermediateField.adjoin (constantsSubfield F)
        {IntermediateField.AdjoinSimple.gen F t} := by
  letI : Differential (F⟮t⟯) := Δ.toDifferential
  letI : DifferentialAlgebra F (F⟮t⟯) := Δ.differentialAlgebra
  let pb := IntermediateField.adjoin.powerBasis ht
  apply le_antisymm
  · intro x hx
    let c : Fin pb.dim → F := fun i => (pb.basis.repr x) i
    have hsum : ∑ i, algebraMap F (F⟮t⟯) (c i) * pb.gen ^ (i : ℕ) = x := by
      simpa [c, PowerBasis.coe_basis, Algebra.smul_def] using pb.basis.sum_repr x
    have hpbgen : pb.gen′ = 0 := by
      rw [IntermediateField.adjoin.powerBasis_gen ht]
      exact hgen
    have hderiv :
        ∑ i, algebraMap F (F⟮t⟯) ((c i)′) * pb.gen ^ (i : ℕ) = 0 := by
      have h := congrArg (fun z : F⟮t⟯ => z′) hsum
      simpa only [map_sum, Derivation.leibniz, deriv_algebraMap, deriv_pow,
        hpbgen, mul_zero, zero_mul, add_zero, smul_eq_mul, mul_comm] using
        h.trans (mem_constantsIntermediateField.mp hx)
    have hc : ∀ i, (c i)′ = 0 := by
      intro i
      have hzero :
          pb.basis.equivFun.symm (fun j => (c j)′) = 0 := by
        rw [Module.Basis.equivFun_symm_apply]
        simpa [PowerBasis.coe_basis, Algebra.smul_def] using hderiv
      have hfun := congrArg pb.basis.equivFun hzero
      rw [LinearEquiv.apply_symm_apply, map_zero] at hfun
      exact congrFun hfun i
    rw [← hsum]
    apply IntermediateField.sum_mem
    intro i _
    apply IntermediateField.mul_mem
    · let ci : constantsSubfield F :=
        ⟨c i, mem_constantsSubfield.mpr (hc i)⟩
      change algebraMap F (F⟮t⟯) (c i) ∈
        IntermediateField.adjoin (constantsSubfield F)
          {IntermediateField.AdjoinSimple.gen F t}
      have hci :
          algebraMap F (F⟮t⟯) (c i) =
            algebraMap (constantsSubfield F) (F⟮t⟯) ci := rfl
      rw [hci]
      exact IntermediateField.algebraMap_mem _ ci
    · apply Subalgebra.pow_mem
      rw [IntermediateField.adjoin.powerBasis_gen ht]
      exact IntermediateField.subset_adjoin _ _ (Set.mem_singleton _)
  · apply IntermediateField.adjoin_le_iff.mpr
    intro x hx
    rw [Set.mem_singleton_iff] at hx
    subst x
    exact mem_constantsIntermediateField.mpr hgen

/-- In a transcendental simple extension generated by a constant, all constants come from adjoining that generator to the base constants. -/
theorem constantsIntermediateField_adjoin_eq_adjoin_constants_of_transcendental
    {F E : Type*} [Field F] [Field E] [Algebra F E] [Differential F]
    (t : E) (ht : Transcendental F t) (Δ : DifferentialExtension F (F⟮t⟯))
    (hgen : Δ.deriv (IntermediateField.AdjoinSimple.gen F t) = 0) :
    letI : Differential (F⟮t⟯) := Δ.toDifferential
    letI : DifferentialAlgebra F (F⟮t⟯) := Δ.differentialAlgebra
    constantsIntermediateField F (F⟮t⟯) =
      IntermediateField.adjoin (constantsSubfield F)
        {IntermediateField.AdjoinSimple.gen F t} := by
  letI : Differential (F⟮t⟯) := Δ.toDifferential
  letI : DifferentialAlgebra F (F⟮t⟯) := Δ.differentialAlgebra
  let e := RatFunc.algEquivOfTranscendental t ht
  let Δ₀ := transcendentalCoefficientExtension t ht
  have hΔ : Δ = Δ₀ :=
    differentialExtension_eq_transcendentalCoefficient_of_gen_eq_zero t ht Δ hgen
  apply le_antisymm
  · intro x hx
    let y := e.symm x
    have hx0 : Δ₀.deriv x = 0 := by
      rw [← hΔ]
      exact mem_constantsIntermediateField.mp hx
    have hy0 : (ratFuncExtensionOfValue (0 : RatFunc F)).deriv y = 0 := by
      change e ((ratFuncExtensionOfValue (e.symm 0)).deriv (e.symm x)) = 0 at hx0
      apply e.injective
      simpa [y] using hx0
    have hrel :
        y.denom * Differential.mapCoeffs y.num =
          y.num * Differential.mapCoeffs y.denom :=
      ratFunc_mapCoeffs_relation_of_coefficient_deriv_eq_zero y hy0
    obtain ⟨hnum, hden⟩ :=
      coeff_deriv_eq_zero_of_coprime_of_relation y.isCoprime_num_denom
        y.monic_denom hrel
    obtain ⟨u, hu⟩ := exists_constantsSubfield_polynomial_map_eq y.num hnum
    obtain ⟨v, hv⟩ := exists_constantsSubfield_polynomial_map_eq y.denom hden
    apply (IntermediateField.mem_adjoin_simple_iff
      (constantsSubfield F) x).mpr
    refine ⟨u, v, ?_⟩
    rw [← show e y = x by exact e.apply_symm_apply x]
    apply Subtype.ext
    rw [RatFunc.algEquivOfTranscendental_apply t ht y]
    have heval (p : (constantsSubfield F)[X]) :
        p.eval₂ ((algebraMap F E).comp (constantsSubfield F).subtype) t =
          ((p.eval₂ (algebraMap (constantsSubfield F) (F⟮t⟯))
            (IntermediateField.AdjoinSimple.gen F t) : F⟮t⟯) : E) := by
      induction p using Polynomial.induction_on' with
      | add p q hp hq =>
          rw [eval₂_add, eval₂_add, hp, hq]
          rfl
      | monomial n a =>
          rw [eval₂_monomial, eval₂_monomial]
          rfl
    have heu :
        aeval t y.num =
          ((aeval (IntermediateField.AdjoinSimple.gen F t) u : F⟮t⟯) : E) := by
      rw [← hu, Polynomial.aeval_def, Polynomial.aeval_def,
        Polynomial.eval₂_map]
      exact heval u
    have hev :
        aeval t y.denom =
          ((aeval (IntermediateField.AdjoinSimple.gen F t) v : F⟮t⟯) : E) := by
      rw [← hv, Polynomial.aeval_def, Polynomial.aeval_def,
        Polynomial.eval₂_map]
      exact heval v
    rw [heu, hev]
    rfl
  · apply IntermediateField.adjoin_le_iff.mpr
    intro x hx
    rw [Set.mem_singleton_iff] at hx
    subst x
    exact mem_constantsIntermediateField.mpr hgen

/-- The constants of `F⟮t⟯` equal `Const(F)⟮t⟯` whenever the generator has derivative zero. -/
theorem constantsIntermediateField_adjoin_eq_adjoin_constants_of_gen_deriv_eq_zero
    {F E : Type*} [Field F] [Field E] [Algebra F E] [Differential F]
    (t : E) (Δ : DifferentialExtension F (F⟮t⟯))
    (hgen : Δ.deriv (IntermediateField.AdjoinSimple.gen F t) = 0) :
    letI : Differential (F⟮t⟯) := Δ.toDifferential
    letI : DifferentialAlgebra F (F⟮t⟯) := Δ.differentialAlgebra
    constantsIntermediateField F (F⟮t⟯) =
      IntermediateField.adjoin (constantsSubfield F)
        {IntermediateField.AdjoinSimple.gen F t} := by
  classical
  by_cases ht : IsIntegral F t
  · exact constantsIntermediateField_adjoin_eq_adjoin_constants_of_isIntegral
      t ht Δ hgen
  · have ht' : Transcendental F t := fun h => ht h.isIntegral
    exact constantsIntermediateField_adjoin_eq_adjoin_constants_of_transcendental
      t ht' Δ hgen

/-- For a constant `t` in an ambient differential extension, `Const(F⟮t⟯) = Const(F)⟮t⟯`. -/
theorem constantsIntermediateField_restrictAdjoin_eq_adjoin_constants
    {F E : Type*} [Field F] [Field E] [Algebra F E] [Differential F]
    (Δ : DifferentialExtension F E) (t : E) (ht : Δ.deriv t = 0) :
    let Δt := Δ.restrictAdjoin t ht
    letI : Differential (F⟮t⟯) := Δt.toDifferential
    letI : DifferentialAlgebra F (F⟮t⟯) := Δt.differentialAlgebra
    constantsIntermediateField F (F⟮t⟯) =
      IntermediateField.adjoin (constantsSubfield F)
        {IntermediateField.AdjoinSimple.gen F t} := by
  exact constantsIntermediateField_adjoin_eq_adjoin_constants_of_gen_deriv_eq_zero
    t (Δ.restrictAdjoin t ht) (Δ.restrictAdjoin_gen_deriv_eq_zero t ht)

end DeepWiki.SymbolicIntegration
