import DeepWiki.Refine.Parametricity.Intrinsic.Core
import DeepWiki.Refine.Parametricity.Univalent.Package

/-! # Intrinsic parametricity abstraction

The base-and-arrow intrinsic calculus admits proof-relevant raw abstraction and its restriction to
relations projected from univalent packages. -/

namespace DeepWiki.Refine

universe u v

noncomputable section

/-- Proof-relevant specialization of the generic core relation fold. -/
def CoreType.proofRelevantRel {A B : Type u} (R : A → B → Type u) :
    (type : CoreType) → type.interpret A → type.interpret B → Type u
  := CoreType.foldRelation
    (Motive := fun type => type.interpret A → type.interpret B → Type u)
    R (fun _ _ domainRel codomainRel => CoreType.arrowRelation domainRel codomainRel)

/-- Proof-relevant relation environments implement the raw context-extension rule. -/
inductive CoreEnv.ProofRelevantRel {A B : Type u} (R : A → B → Type u) :
    {context : List CoreType} → CoreEnv A context → CoreEnv B context → Type u where
  /-- The two empty environments are related. -/
  | nil : CoreEnv.ProofRelevantRel R .nil .nil
  /-- A relation witness extends two already-related environments. -/
  | cons : CoreType.proofRelevantRel R type left right →
      CoreEnv.ProofRelevantRel R leftEnv rightEnv →
      CoreEnv.ProofRelevantRel R (.cons left leftEnv) (.cons right rightEnv)

/-- The proof-relevant relational kernel generated by a base relation. -/
def CoreRelationalKernel.proofRelevant {A B : Type u} (R : A → B → Type u) :
    CoreRelationalKernel A B where
  relation := CoreType.proofRelevantRel R
  environment := CoreEnv.ProofRelevantRel R
  head := fun contextWitness => by
    cases contextWitness with
    | cons head _ => exact head
  tail := fun contextWitness => by
    cases contextWitness with
    | cons _ tail => exact tail
  cons := CoreEnv.ProofRelevantRel.cons
  app := fun functionWitness argumentWitness => functionWitness _ _ argumentWitness
  lam := fun bodyWitness => bodyWitness

/-- A proof-relevant relation environment contains the translated witness for every variable. -/
noncomputable def CoreEnv.ProofRelevantRel.get
    {A B : Type u} {R : A → B → Type u}
    (var : CoreVar context type) {leftEnv : CoreEnv A context} {rightEnv : CoreEnv B context}
    (contextWitness : CoreEnv.ProofRelevantRel R leftEnv rightEnv) :
    CoreType.proofRelevantRel R type (leftEnv.get var) (rightEnv.get var) :=
  (CoreRelationalKernel.proofRelevant R).get var contextWitness

/-- Proof-relevant abstraction witness for the intrinsic core calculus. -/
noncomputable def CoreTerm.proofRelevantAbstraction
    {A B : Type u} {R : A → B → Type u}
    (term : CoreTerm context type) {leftEnv : CoreEnv A context} {rightEnv : CoreEnv B context}
    (contextWitness : CoreEnv.ProofRelevantRel R leftEnv rightEnv) :
    CoreType.proofRelevantRel R type (term.evaluate leftEnv) (term.evaluate rightEnv) :=
  term.abstractionWith (CoreRelationalKernel.proofRelevant R) contextWitness

/-- The three outputs of raw abstraction: two typed interpretations and their relation witness. -/
structure CoreTerm.RawAbstractionResult {A B : Type u} (R : A → B → Type u)
    (type : CoreType) where
  /-- Interpretation of the original term. -/
  original : type.interpret A
  /-- Interpretation of the primed term. -/
  primed : type.interpret B
  /-- The translated term relating the original and primed interpretations. -/
  translated : type.proofRelevantRel R original primed

/-- Raw abstraction packages both interpretations and the structurally generated relation witness. -/
noncomputable def CoreTerm.rawAbstractionResult
    {A B : Type u} {R : A → B → Type u}
    (term : CoreTerm context type) (leftEnv : CoreEnv A context) (rightEnv : CoreEnv B context)
    (contextWitness : CoreEnv.ProofRelevantRel R leftEnv rightEnv) :
    CoreTerm.RawAbstractionResult R type where
  original := term.evaluate leftEnv
  primed := term.evaluate rightEnv
  translated := term.proofRelevantAbstraction contextWitness

/-- Univalent abstraction theorem for the intrinsic fragment, obtained by restricting the raw
translation to the relation projected from a univalent universe package. -/
noncomputable def CoreTerm.univalentParametricity
    {A B : Type u} (package : UnivalentRelation A B)
    (term : CoreTerm context type) {leftEnv : CoreEnv A context} {rightEnv : CoreEnv B context}
    (contextWitness : CoreEnv.ProofRelevantRel package.rel leftEnv rightEnv) :
    CoreType.proofRelevantRel package.rel type (term.evaluate leftEnv) (term.evaluate rightEnv) :=
  term.proofRelevantAbstraction contextWitness

example {A : Type u} {B : Type v} {R : A → B → Prop}
    (term : CoreTerm context type) {leftEnv : CoreEnv A context} {rightEnv : CoreEnv B context}
    (contextWitness : CoreEnv.Rel R leftEnv rightEnv) :
    CoreType.rel R type (term.evaluate leftEnv) (term.evaluate rightEnv) :=
  term.abstraction contextWitness

example {A B : Type u} (package : UnivalentRelation A B)
    (term : CoreTerm context type) {leftEnv : CoreEnv A context} {rightEnv : CoreEnv B context}
    (contextWitness : CoreEnv.ProofRelevantRel package.rel leftEnv rightEnv) :
    CoreType.proofRelevantRel package.rel type (term.evaluate leftEnv) (term.evaluate rightEnv) :=
  term.univalentParametricity package contextWitness

example {A B : Type u} {R : A → B → Type u}
    (term : CoreTerm context type) (leftEnv : CoreEnv A context) (rightEnv : CoreEnv B context)
    (contextWitness : CoreEnv.ProofRelevantRel R leftEnv rightEnv) :
    CoreTerm.RawAbstractionResult R type :=
  term.rawAbstractionResult leftEnv rightEnv contextWitness

end


end DeepWiki.Refine
