import DeepWiki.SymbolicIntegration.CanonicalRepresentation.Assembly
import DeepWiki.SymbolicIntegration.CanonicalRepresentation.Classify
import DeepWiki.SymbolicIntegration.CanonicalRepresentation.NormalSqfree
import DeepWiki.SymbolicIntegration.CanonicalRepresentation.RootCharacterization
import DeepWiki.SymbolicIntegration.CanonicalRepresentation.SpecialNormalCoprime
import DeepWiki.SymbolicIntegration.CanonicalRepresentation.SplitFactor
import DeepWiki.SymbolicIntegration.CanonicalRepresentation.SplitFactorCorrect
import DeepWiki.SymbolicIntegration.CanonicalRepresentation.SplitSquarefreeFactor

/-! # The canonical representation

Aggregator for canonical-representation predicates, split-factor algorithms, and
the final rational-function assembly.
-/
