import DeepWiki.SymbolicIntegration.ComputableFiniteFieldFactor

/-! # Computable Hensel factor-lift: one quadratic Newton step (mod `p^m` → mod `p^{2m}`)

The layer **between** `𝔽_p` factorization (`ComputableFiniteFieldFactor`: `ddf`/`edf` with the
multiply-back invariants `ddf_prod`/`edf_prod`) and recombination in full **Zassenhaus** — the
campaign for a *complete* `ℚ`-irreducibility decider. The wall is `x⁴ + 1`: irreducible over `ℚ`
yet reducible mod **every** prime, so a mod-`p` *test* cannot decide it; one must factor `f mod p`,
**Hensel-lift** that coprime factorization to mod `p^k`, then recombine to `ℤ`-factors.

**★ Mathlib status.** `hensels_lemma` (`Mathlib/NumberTheory/Padics/Hensel.lean`) and
`Mathlib/RingTheory/Henselian.lean` are **root-finding** only — lifting a *single root* of `f`. The
polynomial **factor**-lift (the Zassenhaus quadratic lift of a *coprime factorization*
`f ≡ g·h`) is **not present** and is built here.

**The quadratic (Newton) step.** Given list-polys `f, g, h, s, t` over `ℤ` with
`f ≡ g·h (mod p^m)` and the Bézout relation `s·g + t·h ≡ 1 (mod p^m)`, set the **defect**
`e := f − g·h` and lift
`g' := g + t·e`,  `h' := h + s·e`   (then reduced mod `p^{2m}` to keep coefficients small).
The new defect collapses quadratically:
```
f − g'·h' = f − (g + t·e)(h + s·e)
          = (f − g·h) − (s·g + t·h)·e − s·t·e²
          = e·(1 − (s·g + t·h)) − s·t·e².
```
Since `e ≡ 0 (mod p^m)` and `1 − (s·g + t·h) ≡ 0 (mod p^m)`, the **first term** is `≡ 0 (mod p^{2m})`;
and `s·t·e²` is `≡ 0 (mod p^{2m})` because `e² ≡ 0 (mod p^{2m})`. Hence
`f ≡ g'·h' (mod p^{2m})` — **quadratic convergence**, the milestone of this file.

**Carrier.** `List ℤ` (low-to-high coefficient lists, the same Horner convention as the factor
engine), congruence phrased at the `ℤ[X]` level as **`C (n : ℤ) ∣ (a − b)`** — an ideal
congruence (`polyCongr`), hence additive, multiplicative, transitive, reflexive. This is the
cleanest setting for the Newton identity (it is an honest polynomial identity over `ℤ`, with the
two divisibilities fed in as hypotheses) and keeps the soundness **axiom-clean**
`[propext, Classical.choice, Quot.sound]` — no `native`, no `sorry`. The computational
`reduceModN` (entrywise `Int.emod`) keeps the lifted coefficient lists small for `native_decide`,
and is congruent to the un-reduced lift, so it inherits the same soundness.

**Built here** (single step): the lift data `liftStep`, the defect `defectL`, the congruence
algebra (`polyCongr` reflexive/symmetric-difference/additive/multiplicative/`sub`/`mul`), the
**★ multiply-back soundness `liftStep_congr`** (`f ≡ g'·h' (mod p^{2m})`, axiom-clean), and a
`native_decide` example lifting `x² + 1` mod `7` to mod `49`. **Roadmap (bottom):** Bézout
cofactor lift, the full iteration `p → p² → p⁴ → …`, and recombination. -/

open Polynomial

namespace DeepWiki.SymbolicIntegration

/-! ## Congruence of `ℤ`-polynomials modulo `n`

`polyCongr n a b` is `C (n : ℤ) ∣ (a − b)` on `ℤ[X]` — the congruence in the ideal `(n)`. It is an
equivalence congruent with `+`, `−`, `*` (an ideal quotient), exactly the structure the Newton
identity is read through. We only need reflexivity, the difference characterization, additivity,
and (one-sided) multiplicativity. -/

/-- `a ≡ b (mod n)` at the polynomial level: `C (n : ℤ)` divides `a − b`. The congruence in the
ideal generated by the constant `n`. -/
def polyCongr (n : ℕ) (a b : ℤ[X]) : Prop := (C (n : ℤ)) ∣ (a - b)

/-- `polyCongr n a a`: every polynomial is congruent to itself. -/
theorem polyCongr_refl (n : ℕ) (a : ℤ[X]) : polyCongr n a a := by
  simp [polyCongr]

/-- `polyCongr n a b` iff `C n ∣ (a − b)` — definitional, exposed for rewriting. -/
theorem polyCongr_iff (n : ℕ) (a b : ℤ[X]) : polyCongr n a b ↔ (C (n : ℤ)) ∣ (a - b) := Iff.rfl

/-- A congruence from an explicit witness: `a − b = C n * k → a ≡ b (mod n)`. -/
theorem polyCongr_of_eq (n : ℕ) {a b : ℤ[X]} (k : ℤ[X]) (h : a - b = C (n : ℤ) * k) :
    polyCongr n a b := ⟨k, h⟩

/-- Symmetry: `a ≡ b → b ≡ a`. -/
theorem polyCongr_symm {n : ℕ} {a b : ℤ[X]} (h : polyCongr n a b) : polyCongr n b a := by
  rw [polyCongr] at h ⊢
  rcases h with ⟨k, hk⟩
  exact ⟨-k, by rw [mul_neg, ← hk]; ring⟩

/-- Transitivity: `a ≡ b → b ≡ c → a ≡ c`. -/
theorem polyCongr_trans {n : ℕ} {a b c : ℤ[X]} (hab : polyCongr n a b) (hbc : polyCongr n b c) :
    polyCongr n a c := by
  rw [polyCongr] at hab hbc ⊢
  have : a - c = (a - b) + (b - c) := by ring
  rw [this]; exact dvd_add hab hbc

/-! ## Divisibility by `C (p^m)` squares into `C (p^{2m})`

The numeric core of quadratic convergence: a product of two quantities each `≡ 0 (mod p^m)` is
`≡ 0 (mod p^{2m})`, because `C (p^m) * C (p^m) = C (p^{2m})`. -/

/-- `C (p^m) * C (p^m) = C (p^{2m})` (so the squared modulus appears from two `mod p^m` factors). -/
theorem C_pow_mul_C_pow (p m : ℕ) :
    (C ((p ^ m : ℕ) : ℤ)) * (C ((p ^ m : ℕ) : ℤ)) = C ((p ^ (2 * m) : ℕ) : ℤ) := by
  rw [← C_mul]
  congr 1
  push_cast
  rw [two_mul, pow_add]

/-- **★ The quadratic-convergence multiplicativity.** If `C (p^m) ∣ u` and `C (p^m) ∣ v` then
`C (p^{2m}) ∣ (u * v)`: a product of two `mod p^m`-small quantities is `mod p^{2m}`-small. -/
theorem C_pow_two_mul_dvd_mul {p m : ℕ} {u v : ℤ[X]}
    (hu : (C ((p ^ m : ℕ) : ℤ)) ∣ u) (hv : (C ((p ^ m : ℕ) : ℤ)) ∣ v) :
    (C ((p ^ (2 * m) : ℕ) : ℤ)) ∣ (u * v) := by
  rcases hu with ⟨a, ha⟩
  rcases hv with ⟨b, bk⟩
  refine ⟨a * b, ?_⟩
  rw [ha, bk, ← C_pow_mul_C_pow]; ring

/-! ## The lifting-step data (computable, over `List ℤ`)

The defect `e = f − g·h` and the lifted factors `g' = g + t·e`, `h' = h + s·e`, all on
coefficient lists via the engine `subL`/`addL`/`mulL`. `reduceModN n` reduces every coefficient
mod `n` (entrywise `Int.emod`) to keep the lifted lists small for `native_decide`; it is congruent
to the identity mod `n`, so soundness is unaffected. `liftStep` packages `(g', h')` with the
reduction applied at modulus `p^{2m}`. -/

/-- The **defect** `f − g·h` of a (mod-`p^m`) factorization, as a coefficient list. Its `toPoly` is
`toPolyZ f − toPolyZ g * toPolyZ h`. -/
def defectL (f g h : List ℤ) : List ℤ := subL f (mulL g h)

/-- `toPoly (defectL f g h) = toPolyZ f − toPolyZ g * toPolyZ h`. -/
theorem toPoly_defectL (f g h : List ℤ) :
    toPoly (defectL f g h) = toPolyZ f - toPolyZ g * toPolyZ h := by
  rw [defectL, toPoly_subL, toPoly_mulL, toPolyZ, toPolyZ, toPolyZ]

/-- Reduce every coefficient mod `n` (entrywise `Int.emod`, into `[0, n)`): a small-coefficient
representative, congruent to the input mod `n`. -/
def reduceModN (n : ℕ) (l : List ℤ) : List ℤ := l.map (fun a => a % (n : ℤ))

/-- Each reduced coefficient differs from the original by a multiple of `n`:
`a − a % n = n * (a / n)` (the `Int.emod_add_mul_ediv` decomposition). -/
theorem reduceModN_congr_coeff (n : ℕ) (a : ℤ) : a - a % (n : ℤ) = (n : ℤ) * (a / (n : ℤ)) := by
  have := Int.mul_ediv_add_emod a (n : ℤ)
  linarith [this]

/-- **`reduceModN` is congruent to the identity mod `n`.** `toPoly (reduceModN n l) ≡ toPoly l
(mod n)`: reducing coefficients changes the polynomial only by a multiple of `C n`. By induction on
`l`, each coefficient differing by `n * (a / n)`. -/
theorem polyCongr_toPoly_reduceModN (n : ℕ) (l : List ℤ) :
    polyCongr n (toPoly (reduceModN n l)) (toPoly l) := by
  induction l with
  | nil => simp [reduceModN]; exact polyCongr_refl n 0
  | cons a as ih =>
    rw [reduceModN, List.map_cons, toPoly_cons, toPoly_cons, ← reduceModN]
    rcases ih with ⟨k, hk⟩
    refine ⟨-C (a / (n : ℤ)) + X * k, ?_⟩
    have hcoeff : C (a % (n : ℤ)) - C a = -(C (n : ℤ) * C (a / (n : ℤ))) := by
      rw [← C_mul, ← C_neg, ← C_sub]
      congr 1
      have := reduceModN_congr_coeff n a
      linarith [this]
    rw [show (C (a % (n : ℤ)) + X * toPoly (reduceModN n as))
          - (C a + X * toPoly as)
        = (C (a % (n : ℤ)) - C a) + X * (toPoly (reduceModN n as) - toPoly as) by ring,
      hcoeff, hk]
    ring

/-- **The quadratic lifting step.** From `f, g, h, s, t` (list-polys with `f ≡ g·h` and
`s·g + t·h ≡ 1` mod `p^m`), compute `(g', h')` mod `p^{2m}` with `g' = g + t·e`, `h' = h + s·e`
(`e = f − g·h`), each reduced mod `p^{2m}`. Computable; `native_decide`-able. -/
def liftStep (p m : ℕ) (f g h s t : List ℤ) : List ℤ × List ℤ :=
  let e := defectL f g h
  let n2 := p ^ (2 * m)
  (reduceModN n2 (addL g (mulL t e)), reduceModN n2 (addL h (mulL s e)))

/-! ## ★ Multiply-back soundness of one step (the milestone)

The Newton quadratic-convergence identity, read through the congruence algebra. With
`e = f − g·h`, `g₀ = g + t·e`, `h₀ = h + s·e` (the *un-reduced* lift),
```
f − g₀·h₀ = e·(1 − (s·g + t·h)) − s·t·e².
```
`e ≡ 0 (mod p^m)` (defect hypothesis) and `1 − (s·g + t·h) ≡ 0 (mod p^m)` (Bézout hypothesis) make
the first product `≡ 0 (mod p^{2m})` by `C_pow_two_mul_dvd_mul`; `s·t·e²` is `≡ 0 (mod p^{2m})`
since `e² ≡ 0`. So `f ≡ g₀·h₀ (mod p^{2m})`. Reducing `g₀, h₀` mod `p^{2m}` (the actual
`liftStep` output) only adds further `C (p^{2m})`-multiples, so `f ≡ g'·h' (mod p^{2m})`. -/

/-- The exact polynomial **Newton identity** over `ℤ`: with `e := F − G*H`,
`(G + T*e)*(H + S*e) = F − (e*(1 − (S*G + T*H)) − S*T*e²)`. A `ring` identity, the algebraic heart
of quadratic convergence (no hypotheses; the divisibilities are applied to its two summands). -/
theorem newton_identity (F G H S T : ℤ[X]) :
    let e := F - G * H
    F - (G + T * e) * (H + S * e)
      = e * (1 - (S * G + T * H)) - S * T * (e * e) := by
  intro e
  show F - (G + T * (F - G * H)) * (H + S * (F - G * H))
      = (F - G * H) * (1 - (S * G + T * H)) - S * T * ((F - G * H) * (F - G * H))
  ring

/-- **★ Un-reduced multiply-back.** With `e := toPolyZ f − toPolyZ g * toPolyZ h`,
`toPolyZ f ≡ (toPolyZ g + toPolyZ t * e) * (toPolyZ h + toPolyZ s * e) (mod p^{2m})`, given the
defect congruence `f ≡ g·h (mod p^m)` and Bézout `s·g + t·h ≡ 1 (mod p^m)`. The pure Newton step;
`liftStep_congr` adds the coefficient reduction. -/
theorem liftStepRaw_congr (p m : ℕ) (f g h s t : List ℤ)
    (hdef : polyCongr (p ^ m) (toPolyZ f) (toPolyZ g * toPolyZ h))
    (hbez : polyCongr (p ^ m) (toPolyZ s * toPolyZ g + toPolyZ t * toPolyZ h) 1) :
    polyCongr (p ^ (2 * m)) (toPolyZ f)
      ((toPolyZ g + toPolyZ t * (toPolyZ f - toPolyZ g * toPolyZ h)) *
        (toPolyZ h + toPolyZ s * (toPolyZ f - toPolyZ g * toPolyZ h))) := by
  set F := toPolyZ f
  set G := toPolyZ g
  set H := toPolyZ h
  set S := toPolyZ s
  set T := toPolyZ t
  set e := F - G * H with hedef
  -- e ≡ 0 (mod p^m): C (p^m) ∣ e
  have he : (C ((p ^ m : ℕ) : ℤ)) ∣ e := by
    rcases hdef with ⟨k, hk⟩; exact ⟨k, by rw [hedef, hk]⟩
  -- 1 − (S*G + T*H) ≡ 0 (mod p^m)
  have hb : (C ((p ^ m : ℕ) : ℤ)) ∣ (1 - (S * G + T * H)) := by
    rcases hbez with ⟨k, hk⟩; exact ⟨-k, by rw [mul_neg, ← hk]; ring⟩
  -- the two summands of the Newton residue are each divisible by C (p^{2m})
  have h1 : (C ((p ^ (2 * m) : ℕ) : ℤ)) ∣ (e * (1 - (S * G + T * H))) :=
    C_pow_two_mul_dvd_mul he hb
  have h2 : (C ((p ^ (2 * m) : ℕ) : ℤ)) ∣ (S * T * (e * e)) := by
    have hee : (C ((p ^ (2 * m) : ℕ) : ℤ)) ∣ (e * e) := C_pow_two_mul_dvd_mul he he
    exact Dvd.dvd.mul_left hee (S * T)
  -- f − g'·h' = first − second, divisible by C (p^{2m})
  rw [polyCongr]
  have hid := newton_identity F G H S T
  simp only at hid
  rw [hid]
  exact dvd_sub h1 h2

/-- **★★ Multiply-back soundness of one Hensel step (THE milestone).** Let
`(g', h') = liftStep p m f g h s t`. Given `f ≡ g·h (mod p^m)` and `s·g + t·h ≡ 1 (mod p^m)`, the
lifted factors multiply back mod `p^{2m}`:
`toPolyZ f ≡ toPolyZ g' * toPolyZ h' (mod p^{2m})` — i.e. the new defect `f − g'·h'` vanishes mod
`p^{2m}`. Axiom-clean `[propext, Classical.choice, Quot.sound]`. The Newton quadratic step: the raw
lift `liftStepRaw_congr` plus the `reduceModN` congruence on each factor. -/
theorem liftStep_congr (p m : ℕ) (f g h s t : List ℤ)
    (hdef : polyCongr (p ^ m) (toPolyZ f) (toPolyZ g * toPolyZ h))
    (hbez : polyCongr (p ^ m) (toPolyZ s * toPolyZ g + toPolyZ t * toPolyZ h) 1) :
    polyCongr (p ^ (2 * m)) (toPolyZ f)
      (toPolyZ (liftStep p m f g h s t).1 * toPolyZ (liftStep p m f g h s t).2) := by
  -- abbreviations for the raw (un-reduced) lifted factors
  set e := defectL f g h with hedef
  set g0 := addL g (mulL t e) with hg0def
  set h0 := addL h (mulL s e) with hh0def
  -- the reduced factors are the liftStep output
  have hfst : (liftStep p m f g h s t).1 = reduceModN (p ^ (2 * m)) g0 := rfl
  have hsnd : (liftStep p m f g h s t).2 = reduceModN (p ^ (2 * m)) h0 := rfl
  rw [hfst, hsnd]
  -- step 1: toPolyZ g' ≡ toPolyZ g0, toPolyZ h' ≡ toPolyZ h0 (mod p^{2m})
  have hcg : polyCongr (p ^ (2 * m)) (toPoly (reduceModN (p ^ (2 * m)) g0)) (toPoly g0) :=
    polyCongr_toPoly_reduceModN _ _
  have hch : polyCongr (p ^ (2 * m)) (toPoly (reduceModN (p ^ (2 * m)) h0)) (toPoly h0) :=
    polyCongr_toPoly_reduceModN _ _
  -- toPoly g0 = toPoly g + toPoly t * (toPoly f − toPoly g * toPoly h)  (toPolyZ = toPoly defeq)
  have hg0poly : toPoly g0 = toPoly g + toPoly t * (toPoly f - toPoly g * toPoly h) := by
    rw [hg0def, toPoly_addL, toPoly_mulL, hedef, toPoly_defectL, toPolyZ, toPolyZ, toPolyZ]
  have hh0poly : toPoly h0 = toPoly h + toPoly s * (toPoly f - toPoly g * toPoly h) := by
    rw [hh0def, toPoly_addL, toPoly_mulL, hedef, toPoly_defectL, toPolyZ, toPolyZ, toPolyZ]
  -- the product of the reduced factors ≡ the product of g0,h0 (mod p^{2m})
  have hprod : polyCongr (p ^ (2 * m))
      (toPoly (reduceModN (p ^ (2 * m)) g0) * toPoly (reduceModN (p ^ (2 * m)) h0))
      (toPoly g0 * toPoly h0) := by
    -- g'h' − g0h0 = (g' − g0) h' + g0 (h' − h0)
    rcases hcg with ⟨kg, hkg⟩
    rcases hch with ⟨kh, hkh⟩
    refine ⟨kg * toPoly (reduceModN (p ^ (2 * m)) h0) + toPoly g0 * kh, ?_⟩
    have hexpand :
        toPoly (reduceModN (p ^ (2 * m)) g0) * toPoly (reduceModN (p ^ (2 * m)) h0)
          - toPoly g0 * toPoly h0
        = (toPoly (reduceModN (p ^ (2 * m)) g0) - toPoly g0)
            * toPoly (reduceModN (p ^ (2 * m)) h0)
          + toPoly g0 * (toPoly (reduceModN (p ^ (2 * m)) h0) - toPoly h0) := by ring
    rw [hexpand, hkg, hkh]; ring
  -- the raw multiply-back (mod p^{2m}); `toPolyZ` unfolds to `toPoly` (defeq)
  have hraw := liftStepRaw_congr p m f g h s t hdef hbez
  simp only [toPolyZ] at hraw ⊢
  rw [← hg0poly, ← hh0poly] at hraw
  -- chain: f ≡ g0·h0 ≡ g'·h'
  exact polyCongr_trans hraw (polyCongr_symm hprod)

/-! ## Lifting the Bézout cofactors (to iterate)

To **iterate** the Hensel step the cofactors `s, t` must lift alongside the factors. With the
*lifted* factors `g', h'` and the **Bézout defect** `b := s·g' + t·h' − 1` (`≡ 0 (mod p^m)`, since
`g' ≡ g`, `h' ≡ h (mod p^m)`), set
`s' := s − s·b`,  `t' := t − t·b`   (reduced mod `p^{2m}`).
Then
```
s'·g' + t'·h' = (s·g' + t·h') − b·(s·g' + t·h') = (1 + b) − b·(1 + b) = 1 − b².
```
As `b ≡ 0 (mod p^m)`, `b² ≡ 0 (mod p^{2m})`, so `s'·g' + t'·h' ≡ 1 (mod p^{2m})` — the Bézout
relation lifts. Soundness `liftBezout_congr` is proven against the *raw* `(s', t')` (the
coefficient reduction is congruent, cf. `liftStep`); the computable `liftBezout` applies
`reduceModN`. -/

/-- The **Bézout defect** of cofactors `s, t` for factors `gp, hp`: `s·gp + t·hp − 1`, as a
coefficient list. Its `toPoly` is `toPolyZ s * toPolyZ gp + toPolyZ t * toPolyZ hp − 1`. -/
def bezoutDefectL (s t gp hp : List ℤ) : List ℤ :=
  subL (addL (mulL s gp) (mulL t hp)) [1]

/-- `toPoly (bezoutDefectL s t gp hp) = toPolyZ s * toPolyZ gp + toPolyZ t * toPolyZ hp − 1`. -/
theorem toPoly_bezoutDefectL (s t gp hp : List ℤ) :
    toPoly (bezoutDefectL s t gp hp)
      = toPolyZ s * toPolyZ gp + toPolyZ t * toPolyZ hp - 1 := by
  rw [bezoutDefectL, toPoly_subL, toPoly_addL, toPoly_mulL, toPoly_mulL, toPolyZ, toPolyZ, toPolyZ,
    toPolyZ]
  simp [toPoly]

/-- **Lift the Bézout cofactors** for the lifted factors `gp, hp`: with `b := s·gp + t·hp − 1`,
`s' := s − s·b`, `t' := t − t·b`, each reduced mod `p^{2m}`. Computable. -/
def liftBezout (p m : ℕ) (s t gp hp : List ℤ) : List ℤ × List ℤ :=
  let b := bezoutDefectL s t gp hp
  let n2 := p ^ (2 * m)
  (reduceModN n2 (subL s (mulL s b)), reduceModN n2 (subL t (mulL t b)))

/-- **★ Raw Bézout-cofactor lift soundness.** With `b := S·Gp + T·Hp − 1`, the raw lifted
cofactors `S − S·b`, `T − T·b` satisfy `(S − S·b)·Gp + (T − T·b)·Hp ≡ 1 (mod p^{2m})`, given the
Bézout defect congruence `S·Gp + T·Hp ≡ 1 (mod p^m)`. The identity is `1 − b²` with `b² ≡ 0`. -/
theorem liftBezoutRaw_congr (p m : ℕ) (s t gp hp : List ℤ)
    (hbdef : polyCongr (p ^ m) (toPolyZ s * toPolyZ gp + toPolyZ t * toPolyZ hp) 1) :
    polyCongr (p ^ (2 * m))
      ((toPolyZ s - toPolyZ s * (toPolyZ s * toPolyZ gp + toPolyZ t * toPolyZ hp - 1)) * toPolyZ gp
        + (toPolyZ t - toPolyZ t * (toPolyZ s * toPolyZ gp + toPolyZ t * toPolyZ hp - 1))
            * toPolyZ hp)
      1 := by
  set S := toPolyZ s
  set T := toPolyZ t
  set Gp := toPolyZ gp
  set Hp := toPolyZ hp
  set b := S * Gp + T * Hp - 1 with hbdef'
  -- b ≡ 0 (mod p^m)
  have hb : (C ((p ^ m : ℕ) : ℤ)) ∣ b := by
    rcases hbdef with ⟨k, hk⟩; exact ⟨k, by rw [hbdef', hk]⟩
  -- b² ≡ 0 (mod p^{2m})
  have hbb : (C ((p ^ (2 * m) : ℕ) : ℤ)) ∣ (b * b) := C_pow_two_mul_dvd_mul hb hb
  -- (S − S·b)·Gp + (T − T·b)·Hp − 1 = −b²
  rw [polyCongr]
  have hid : ((S - S * b) * Gp + (T - T * b) * Hp) - 1 = -(b * b) := by
    show ((S - S * b) * Gp + (T - T * b) * Hp) - 1 = -((S * Gp + T * Hp - 1) * (S * Gp + T * Hp - 1))
    ring
  rw [hid]
  exact (dvd_neg).2 hbb

/-- **★ Bézout-cofactor lift soundness (iteration enabler).** Let
`(s', t') = liftBezout p m s t gp hp`. Given `s·gp + t·hp ≡ 1 (mod p^m)`, the lifted cofactors keep
Bézout mod `p^{2m}`: `toPolyZ s' * toPolyZ gp + toPolyZ t' * toPolyZ hp ≡ 1 (mod p^{2m})`. The raw
lift `liftBezoutRaw_congr` plus the `reduceModN` congruence on `s', t'`. Needed to iterate Hensel.
Axiom-clean. -/
theorem liftBezout_congr (p m : ℕ) (s t gp hp : List ℤ)
    (hbdef : polyCongr (p ^ m) (toPolyZ s * toPolyZ gp + toPolyZ t * toPolyZ hp) 1) :
    polyCongr (p ^ (2 * m))
      (toPolyZ (liftBezout p m s t gp hp).1 * toPolyZ gp
        + toPolyZ (liftBezout p m s t gp hp).2 * toPolyZ hp)
      1 := by
  set b := bezoutDefectL s t gp hp with hbdef0
  set s0 := subL s (mulL s b) with hs0def
  set t0 := subL t (mulL t b) with ht0def
  have hfst : (liftBezout p m s t gp hp).1 = reduceModN (p ^ (2 * m)) s0 := rfl
  have hsnd : (liftBezout p m s t gp hp).2 = reduceModN (p ^ (2 * m)) t0 := rfl
  rw [hfst, hsnd]
  -- `toPolyZ` unfolds to `toPoly` (defeq); normalize the goal
  simp only [toPolyZ]
  -- reduced cofactors are congruent to the raw ones (mod p^{2m})
  have hcs : polyCongr (p ^ (2 * m)) (toPoly (reduceModN (p ^ (2 * m)) s0)) (toPoly s0) :=
    polyCongr_toPoly_reduceModN _ _
  have hct : polyCongr (p ^ (2 * m)) (toPoly (reduceModN (p ^ (2 * m)) t0)) (toPoly t0) :=
    polyCongr_toPoly_reduceModN _ _
  -- raw cofactors as polynomials (in `toPoly` form throughout)
  have hs0poly : toPoly s0
      = toPoly s - toPoly s * (toPoly s * toPoly gp + toPoly t * toPoly hp - 1) := by
    rw [hs0def, toPoly_subL, toPoly_mulL, hbdef0, toPoly_bezoutDefectL, toPolyZ, toPolyZ, toPolyZ,
      toPolyZ]
  have ht0poly : toPoly t0
      = toPoly t - toPoly t * (toPoly s * toPoly gp + toPoly t * toPoly hp - 1) := by
    rw [ht0def, toPoly_subL, toPoly_mulL, hbdef0, toPoly_bezoutDefectL, toPolyZ, toPolyZ, toPolyZ,
      toPolyZ]
  -- the Bézout combination with reduced cofactors ≡ that with raw cofactors (mod p^{2m})
  have hcomb : polyCongr (p ^ (2 * m))
      (toPoly (reduceModN (p ^ (2 * m)) s0) * toPoly gp
        + toPoly (reduceModN (p ^ (2 * m)) t0) * toPoly hp)
      (toPoly s0 * toPoly gp + toPoly t0 * toPoly hp) := by
    rcases hcs with ⟨ks, hks⟩
    rcases hct with ⟨kt, hkt⟩
    refine ⟨ks * toPoly gp + kt * toPoly hp, ?_⟩
    have hexpand :
        (toPoly (reduceModN (p ^ (2 * m)) s0) * toPoly gp
          + toPoly (reduceModN (p ^ (2 * m)) t0) * toPoly hp)
          - (toPoly s0 * toPoly gp + toPoly t0 * toPoly hp)
        = (toPoly (reduceModN (p ^ (2 * m)) s0) - toPoly s0) * toPoly gp
          + (toPoly (reduceModN (p ^ (2 * m)) t0) - toPoly t0) * toPoly hp := by ring
    rw [hexpand, hks, hkt]; ring
  -- raw soundness
  have hraw := liftBezoutRaw_congr p m s t gp hp hbdef
  simp only [toPolyZ] at hraw
  rw [← hs0poly, ← ht0poly] at hraw
  -- chain: combination(reduced) ≡ combination(raw) ≡ 1
  exact polyCongr_trans hcomb hraw

/-! ## `native_decide` validation of one lifting step

The concrete computational content behind `liftStep_congr`: lift `x² + 1` over `ℤ` from its
mod-`5` factorization `(x + 3)(x + 2) = x² + 5x + 6 ≡ x² + 1 (mod 5)` one quadratic step to mod
`5² = 25`, and verify the lifted factors multiply back mod `25`. Bézout: `1·(x + 3) + (−1)·(x + 2)
= 1`, so `s = [1]`, `t = [−1]`. (`toPoly` is `noncomputable`, so — as in the factor engine — we
validate the list-level `mulL`/`reduceModN` output, which `toPoly` sends to the polynomial
congruence `liftStep_congr` proves.) -/

/-- The mod-`5` defect of `x² + 1 = (x + 3)(x + 2)` is `−5x − 5 ≡ 0 (mod 5)`: the factorization is
exact mod `5` (`native_decide`). -/
example : reduceModN 5 (defectL [1, 0, 1] [3, 1] [2, 1]) = [0, 0, 0] := by native_decide

/-- The Bézout relation `1·(x + 3) + (−1)·(x + 2) = 1` holds (`s·g + t·h − 1 ≡ 0`, list-level)
(`native_decide`). -/
example : subL (addL (mulL [1] [3, 1]) (mulL [-1] [2, 1])) [1] = [0, 0] := by native_decide

/-- One quadratic Hensel step lifts `(x + 3, x + 2)` to `(6x + 8, 21x + 22)` mod `25`
(`native_decide`). -/
example : liftStep 5 1 [1, 0, 1] [3, 1] [2, 1] [1] [-1] = ([8, 6, 0], [22, 21, 0]) := by
  native_decide

/-- **★ Multiply-back mod `25`.** The lifted factors `(6x + 8)(21x + 22)` reduce mod `25` to
`x² + 1` (the input, with benign trailing zeros from un-trimmed lists; `toPoly` agrees, the
content of `liftStep_congr`) — the new defect vanishes mod `25` (`native_decide`). -/
example :
    (let (g', h') := liftStep 5 1 [1, 0, 1] [3, 1] [2, 1] [1] [-1];
      reduceModN 25 (mulL g' h')) = [1, 0, 1, 0, 0] := by native_decide

/-- The new defect `f − g'·h'` is `≡ 0 (mod 25)` after one step: quadratic convergence from `mod 5`
to `mod 25` (`native_decide`). -/
example :
    (let (g', h') := liftStep 5 1 [1, 0, 1] [3, 1] [2, 1] [1] [-1];
      reduceModN 25 (defectL [1, 0, 1] g' h')) = [0, 0, 0, 0, 0] := by native_decide

/-- **★ Bézout cofactor lift mod `25`.** Lifting the cofactors `s = 1, t = −1` for the lifted
factors `(6x + 8, 21x + 22)` gives `(15x + 16, 10x + 9)` mod `25`, keeping the Bézout relation
`s'·g' + t'·h' ≡ 1 (mod 25)` (the lifted defect vanishes mod `25`; cf. `liftBezout_congr`) — so the
step is ready to iterate (`native_decide`). -/
example :
    (let (s', t') := liftBezout 5 1 [1] [-1] [8, 6, 0] [22, 21, 0];
      reduceModN 25 (bezoutDefectL s' t' [8, 6, 0] [22, 21, 0])) = [0, 0, 0, 0, 0] := by
  native_decide

/-! ## Roadmap: from one step to the complete `ℚ`-irreducibility decider

What this file builds, and what remains for full Zassenhaus.

**★ Built here (one quadratic step, axiom-clean).**
* `liftStep` / `liftStep_congr` — the factor lift `g, h (mod p^m) ↦ g', h' (mod p^{2m})` with
  `f ≡ g'·h' (mod p^{2m})` (the Newton quadratic identity).
* `liftBezout` / `liftBezout_congr` — the cofactor lift `s, t (mod p^m) ↦ s', t' (mod p^{2m})`
  with `s'·g' + t'·h' ≡ 1 (mod p^{2m})`, so the data needed for the *next* step is regenerated:
  a single iteration `(f, g, h, s, t) ↦ (f, g', h', s', t')` over `mod p^m → mod p^{2m}` is
  **complete and sound**.
* `polyCongr` congruence algebra + `reduceModN` (coefficient control) + `native_decide`
  validation (`x² + 1`, `mod 5 → mod 25`).

**Remaining — the full iteration `mod p → p² → p⁴ → … → p^k`.**
Iterate the single step `⌈log₂ k⌉` times, doubling the modulus exponent each round
(`m ↦ 2m`), starting from a coprime mod-`p` factorization (`ddf`/`edf` from
`ComputableFiniteFieldFactor`, lifted to `List ℤ` by choosing representatives in `[0, p)`, with
the mod-`p` Bézout cofactors from the extended Euclidean algorithm). The termination target is
`p^k > 2 · B`, where `B` is the **Mignotte bound** on the coefficients of any factor of `f`
(`B = (deg f choose ⌊deg f / 2⌋) · ‖f‖₂ · lc(f)`, roughly), so every true `ℤ`-factor has a unique
representative in the symmetric range `(−p^k/2, p^k/2]`. Engineering: a recursion folding
`liftStep`/`liftBezout` over the doubling schedule, with the multiply-back/Bézout invariants
threaded through (each round is `liftStep_congr` ∘ `liftBezout_congr`). The two-factor step here
generalizes to `r` factors by the standard **multifactor** lift (lift `g` against the product of
the rest, recursively), or by repeatedly applying the two-factor step on a balanced split.

**Remaining — recombination to `ℤ`-factors (the last Zassenhaus stage).**
Given the lifted irreducible factors `g₁, …, gᵣ (mod p^k)`, the true `ℤ`-factors are products of
**subsets** of the `gᵢ` whose coefficients (taken in the symmetric range) are bounded by the
Mignotte bound and which **actually divide** `f` over `ℤ`. Search subsets in increasing size; each
candidate is `∏_{i ∈ S} gᵢ (mod p^k)`, symmetric-range-reduced, tested by trial division of `f`
in `ℤ[X]`. *Mathlib status:* **not present**; an exponential subset search (LLL tames it later).
The correctness predicate (a subset product divides `f` over `ℤ` and is irreducible) then yields:
`f` is `ℚ`-irreducible iff recombination returns a single factor — the **complete decider** that
`ComputablePolynomialIrreducibility`'s one-way mod-`p` test (the `x⁴ + 1` wall) cannot give.

**The campaign.** `ddf` + `edf` (factor mod `p`, `ComputableFiniteFieldFactor`) → **Hensel
factor-lift (this file)** → multifactor iteration to `mod p^k` → recombination → complete
`ℚ`-irreducibility decider. The single quadratic step with its multiply-back and Bézout soundness
is the Mathlib-lacking brick this file contributes. -/

end DeepWiki.SymbolicIntegration
