import DeepWiki.SymbolicIntegration.ComputableIntegralBasisFull
import DeepWiki.SymbolicIntegration.ComputableGeneralLogArg
import DeepWiki.SymbolicIntegration.ComputableQFunReduce

/-! # The GENERAL divisor-class-group: divisors as fractional ideals of the order `O` (= the integral
basis), `div(g)`, and the ideal product (the Pic group law) — for an ARBITRARY plane curve
(Trager, *Integration of Algebraic Functions*, Ch. 5 §3 "Constructing Divisors", Ch. 6 "Principal Divisors
and Points of Finite Order")

`ComputableHyperellipticDivisor` carries the **Mumford pair** `(u, v)` representation — but only for a
HYPERELLIPTIC curve `y² = ρ(x)`. This file builds the **general lift**: the representation of a divisor on
an ARBITRARY curve `K(x, y) = K(x)[y]/(f)` as a **fractional `O`-ideal**, where `O = [w₁, …, wₙ]` is the
integral basis (`integralBasis f`, the maximal order, a `K[x]`-module). This is the data structure on which
the general analogue of Cantor's composition runs.

**The math.** A (finite) divisor on `C` ↔ a fractional `O`-ideal `I ⊆ K(x, y)`. Pick a `K[x]`-module
presentation: `I` is generated by `n` elements `gen₁, …, genₙ ∈ K(x, y)`, each written in the integral-basis
coordinates `genᵢ = Σⱼ Mᵢⱼ wⱼ` with `Mᵢⱼ ∈ K(x)`. So `I` ↔ the `n×n` matrix `M` over `K(x)` (rows =
generators in `[w₁, …, wₙ]` coords) — the general analogue of the Mumford pair. The key constructions:

* **The IDENTITY** is the order `O` itself: matrix `Iₙ` (the `[w]`-coords of `w₁, …, wₙ` are the standard
  basis). `idealIdentity n`.
* **`div(g) = g·O`** (the PRINCIPAL divisor of `g ∈ K(x, y)`): the ideal generated by `g·w₁, …, g·wₙ`, so
  row `i` is the `[w]`-coords of `afMul f g wᵢ`. `principalDivisor f basis g`.
* **`I·J`** (= divisor ADDITION in `Pic`, the general analogue of Cantor's composition): the product ideal,
  generated by the `n²` cross-products `(genᵢ of I)·(genₖ of J)`, reduced from `n²` to `n` generators by
  `hermiteRowReduce` over `K[x]` (after clearing denominators). `idealProduct f basis I J`. The IDENTITY law
  `I·O = I` and the homomorphism `div(g)·div(h) = div(g·h)` (so `div : K(x, y)ˣ → Pic` is a group
  homomorphism) are the validations.
* **The order at a place** = the valuation; the divisor is **integral** iff `M` is over `K[x]` (no
  denominators) — `idealIsIntegral`.

Because `O`-ideal arithmetic mixes `K(x)` (the matrix entries) and `K[x]` (the Hermite reduction), the
canonical form for testing `I = J` clears each ideal to a common `K[x]` denominator `δ` (the rows times `δ`
become integral, `cleared ⊆ K[x]ⁿ`) and Hermite-reduces the cleared generators (`idealHNF`), comparing the
`(δ, HNF)` data. Two fractional ideals are equal iff a common-denominator clearing has the same `K[x]`-row
span (same Hermite normal form) — the decision procedure `idealEq`.

**Validations** (`native_decide`) on the GENERAL (non-hyperelliptic) curve `y³ = x²` (`gcuspCubicF`), whose
integral basis `[1, y, y²/x]` is **NOT** the power basis (the third generator carries a denominator), so the
`[w]`-coordinate conversion `B⁻¹` is genuinely exercised:
* **`div(y)` and `div(y²)`** as ideal matrices (the principal divisors of `y` and `y²`);
* **★ `div(y)·div(y) = div(y²)`** — the Pic group law / `div` homomorphism on a general curve (the general
  analogue of `div(P) + div(P) = div(2P)`);
* **`I·O = I`** — the identity law of the Pic group (`O` is the neutral element);
* **integrality** of `div(y)`, `div(y²)` (their matrices are over `K[x]`).

**The engine now represents general-curve divisors as fractional ideals over the integral basis, with
`div(g)` and the ideal product (the Pic group law).** The remaining torsion pipeline — `idealInverse` /
`idealReduce` (toward the reduced divisor), the ORDER (smallest `m` with `m·δ` principal, via repeated
`idealProduct` + an `afLogArgSolve`-style principality test), and the good-reduction bound mod `p` (the
general lift of `ComputableDivisorOrder`) — is documented at the end as the next pieces. -/

open Polynomial

namespace DeepWiki.SymbolicIntegration

namespace CPolyG

open CPolyG

/-! ### The representation: a fractional `O`-ideal as a `K(x)`-matrix in `[w]`-coordinates (`GenDivisor`)

A divisor ↔ a fractional `O`-ideal ↔ an `n×n` matrix `M` over `K(x) = QFunNZG ℚ` whose **row `i`** is the
generator `genᵢ = Σⱼ Mᵢⱼ wⱼ` in the integral-basis `[w₁, …, wₙ]` coordinates. We represent it as a plain
`List (List (QFunNZG ℚ))` (rows of `K(x)` entries) — the general-curve analogue of the Mumford pair
`(u, v)`, lifted from the hyperelliptic `y² = ρ` to an arbitrary `K(x)[y]/(f)`. -/

/-- **A general divisor as a fractional `O`-ideal** `GenDivisor`: an `n×n` matrix over `K(x) = QFunNZG ℚ`
whose row `i` is a generator `genᵢ = Σⱼ Mᵢⱼ wⱼ` in the integral-basis `[w₁, …, wₙ]` coordinates. The
general-curve analogue of `ComputableHyperellipticDivisor`'s Mumford pair, on an arbitrary `K(x)[y]/(f)`.
A `List (List (QFunNZG ℚ))`. -/
abbrev GenDivisor := List (List (QFunNZG ℚ))

/-- **The identity divisor `O`** `idealIdentity n = Iₙ` — the order itself, the neutral element of the Pic
group: row `i` is the standard basis vector `eᵢ` (the `[w]`-coords of `wᵢ`), so the generators are exactly
`w₁, …, wₙ`. The `K(x)`-matrix `Iₙ` (entries `CField.one`/`CField.zero`). -/
def idealIdentity (n : ℕ) : GenDivisor :=
  (List.range n).map (fun i =>
    (List.range n).map (fun j => if i = j then (CField.one : QFunNZG ℚ) else CField.zero))

/-- **Reduce every `K(x)`-entry of a fractional-ideal matrix to lowest terms** `qReduceMat I = I.map
(List.map qReduce)`: apply the **value-preservation-proven** reducer `qReduce` (`ComputableQFunReduce`,
`toQFunNZG_qReduce` unconditional, axiom-clean) entrywise to a `GenDivisor`, cancelling `gcd(num, den)` of
each `ℚ(x)` entry. Because `qReduce` preserves each entry's `ℚ(x)` value, `qReduceMat` returns the **same**
fractional `O`-ideal (the divisor class is unchanged by `toQFunNZG_qReduce`) — a proven-correct
canonicalization, replacing the engine's reliance on the *un*-proven `qReduceNZG` at the swelling ideal
operations' outputs (`idealProduct`'s `n²` cross-product accumulator and product rows, `idealReduce`'s
reduced rows). It cancels any common *polynomial* factor between numerator and denominator; on entries
already polynomial-coprime (e.g. the degree-0 scalar `c/d` entries the Hermite-over-`K[x]` read-back
produces) it is a no-op, so it does not by itself tame a swell that lives purely in the **scalar
ℚ-coefficient** magnitude (the `commonDenomG` content) — that is a separate normalization. -/
def qReduceMat (I : GenDivisor) : GenDivisor :=
  I.map (List.map qReduce)

/-- **Reconstruct a `K(x, y)` element from `[w]`-coordinates** `wToAf basis row = Σⱼ rowⱼ·wⱼ`: the element
of `K(x, y) = K(x)[y]/(f)` whose integral-basis coordinates are `row` (the inverse of `toOCoords`). Turns a
`GenDivisor` row (generator in `[w]`-coords) into the `K(x, y)` element it represents, so `afMul` can
multiply by it. -/
def wToAf (basis : List (CPolyG (QFunNZG ℚ))) (row : List (QFunNZG ℚ)) : CPolyG (QFunNZG ℚ) :=
  (List.range basis.length).foldl (fun acc i =>
    caddG acc (cscaleG (row.getD i CField.zero) (basis.getD i []))) ([] : CPolyG (QFunNZG ℚ))

/-! ### `div(g) = g·O`: the principal divisor (`principalDivisor`)

The principal divisor of `g ∈ K(x, y)` is the fractional ideal `g·O`, generated by `g·w₁, …, g·wₙ`. Row `i`
of its matrix is the `[w]`-coordinates of `g·wᵢ = afMul f g wᵢ`. Since `afMul` returns a *power*-basis
coordinate vector, we convert to `[w]`-coords by `B⁻¹` (`toOCoords`, `B = orderToPowerMatrix basis`). For
the power-basis case `B = Iₙ`, but for a genuine general curve (`y³ = x²`, basis `[1, y, y²/x]`) `B ≠ Iₙ`,
so this conversion is essential. -/

/-- **The principal divisor `div(g) = g·O`** `principalDivisor f basis g`: the fractional `O`-ideal of `g`,
generated by `g·w₁, …, g·wₙ`. Row `i` is the integral-basis coordinates of `g·wᵢ = afMul f g wᵢ`, obtained
by converting `afMul`'s power-basis output to `[w]`-coordinates via `B⁻¹ = (orderToPowerMatrix basis)⁻¹`
(`toOCoords`). The general analogue of the Mumford divisor of a function; `div : K(x, y)ˣ → Pic` is a group
homomorphism (`div(g·h) = div(g)·div(h)`, validated below). Returns the empty matrix if `B` is singular (the
basis is not a basis — never for `integralBasis f`). -/
def principalDivisor (f : CPolyG (QFunNZG ℚ)) (basis : List (CPolyG (QFunNZG ℚ)))
    (g : CPolyG (QFunNZG ℚ)) : GenDivisor :=
  let n := cdegG f
  let B := orderToPowerMatrix n basis
  match matInvG n B with
  | none => []
  | some Binv =>
    basis.map (fun wi => toOCoords Binv n (afMul f g wi))

/-! ### Clearing a fractional ideal to an integral `K[x]`-matrix at a common denominator (`idealClear`)

`O`-ideal arithmetic mixes `K(x)` (the matrix entries) and `K[x]` (the Hermite reduction). To Hermite-reduce
(and to test equality) we **clear** each `K(x)`-matrix to `K[x]` at a common denominator `δ`
(`commonDenomG`): each row times `δ` becomes integral (`clearRowExact`, exact division), so the cleared
matrix is a `PolyMatrix ℚ`. The original ideal is `(1/δ)·(cleared `K[x]`-ideal)` — `δ` is carried alongside
for the comparison. -/

/-- **Clear a fractional ideal to `(δ, integral matrix)`** `idealClear I = (δ, N)`: the common denominator
`δ = commonDenomG I` (`CPolyG ℚ`) and the integral `PolyMatrix ℚ` `N` with `Nᵢⱼ = δ·Iᵢⱼ` (exact division,
`clearRowExact`), so `I = (1/δ)·N` with `N` over `K[x]`. The bridge from the `K(x)`-ideal to the `K[x]`
Hermite reduction. -/
def idealClear (I : GenDivisor) : CPolyG ℚ × PolyMatrix ℚ :=
  let δ : CPolyG ℚ := commonDenomG I
  (δ, I.map (clearRowExact δ))

/-! ### The ideal product `I·J` (the Pic group law) (`idealProduct`)

The product ideal `I·J` is generated by the `n²` cross-products `genᵢ·genₖ` (generator `i` of `I` times
generator `k` of `J`), as `K(x, y)` elements — reconstructed by `wToAf`, multiplied by `afMul`, converted
back to `[w]`-coords by `toOCoords`. These `n²` generators are reduced to `n` by clearing to a common
denominator and `hermiteRowReduce` over `K[x]` (the general analogue of Cantor's composition). The result
is read back as a fractional ideal `(1/δ)·(HNF)`. -/

/-- **The ideal product `I·J`** `idealProduct f basis I J` (the Pic group law / divisor addition): the
fractional `O`-ideal generated by the `n²` cross-products `(genᵢ of I)·(genₖ of J)`. Each cross-product is
reconstructed (`wToAf basis`), multiplied in `K(x, y)` (`afMul f`), and converted back to `[w]`-coordinates
(`toOCoords Binv`, `Binv = (orderToPowerMatrix basis)⁻¹`), giving an `n²×n` matrix over `K(x)`; cleared to a
common denominator `δ` (`commonDenomG` + `clearRowExact`) and `hermiteRowReduce`d over `K[x]` to `n`
generators (`Nhat`), then read back as the fractional ideal `(1/δ)·Nhat` (entries `qxOfFrac (Nhatᵢⱼ) δ`).
The general analogue of Cantor's COMPOSITION — `n²` generators of the product ideal reduced to `n` by Hermite
reduction. Returns `[]` if `B` is singular. -/
def idealProduct (f : CPolyG (QFunNZG ℚ)) (basis : List (CPolyG (QFunNZG ℚ)))
    (I J : GenDivisor) : GenDivisor :=
  let n := cdegG f
  let B := orderToPowerMatrix n basis
  match matInvG n B with
  | none => []
  | some Binv =>
    -- the n² cross-products genᵢ·genₖ in [w]-coords, each entry put in lowest terms (`qReduceMat`,
    -- value-preserving) before the common-denominator clearing below
    let cross : List (List (QFunNZG ℚ)) :=
      qReduceMat (I.flatMap (fun gi =>
        J.map (fun gk =>
          toOCoords Binv n (afMul f (wToAf basis gi) (wToAf basis gk)))))
    -- clear to K[x] at a common denom δ, Hermite-reduce, take the n nonzero rows
    let δ : CPolyG ℚ := commonDenomG cross
    let N : PolyMatrix ℚ := cross.map (clearRowExact δ)
    let nz := (hermiteRowReduce N).filter (fun row => !row.all cisZeroG)
    -- read back the first n rows as the fractional ideal (1/δ)·Nhat, then put every entry in lowest terms
    -- (`qReduceMat`, value-preserving) so the product fed back into the next `idealProduct` is canonical
    qReduceMat ((List.range n).map (fun i =>
      (List.range n).map (fun j =>
        let num := (nz.getD i []).getD j []
        let dd := cnormG δ
        if h : cisZeroG dd = false then qReduceNZG (qxOfFrac num dd h) else CField.zero)))

/-! ### Normalization / equality of fractional ideals (`idealHNF`, `idealEq`, `idealIsIntegral`)

Two fractional ideals are equal iff a common-denominator clearing has the same `K[x]`-row span — i.e. the
same Hermite normal form, after also clearing the *combined* denominator so the two `(δ, N)` are over a
common `δ`. We compare via `idealHNF`: clear, Hermite-reduce, scale the HNF by the per-ideal `δ` cleared to a
shared denominator. A divisor is **integral** iff its matrix is over `K[x]` (`δ = 1` after reduction). -/

/-- **The Hermite normal form of a cleared ideal** `idealHNF I = (δ, H)`: clear `I` to `(δ, N)`
(`idealClear`), Hermite-reduce `N` over `K[x]` (`hermiteRowReduce`), keep the nonzero rows monic-normalized
(`cmonicG` on each entry's leading coefficient cleared row, via `cnormG`). The canonical `K[x]`-presentation
`(1/δ)·H` of the fractional ideal, for the equality test. -/
def idealHNF (I : GenDivisor) : CPolyG ℚ × PolyMatrix ℚ :=
  let (δ, N) := idealClear I
  let H := (hermiteRowReduce N).filter (fun row => !row.all cisZeroG)
  (cnormG δ, H.map (fun row => row.map cnormG))

/-- **`true` iff two fractional ideals are equal** `idealEq I J`: bring both to a common denominator
`δ = δ_I·δ_J`, scale each cleared generator matrix to that `δ` (`δ_J·N_I` and `δ_I·N_J`), Hermite-reduce
both over `K[x]`, and compare the resulting normal forms entrywise (`cisZeroG` of the difference). Two
fractional `O`-ideals are equal iff a common-denominator clearing has the same `K[x]`-row span (same HNF) —
the decision procedure for `div(g)·div(h) = div(g·h)` and `I·O = I`. -/
def idealEq (I J : GenDivisor) : Bool :=
  let (δI, _) := idealClear I
  let (δJ, _) := idealClear J
  -- scale both ideals to the common denom δI·δJ, then compare cleared HNFs
  let scale : CPolyG ℚ → GenDivisor → PolyMatrix ℚ := fun c K =>
    let cc := cnormG c
    K.map (fun row => row.map (fun z =>
      let zz := qReduceNZG z
      let num := zz.1.1
      let den := cnormG zz.1.2
      cdivWf (cmulG cc num) den))
  let NI := scale (cmulG δI δJ) I
  let NJ := scale (cmulG δI δJ) J
  let HI := (hermiteRowReduce NI).filter (fun row => !row.all cisZeroG)
  let HJ := (hermiteRowReduce NJ).filter (fun row => !row.all cisZeroG)
  let n := max HI.length HJ.length
  let w := max (HI.headD []).length (HJ.headD []).length
  (List.range n).all (fun i =>
    (List.range w).all (fun j =>
      cisZeroG (csubG ((HI.getD i []).getD j []) ((HJ.getD i []).getD j []))))

/-- **`true` iff the divisor is integral** `idealIsIntegral I`: every matrix entry is over `K[x]` (no
denominator), i.e. each `Iᵢⱼ` reduces (`qReduceNZG`) to a fraction with `denominator = 1`. An integral
divisor is one contained in the order `O` (`I ⊆ O`, the valuation `≥ 0` at every finite place). -/
def idealIsIntegral (I : GenDivisor) : Bool :=
  I.all (fun row => row.all (fun z =>
    let zz := qReduceNZG z
    cisZeroG (csubG (cnormG zz.1.2) [CField.one])))

end CPolyG

/-! ## ★ Validation over the GENERAL (non-hyperelliptic) curve `y³ = x²` (`native_decide`)

The cuspidal cubic `f = y³ − x²` (`gcuspCubicF`), genus 0, **non-hyperelliptic** (degree 3). Its integral
basis is `[1, y, y²/x]` (`gcuspCubicBasis = integralBasis gcuspCubicF`) — crucially **NOT** the power basis:
the third generator `y²/x` carries a denominator, so the change of basis `B = orderToPowerMatrix` is not the
identity and the `[w]`-coordinate conversions in `principalDivisor`/`idealProduct` are genuinely exercised.
This is the real test that the divisor machinery lifts to arbitrary curves. -/

open CPolyG

/-! ### `div(y)` and `div(y²)` as fractional `O`-ideals -/

/-- The principal divisor `div(y) = y·O` on `y³ = x²` (the fractional ideal generated by
`y·1, y·y, y·(y²/x)` in the `[1, y, y²/x]` coordinates). -/
def gdDivY : GenDivisor := principalDivisor gcuspCubicF gcuspCubicBasis gcuspCubicY

/-- The principal divisor `div(y²) = y²·O` on `y³ = x²` (the fractional ideal generated by
`y²·1, y²·y, y²·(y²/x)`). -/
def gdDivYsq : GenDivisor := principalDivisor gcuspCubicF gcuspCubicBasis gcuspCubicYsq

/-- The identity divisor `O` on `y³ = x²` (the `3×3` identity, generators `1, y, y²/x`). -/
def gdIdentity : GenDivisor := idealIdentity (cdegG gcuspCubicF)

-- Sanity print: the integral basis `[1, y, y²/x]` (coords over ℚ(x); third should carry a 1/x denom).
#eval gcuspCubicBasis.map (fun b => b.map (fun z => ((z.1.1 : List ℚ), (z.1.2 : List ℚ))))

-- Sanity print: div(y) as a [w]-coordinate matrix over ℚ(x).
#eval gdDivY.map (fun row => row.map (fun z => ((z.1.1 : List ℚ), (z.1.2 : List ℚ))))

-- Sanity print: div(y²) as a [w]-coordinate matrix over ℚ(x).
#eval gdDivYsq.map (fun row => row.map (fun z => ((z.1.1 : List ℚ), (z.1.2 : List ℚ))))

-- Sanity print: div(y)·div(y) (should equal div(y²) as an ideal).
#eval (idealProduct gcuspCubicF gcuspCubicBasis gdDivY gdDivY).map
  (fun row => row.map (fun z => ((z.1.1 : List ℚ), (z.1.2 : List ℚ))))

/-! ### ★ The integral basis is genuinely non-trivial (`native_decide`) -/

/-- **★ The integral basis of `y³ = x²` is `[1, y, y²/x]`, NOT the power basis** (`native_decide`): the
third basis vector is `[0, 0, 1/x] = y²/x` (a genuine denominator), so the change of basis `B =
orderToPowerMatrix gcuspCubicBasis` is **not** the identity. This is what makes `principalDivisor` /
`idealProduct` genuinely test the `[w]`-coordinate conversion `B⁻¹` on a general curve (a power-basis curve
would have `B = Iₙ` and hide the conversion). Checked by `w₃ = [0, 0, 1/x]`, `w₁ = 1`, `w₂ = y`. -/
theorem gd_integralBasis_nontrivial :
    (cisZeroG (csubG (gcuspCubicBasis.getD 2 []) [CField.zero, CField.zero, qxOfFrac [1] [0, 1] (by decide)])
      && cisZeroG (csubG (gcuspCubicBasis.getD 0 []) [CField.one])
      && cisZeroG (csubG (gcuspCubicBasis.getD 1 []) [CField.zero, CField.one])) = true := by
  native_decide

/-! ### ★★ The Pic group law `div(y)·div(y) = div(y²)` on `y³ = x²` (`native_decide`)

The headline: `div` is a group homomorphism `K(x, y)ˣ → Pic`, so `div(y)·div(y) = div(y·y) = div(y²)`. This
is the general-curve analogue of `div(P) + div(P) = div(2P)` in the Jacobian — the IDEAL PRODUCT (the general
Cantor composition) realizes the Pic group law. We compute `idealProduct (div y) (div y)` and check it equals
`div(y²)` as fractional ideals (`idealEq`). -/

/-- **★★ THE PIC GROUP LAW: `div(y)·div(y) = div(y²)` on the non-hyperelliptic `y³ = x²`** (`native_decide`):
the ideal product of the principal divisor `div(y)` with itself equals the principal divisor `div(y²)`, i.e.
`div(y)·div(y) = div(y·y)` — `div : K(x, y)ˣ → Pic` is a group HOMOMORPHISM, and the IDEAL PRODUCT
`idealProduct` (the `n²`-cross-products-reduced-by-Hermite, the general analogue of Cantor's composition)
realizes the Pic group law. On a GENERAL (non-power-basis) curve, exercising the `[w]`-coordinate conversion.
The general-curve lift of `div(P) + div(P) = div(2P)`. Checked by `idealEq (idealProduct gdDivY gdDivY)
gdDivYsq`. -/
theorem gd_pic_grouplaw_divY_sq :
    idealEq (idealProduct gcuspCubicF gcuspCubicBasis gdDivY gdDivY) gdDivYsq = true := by native_decide

/-! ### ★ The identity law `I·O = I` (the Pic neutral element) (`native_decide`)

`O` (the integral basis, `idealIdentity`) is the neutral element of the Pic group: `I·O = I` for every
fractional ideal `I`. We check it for `I = div(y)` and `I = div(y²)`. -/

/-- **★ The Pic identity law `div(y)·O = div(y)` on `y³ = x²`** (`native_decide`): the ideal product of
`div(y)` with the identity divisor `O` (`idealIdentity`, the order itself) equals `div(y)` — `O` is the
NEUTRAL element of the Pic group. The general-curve analogue of `D + 0 = D` in the Jacobian. Checked by
`idealEq (idealProduct gdDivY gdIdentity) gdDivY`. -/
theorem gd_pic_identity_divY :
    idealEq (idealProduct gcuspCubicF gcuspCubicBasis gdDivY gdIdentity) gdDivY = true := by native_decide

/-- **★ The Pic identity law `div(y²)·O = div(y²)` on `y³ = x²`** (`native_decide`): the ideal product of
`div(y²)` with the identity `O` equals `div(y²)` — confirming `O` is the Pic neutral element on a second
principal divisor (a `y²`-component divisor). Checked by `idealEq (idealProduct gdDivYsq gdIdentity)
gdDivYsq`. -/
theorem gd_pic_identity_divYsq :
    idealEq (idealProduct gcuspCubicF gcuspCubicBasis gdDivYsq gdIdentity) gdDivYsq = true := by
  native_decide

/-! ### ★ Integrality of the principal divisors (`native_decide`)

`div(y)` and `div(y²)` are integral divisors: `y, y²` are integral functions (no finite poles), so
`y·O ⊆ O` and `y²·O ⊆ O` — their matrices are over `K[x]` (no denominators). -/

/-- **★ `div(y)` and `div(y²)` are integral divisors on `y³ = x²`** (`native_decide`): both
`principalDivisor` matrices are over `K[x]` (every entry reduces to denominator `1`), i.e. `y·O ⊆ O` and
`y²·O ⊆ O` — `y` and `y²` are integral functions (no finite poles), so their principal divisors are
**effective** (integral). The order at every finite place is `≥ 0`. Checked by `idealIsIntegral` on both. -/
theorem gd_divY_divYsq_integral :
    (idealIsIntegral gdDivY && idealIsIntegral gdDivYsq) = true := by native_decide

/-! ### ★★ The end-to-end general-divisor milestone (`native_decide`) -/

/-- **★★ THE GENERAL-CURVE DIVISOR REPRESENTATION + `div(g)` + THE IDEAL PRODUCT (PIC GROUP LAW) COMPUTE AND
VALIDATE** (Trager Ch. 5 §3 / Ch. 6, `native_decide`). On the **non-hyperelliptic** curve `y³ = x²`, whose
integral basis `[1, y, y²/x]` is NOT the power basis (so the `[w]`-coordinate conversion is genuinely
exercised — `gd_integralBasis_nontrivial`):
* divisors are represented as fractional `O`-ideals (`n×n` `K(x)`-matrices in `[w]`-coords), the general lift
  of `ComputableHyperellipticDivisor`'s Mumford pair;
* `div(y)`, `div(y²)` are computed as principal divisors `g·O` (`principalDivisor`);
* the IDEAL PRODUCT (the general Cantor composition, `n²` cross-products reduced by Hermite over `K[x]`)
  realizes the Pic group law: **`div(y)·div(y) = div(y²)`** (`div` a group homomorphism, `gd_pic_grouplaw_divY_sq`);
* the IDENTITY `O` is the Pic neutral element: `I·O = I` (`gd_pic_identity_divY`, `gd_pic_identity_divYsq`);
* `div(y)`, `div(y²)` are integral (`gd_divY_divYsq_integral`).
The engine now represents general-curve divisors as fractional ideals over the integral basis, with `div(g)`
and the ideal product — the foundation the general divisor-class-group / torsion arithmetic runs on. -/
theorem gen_divisor_representation_validates :
    -- the integral basis is genuinely non-trivial (not the power basis)
    (cisZeroG (csubG (gcuspCubicBasis.getD 2 [])
        [CField.zero, CField.zero, qxOfFrac [1] [0, 1] (by decide)]))
    -- the Pic group law div(y)·div(y) = div(y²)
    ∧ idealEq (idealProduct gcuspCubicF gcuspCubicBasis gdDivY gdDivY) gdDivYsq = true
    -- the identity law I·O = I for two principal divisors
    ∧ idealEq (idealProduct gcuspCubicF gcuspCubicBasis gdDivY gdIdentity) gdDivY = true
    ∧ idealEq (idealProduct gcuspCubicF gcuspCubicBasis gdDivYsq gdIdentity) gdDivYsq = true
    -- the principal divisors are integral
    ∧ (idealIsIntegral gdDivY && idealIsIntegral gdDivYsq) = true := by native_decide

/-! ### Deliverable: `#print axioms`

`[propext, Classical.choice, Quot.sound]` plus `Lean.ofReduceBool` (the `native_decide` kernel-reduction
axiom). **No `sorry`, no `sorryAx`, no extra axiom** — `principalDivisor`/`idealProduct`/`idealEq` are
non-recursive compositions over finite-list kernels (`afMul`/`afReduce` use `cmodWf`,
`hermiteRowReduce`/exact division use `cdivWf`, `qReduceNZG` uses the shared fuel-free fraction reducer, and
`matInvG`/`toOCoords`/`commonDenomG` fold over finite `List.range`s). -/

#print axioms gd_integralBasis_nontrivial
-- ★★ The Pic group law div(y)·div(y) = div(y²) on the non-hyperelliptic y³ = x²:
#print axioms gd_pic_grouplaw_divY_sq
-- ★ The identity law I·O = I:
#print axioms gd_pic_identity_divY
#print axioms gd_pic_identity_divYsq
-- ★ Integrality of the principal divisors:
#print axioms gd_divY_divYsq_integral
-- ★★ The end-to-end milestone:
#print axioms gen_divisor_representation_validates

/-! ## The deferred NEXT pieces: the torsion pipeline (order / good reduction)

The general divisor REPRESENTATION (fractional `O`-ideal as a `K(x)`-matrix in `[w]`-coords), the PRINCIPAL
divisor `div(g) = g·O`, the IDEAL PRODUCT `I·J` (the Pic group law / general Cantor composition), the
IDENTITY `O`, and the integral/equality tests land here, `native_decide`-validated on the general curve
`y³ = x²` — the Pic group law `div(y)·div(y) = div(y²)` and the identity `I·O = I` exhibit `div : K(x, y)ˣ →
Pic` as a group homomorphism into the divisor class group. The remaining pieces of the general
divisor-class-group / torsion sub-arc (the general lift of `ComputableCantorComposition` /
`ComputableDivisorOrder` / `ComputablePrincipalGenerator` / `ComputableTorsionLogTerm`, which carry this for
the HYPERELLIPTIC Jacobian), in order:

1. **`idealInverse` / `idealReduce` (toward the reduced divisor).** The INVERSE `I⁻¹ = (O : I) = { z ∈ K(x, y)
   : z·I ⊆ O }` (the colon ideal, computed by the same idealizer-style `B⁻¹`-and-Hermite solve as
   `idealizerOCoords` but with the target `O` rather than `I`); and a REDUCTION bringing a fractional ideal to
   its unique **reduced** representative in each Pic class (the general analogue of Cantor reduction `deg u ≤
   g` — here a `K[x]`-Hermite/Riemann–Roch reduction over the integral basis, minimizing the `K[x]`-degree of
   the generator matrix subject to the ideal class, a Hess-style reduction). With `idealProduct` (this file)
   + `idealInverse` + `idealReduce`, the Pic group is fully computable: `−δ`, `δ₁ + δ₂`, and the reduced
   canonical form of any divisor class.

2. **The ORDER (points of finite order, Trager Ch. 6).** The smallest `m ≥ 1` with `m·δ` **principal** —
   computed by iterating `idealProduct` (`δ, 2δ, 3δ, …` via repeated composition) and, at each `m`, testing
   **principality**: `m·δ` is principal iff its reduced fractional ideal is `g·O` for some `g ∈ K(x, y)`,
   which is exactly an `afLogArgSolve`-style linear test — does the ideal `m·δ` (reduced) have a single
   generator `g` with `(m·δ) = g·O`? (`afLogArgSolve`'s kernel solve for `u` with `div(u) = m·δ` over the
   integral basis is the principality oracle: a nonzero bounded-degree generator exists iff `m·δ` is
   principal.) The order `m` and the generator `g` of `m·δ` give the `(1/m)·log g` term of the non-principal
   integrator branch — the general lift of `ComputablePrincipalGenerator` / `ComputableTorsionLogTerm`.

3. **Good reduction mod `p` for the torsion BOUND (Trager Ch. 6 / Davenport).** To make the search in (2)
   **terminate**, bound `m` by the size of the torsion subgroup of `Pic⁰(C)`, itself bounded via **good
   reduction modulo a prime `p`**: reduce the curve `f mod p` over `𝔽_p` (a good prime, not dividing the
   discriminant / the leading coefficients of the integral basis), compute the **finite** group order
   `|Pic⁰(C)(𝔽_p)|` (the general analogue of the hyperelliptic point-count), and use it as the effective
   torsion bound — only `m ≤ |Pic⁰(C)(𝔽_p)|` need be tried. This is the general lift of
   `ComputableDivisorOrder`'s good-reduction bound from the hyperelliptic Jacobian to an arbitrary curve.

The **divisor representation + `div(g)` + the ideal product** (this file) are the foundation; the
inverse/reduce → order/torsion → good-reduction path is the genuine continuation, the general lift of the
hyperelliptic Mumford/Cantor machinery (`ComputableCantorComposition` … `ComputableTorsionLogTerm`) onto the
fractional-ideal-over-the-integral-basis representation. These are recorded (not formalized) in the
`Sources/Doi_10_1007_b138171` catalog `## NOT YET FORMALIZED` blocks. -/

end DeepWiki.SymbolicIntegration
