import DeepWiki.SymbolicIntegration.RiobooLogToReal

/-! # `LogToReal`'s real/imaginary splits (Bronstein §2.8, p.69)
The `LogToReal` algorithm processes its inputs `R ∈ K[t]` and `S ∈ K[t][x]` by substituting
`t = u + i·v` and collecting real and imaginary parts:
`R(u+i·v) = P(u,v) + i·Q(u,v)` and `S(u+i·v, x) = A(u,v,x) + i·B(u,v,x)`.

This file closes **Stage A**: the polynomial real/imaginary **split** itself. Working in a
commutative ring `S` with a designated `i` (`i² = −1`) over a base ring `K` (the `(u,v)`- or
`(u,v,x)`-ring lives inside `S` as the `K`-subalgebra generated by `u, v, x`), for any polynomial
`R` over `K` we build real-form elements `P, Q` with `aeval (u+i·v) R = P + i·Q` **and** the
conjugate `aeval (u−i·v) R = P − i·Q` — by induction on `R` (the multiplicative monomial step is the
genuine `(P+iQ)(u+iv)` recursion `(Pu−Qv) + i(Pv+Qu)`). Specializing the base `K → K[x]` gives the
bivariate `S(u+i·v, x) = A + i·B` split for free. The conjugate-product **bridge**
`A² + B² = S(a+i·b, x)·S(a−i·b, x)` follows from `add_imag_mul_sub_imag`, feeding the split's `A, B`
straight into `logToReal_conjugate_pair`.

**Stage B** (the conjugate-root selection `P(a,b)=Q(a,b)=0` and the recursion over `R`'s roots) is
reached only at the level of the per-root **criterion** `R(a+i·b) = 0 ↔ P(a,b)=0 ∧ Q(a,b)=0` (over a
char-`0` field where the reals are independent over `i`); the multiset bookkeeping that partitions
`R`'s roots over `K̄` into real roots ⊎ conjugate pairs with the `b > 0` ordered-field selection needs
splitting-field root-counting machinery and is left as the precisely-stated residual. -/

open Polynomial
open scoped Differential

namespace DeepWiki.SymbolicIntegration

section Split
variable {S : Type*} [CommRing S] {K : Type*} [CommRing K] [Algebra K S]

/-- **Real/imaginary split of `R(u+i·v)`** (§2.8, p.69, the `R(u+i·v) = P + i·Q` step of `LogToReal`):
in a commutative ring with `i² = −1`, for any `R ∈ K[t]` there exist real-form `P, Q ∈ S` (in the
`K`-subalgebra generated by `u, v`) with `aeval (u+i·v) R = P + i·Q` **and** the conjugate
`aeval (u−i·v) R = P − i·Q`. Proof by `Polynomial.induction_on`: constants split as `(a, 0)`, sums add
componentwise, and the monomial step is the multiplication recursion `(P+iQ)(u+iv) = (Pu−Qv) +
i(Pv+Qu)` (using `i² = −1`). Example 2.8.3: `R = 4t²+1` gives `P = 4u²−4v²+1`, `Q = 8uv`. -/
theorem exists_realImag_split (i : S) (hi : i ^ 2 = -1) (u v : S) (R : K[X]) :
    ∃ P Q : S, aeval (u + i * v) R = P + i * Q ∧ aeval (u - i * v) R = P - i * Q := by
  induction R using Polynomial.induction_on with
  | C a => exact ⟨algebraMap K S a, 0, by simp, by simp⟩
  | add p q hp hq =>
    obtain ⟨Pp, Qp, hp1, hp2⟩ := hp
    obtain ⟨Pq, Qq, hq1, hq2⟩ := hq
    exact ⟨Pp + Pq, Qp + Qq, by rw [map_add, hp1, hq1]; ring,
      by rw [map_add, hp2, hq2]; ring⟩
  | monomial n a ih =>
    obtain ⟨P, Q, h1, h2⟩ := ih
    refine ⟨P * u - Q * v, P * v + Q * u, ?_, ?_⟩
    · rw [pow_succ, ← mul_assoc, map_mul, h1, aeval_X]
      linear_combination (Q * v) * hi
    · rw [pow_succ, ← mul_assoc, map_mul, h2, aeval_X]
      linear_combination (Q * v) * hi

end Split

section Bivariate
variable {S : Type*} [CommRing S] {K : Type*} [CommRing K]

/-- **Real/imaginary split of `S(u+i·v, x)`** (§2.8, p.69, the `S(u+i·v, x) = A + i·B` step of
`LogToReal`): viewing the bivariate `S ∈ K[t][x]` (here `Sxt : (K[X])[t]`, polynomials in `t` over the
`x`-ring `K[X]`) and substituting `t = u + i·v` in an algebra `E` over `K[X]` with `i² = −1`, there
exist real-form `A, B ∈ E` (over the `x`-ring) with `aeval (u+i·v) Sxt = A + i·B` and the conjugate
`aeval (u−i·v) Sxt = A − i·B`. This is `exists_realImag_split` with the base ring specialized to
`K[X]` — the `x`-variable rides inside the coefficients. Example 2.8.3:
`S = x³ + 2t·x² − 3x − 4t` gives `A = x³ + 2u·x² − 3x − 4u`, `B = 2v·x² − 4v`. -/
theorem exists_realImag_split_bivariate {E : Type*} [CommRing E] [Algebra (K[X]) E]
    (i : E) (hi : i ^ 2 = -1) (u v : E) (Sxt : (K[X])[X]) :
    ∃ A B : E, aeval (u + i * v) Sxt = A + i * B ∧ aeval (u - i * v) Sxt = A - i * B :=
  exists_realImag_split i hi u v Sxt

end Bivariate

section Bridge
variable {S : Type*} [CommRing S]

/-- **Conjugate-product bridge `A²+B² = S(a+ib)·S(a−ib)`** (§2.8, p.69, the bridge behind
`logToReal_conjugate_pair`): if the real/imaginary split gives `S(a+i·b, x) = A + i·B` and
`S(a−i·b, x) = A − i·B` (`i² = −1`), then `A² + B² = S(a+i·b, x)·S(a−i·b, x)` — the product of the two
conjugate evaluations (the `CommRing` form of `add_imag_mul_sub_imag`). -/
theorem sq_add_sq_eq_mul_conj (i A B sPlus sMinus : S) (hi : i ^ 2 = -1)
    (hP : sPlus = A + i * B) (hM : sMinus = A - i * B) :
    A ^ 2 + B ^ 2 = sPlus * sMinus := by
  rw [hP, hM]; linear_combination (B ^ 2) * hi

end Bridge

section RootCriterion
variable {S : Type*} [Field S] [CharZero S]

/-- **Reals are independent over `i`** (§2.8, the linear-independence behind the `b > 0` root
selection): in a char-`0` field with `i² = −1`, if `P + i·Q = 0` **and** its conjugate `P − i·Q = 0`,
then `P = 0 ∧ Q = 0`. Proof: the sum gives `2·P = 0` and the difference `2·i·Q = 0`; char `0` cancels
`2` and `i ≠ 0` cancels `i`. (The conjugate equation supplies the missing half — `P + i·Q = 0` alone
does not force `P = Q = 0` unless `P, Q` are genuinely real.) -/
theorem eq_zero_and_eq_zero_of_add_imag_eq_zero {i P Q : S} (hi : i ^ 2 = -1)
    (h1 : P + i * Q = 0) (h2 : P - i * Q = 0) : P = 0 ∧ Q = 0 := by
  have hi0 : (i : S) ≠ 0 := by rintro rfl; simp at hi
  have hP : (2 : S) * P = 0 := by linear_combination h1 + h2
  have hiQ : (2 : S) * (i * Q) = 0 := by linear_combination h1 - h2
  refine ⟨(mul_eq_zero.mp hP).resolve_left two_ne_zero, ?_⟩
  have hiQz : i * Q = 0 := (mul_eq_zero.mp hiQ).resolve_left two_ne_zero
  exact (mul_eq_zero.mp hiQz).resolve_left hi0

/-- **Conjugate-root selection criterion** (§2.8, p.69, the `P(a,b)=Q(a,b)=0 ⟺ R(a+i·b)=0` step): in a
char-`0` field with `i² = −1` and a conjugation `σ` (`σ i = −i`) that **certifies `P, Q` are real**
(`σ P = P`, `σ Q = Q`), given the split `R(a+i·b) = P + i·Q`, `a+i·b` is a root of `R` iff its real and
imaginary parts both vanish, `R(a+i·b) = 0 ↔ P = 0 ∧ Q = 0`. Forward: conjugating `P + i·Q = 0` gives
the conjugate root `P − i·Q = σ(P+iQ) = 0`, and the pair forces `P = Q = 0`
(`eq_zero_and_eq_zero_of_add_imag_eq_zero`); backward by substitution. The realness of `P, Q` is
**essential** — `P + i·Q = 0` alone does not force `P = Q = 0` (e.g. `P = i, Q = −1`). The book selects
the conjugate pairs of roots by exactly this `P = Q = 0` condition (over `b > 0`). -/
theorem aeval_eq_zero_iff_realImag_eq_zero {i P Q vPlus : S} (hi : i ^ 2 = -1)
    (σ : S →+* S) (hσi : σ i = -i) (hσP : σ P = P) (hσQ : σ Q = Q)
    (hP : vPlus = P + i * Q) :
    vPlus = 0 ↔ P = 0 ∧ Q = 0 := by
  refine ⟨fun h => ?_, fun ⟨hP0, hQ0⟩ => by rw [hP, hP0, hQ0]; ring⟩
  have h1 : P + i * Q = 0 := hP ▸ h
  -- conjugate `P + i·Q = 0` to get the conjugate root `P − i·Q = 0`
  have h2 : P - i * Q = 0 := by
    have hc := congrArg σ h1
    rw [map_add, map_mul, hσi, hσP, hσQ, map_zero, neg_mul] at hc
    linear_combination hc
  exact eq_zero_and_eq_zero_of_add_imag_eq_zero hi h1 h2

end RootCriterion

section ConjugatePairFromSplit
variable {R : Type*} [Field R] [Differential R]

/-- **Conjugate-pair real form from the split** (§2.8, p.69, the `LogToReal` summand assembled from the
split): feeding the split's real-form `A, B` (`S(a+i·b, x) = A + i·B`, `S(a−i·b, x) = A − i·B`,
`A²+B² ≠ 0`, `i² = −1`) into `logToReal_conjugate_pair`, the conjugate pair `a ± i·b` contributes the
**real** function's derivative
`(a+i·b)·logDeriv(S(a+i·b)) + (a−i·b)·logDeriv(S(a−i·b)) = a·logDeriv(A²+B²) +
b·(i·logDeriv((A+i·B)/(A−i·B)))` — i.e. `a·log(A²+B²) + b·LogToAtan(A,B)`. This is exactly the
inner summand of `LogToReal`'s output, now stated on the **split** evaluations `S(a±i·b, x)`. -/
theorem logToReal_conjugate_pair_of_split {i a b A B sPlus sMinus : R} (hi : i ^ 2 = -1)
    (hAB : A ^ 2 + B ^ 2 ≠ 0) (hP : sPlus = A + i * B) (hM : sMinus = A - i * B) :
    (a + i * b) * Differential.logDeriv sPlus + (a - i * b) * Differential.logDeriv sMinus
      = a * Differential.logDeriv (A ^ 2 + B ^ 2)
        + b * (i * Differential.logDeriv ((A + i * B) / (A - i * B))) := by
  rw [hP, hM]
  exact logToReal_conjugate_pair hi hAB

end ConjugatePairFromSplit

section Restatements
variable {S : Type*} [CommRing S] {K : Type*} [CommRing K] [Algebra K S]

/-- Restatement of the **real/imaginary split** against the book wording (§2.8, p.69): "write
`R(u+i·v)` as `P(u,v) + i·Q(u,v)`" — for any `R ∈ K[t]` there are real-form `P, Q` with
`R(u+i·v) = P + i·Q`, certified real by the conjugate `R(u−i·v) = P − i·Q`. -/
example (i : S) (hi : i ^ 2 = -1) (u v : S) (R : K[X]) :
    ∃ P Q : S, aeval (u + i * v) R = P + i * Q ∧ aeval (u - i * v) R = P - i * Q :=
  exists_realImag_split i hi u v R

/-- Restatement of the **conjugate-product bridge** against the book wording (§2.8, p.69): with
`S(a+i·b, x) = A + i·B` (`i² = −1`), `A(a,b,x)² + B(a,b,x)²` is the product of the conjugate values
`S(a+i·b, x)·S(a−i·b, x)` — the argument of the real logarithm `a·log(A²+B²)`. -/
example {T : Type*} [CommRing T] (i A B sP sM : T) (hi : i ^ 2 = -1)
    (hP : sP = A + i * B) (hM : sM = A - i * B) : A ^ 2 + B ^ 2 = sP * sM :=
  sq_add_sq_eq_mul_conj i A B sP sM hi hP hM

end Restatements

end DeepWiki.SymbolicIntegration
